### ISSUE TITLE
Add daily worklog trends by user

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1000]
## Description
To track user's worklog info, we need calc the worklog data daily by user.  
![image](https://user-images.githubusercontent.com/11383928/147075146-596562f4-eb0d-49ad-acba-28bbcedc15b0.png)  
The snapshot shows worklog trends in a sprint. And we also need this data for each user.  
![image](https://user-images.githubusercontent.com/11383928/147075612-31611f9a-0ed3-4c4c-bb24-dfba3ff62523.png)

## Has the Feature been Requested Before?
No

## Additional context
Consider timezone, maybe we should refer the design of sprint_issue_burndown entity.

**Comment by narrowizard** [comment]
- Added `added_worklog_minutes` column to `sprint_trends` entity. (Daily worklog by sprint)
- Aggregate users' worklog from 'worklog` entity. (Daily worklog by users)

**Comment by klesh** [comment]
Closed by PR #852
