### ISSUE TITLE
Git Repo Extractor: A new plugin that directly collect data from git repos

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1004]
## Why another git collector?

At the moment, DevLake supports collecting git data through Gitlab/Github API. This approach has two major limitations:

1. Data coverage issue: Gitlab/Github API only covers a subset of git data
2. Efficiency / API rate limit issue: for very large repos or an organization with many repos, collecting data through Gitlab/Github API is not the most efficient solution

In this issue, we propose a new plugin that can directly collect data from git repos, which would overcome the limitations described above.

## What data to collect?

This new plugin will collect the following entities in [the domain layer schema](https://github.com/merico-dev/lake/issues/700).

1. repos (repo's metadata)
2. commits (commit's metadata)
2. repo_commits (association between repos and commits)
3. repo_languages (a repo's language composition)
4. commit_files (file changes associated with a commit)
5. refs (the mapping between refs and commits)

Plus the necessary new tables for storing a branch's own commits.

## How this plugin will be used?

1. This plugin is an executable whose input is a git repo and may be configured to either directly write to a data store (e.g., MySQL or other databases) or a data file (e.g., parquet or other formats), depending on the environment.
2. This plugin will be invoked whenever target repos detect new changes, so ideally it should have an incremental mode.

## Challenges

1. How to avoid counting the same code contribution multiple times due to rebase / cherry-pick / squash / revert / fork? #1016 
2. How to efficiently compute and store each branch's own commits? #1011 
3. How to make the plugin work in an incremental manner? How does it know what it has previously collected? Is the incremental approach even possible if we consider rebasing?

**Comment by warren830** [comment]
resolved in https://github.com/merico-dev/lake/pull/1109
