### ISSUE TITLE
QA - "As a lake developer, I want migrations run when I run make dev"

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1008]
This is a QA test case for #979 

Here is the test procedure I conducted. Changes have been pushed to migrations-v2

QA Flow - Dev

- Clone repo
- Switch to migration branch
- Copy .env file
- Run make compose (mysql, Grafana)
- DBs get created without tables from running docker-compose-startup.sql script
<img width="370" alt="SCHEMAS" src="https://user-images.githubusercontent.com/27032263/147365787-6fa6bad5-5f65-4c3b-9e81-1bea855c5d9b.png">

- unexpected: Where are the schema migrations tables?
- Trying again by dropping tables manually
- Same result 
- Creating tables manually with ```mysql -u root --protocol=tcp -padmin -h localhost -e "USE lake; CREATE TABLE IF NOT EXISTS schema_migrations (version bigint NOT NULL DEFAULT 1,dirty tinyint(1) NOT NULL DEFAULT 0, PRIMARY KEY (version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;”```
<img width="372" alt="SCHEMAS" src="https://user-images.githubusercontent.com/27032263/147365820-8b708b6c-9a9b-48b7-84c9-33f25efc2949.png">

- Running ```make dev``` to see migrations
- Received 2 errors on migrations:
<img width="889" alt="devlake" src="https://user-images.githubusercontent.com/27032263/147365829-7aa21606-05c7-4b16-9f4a-2622fdcb055e.png">

- Paths are wrong: 
    - /Users/kevinkline/Merico/test/devlake/bin/lake/db/migration/.
    - /Users/kevinkline/Merico/test/devlake/plugins/compound/migration/.
- Changed MIGRATIONS_PATH to fix
- Now 2 errors:
<img width="886" alt="Building plugin github to binpluginsgithubgithub  so" src="https://user-images.githubusercontent.com/27032263/147365843-19b8e8df-a855-42d5-bae5-2a9c38cc0207.png">

- 2nd one is caused by the fact there IS no migration folder for compound
<img width="196" alt="plugins" src="https://user-images.githubusercontent.com/27032263/147365859-48ed9302-3016-4207-ac38-b414f63e997d.png">

- Fix added to check if path exists
- Only error now:
<img width="763" alt="INFO RunDomainLayerMigrationsUp Could not run migrations UP no change" src="https://user-images.githubusercontent.com/27032263/147365865-cba5dc18-6cca-445b-8598-1e1a4a8bfd04.png">

- However, all tables are migrated:
<img width="340" alt="feishu_meeting_top_user_items" src="https://user-images.githubusercontent.com/27032263/147365870-bcab267c-4abe-4a31-a820-8d9ea8f9bc2b.png">

- [x] This satisfies the following condition:  “As a lake developer, I want migrations run when I run make dev”

**Comment by klesh** [comment]
Resolved by #1057
