### ISSUE TITLE
QA "As a developer with no database, I need to be able to create the databases from scratch with a make command"

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1009]
This is a test condition for #979 

This is the QA process. The result is that the make command did not work on my machine, but the commands _within_ the make command _do_ work individually. I'm not sure how to resolve the issue at this time.

1. Drop databases ‘lake’ and ‘lake_test’
<img width="370" alt="SCHEMAS" src="https://user-images.githubusercontent.com/27032263/147366588-4b2a97b1-6f30-4c07-bd19-4b0cc97bc8fa.png">

2. Run make init-db
3. Error:
<img width="887" alt="binsh mysal conmand not found" src="https://user-images.githubusercontent.com/27032263/147366594-4480aaac-6f66-427f-94d6-85d875545996.png">

4. Run commands manually (not sure how to fix, already have mysql path)
<img width="887" alt="Pasted Graphic 9" src="https://user-images.githubusercontent.com/27032263/147366603-0ce25b41-d989-413b-98d4-079710c52c3e.png">

5. Run commands manually (from init-db)
<img width="886" alt="ATE DATABASE IF NOT EXISTS loke_te" src="https://user-images.githubusercontent.com/27032263/147366609-31e278cc-378e-4157-9f7f-cfee016beee2.png">

6. Commands work individually
<img width="265" alt="schema_migrations" src="https://user-images.githubusercontent.com/27032263/147366619-e9fb4627-32f7-45b9-8c4e-3d10dcbc40db.png">

## Conclusion

The individual commands work; however the ```make``` command didn't work on my machine. This could be an issue for me locally, but possibly others. Recommend others test and make documentation if needed.

**Comment by kevin-kline** [comment]
@joncodo Is this needed? @hezyin is asking why. Can we provide an explanation?

**Comment by klesh** [comment]
Resolved
