### ISSUE TITLE
QA: "As a developer that wants to run all tests locally, When make test-models is run, a test_db is ready and all migrations are run by the tests."

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1010]
This is a test condition for #979 

QA Flow - Dev

Condition: “As a developer that wants to run all tests locally, When make test-models is run, a test_db is ready and all migrations are run by the tests.”

1. Project cloned
2. DBs created manually using make (or mysql) commands
<img width="321" alt="schema_migrations" src="https://user-images.githubusercontent.com/27032263/147370147-e94e6ea7-345f-4303-9f82-f61927db385e.png">

3. Run ```make test-models```
4. 3 Errors:
<img width="886" alt="TEST=true go test  modelstest -v" src="https://user-images.githubusercontent.com/27032263/147370154-4bd8ca35-4f62-43d0-86e6-6b7a462ed1c8.png">

5. Turn off RunPluginMigrations first to isolate
6. Start with “RunDomainLayerMigrationsUp - no scheme”
7. Locate function call
<img width="801" alt="INFO RunDomainLayerMigrationsUp Could not init migrate For UP no scheme" src="https://user-images.githubusercontent.com/27032263/147370159-24a563c8-3d55-4891-ab77-b47365f3444a.png">

8. MigrateDb called before TestMain (both call run migrations)
9. init() (models) called first
<img width="807" alt="TEST=true go test  modelstest -v" src="https://user-images.githubusercontent.com/27032263/147370167-71346060-a8b7-496c-8416-b02a86d9a96b.png">

10. Logging out paths for migrate db
<img width="886" alt="KEVIN  inft models" src="https://user-images.githubusercontent.com/27032263/147370172-ad0dad97-51f3-4040-8c93-70e138280806.png">

11. Two problems
    1. Migrations path gets working directory as ```models/test```. Appending ```/db/migrations``` doesn’t work when there is no such path 
    2. We are not getting variables from .env in GetConnectionString() method
12. First problem 
    1. “How do we get the directory of the migration scripts?”
        1. If we use os.Getwd(), then we get different results based on test execution or main execution. 
        2. If we use absolute path, we get different results in the cloud. So we must get it dynamically.
    2. We need to get the directory dynamically, so we need to make the entry point consistent. The entry point changes based on execution though. 
    3. We can use case statements on one-by-one basis, but that is not a great solution at all.
<img width="740" alt="Pasted Graphic 18" src="https://user-images.githubusercontent.com/27032263/147370185-6d50fd35-946a-4bd8-a465-d01f584b2a5c.png">

13. Second problem
    1. Path to .env doesn’t load (same problem of entry point)
    2. There is no .env in “/models/test” so we need to look elsewhere and refactor LoadConfigFile to include other paths ** This solution involves renaming ```.env``` to ```config.env```
<img width="394" alt="func LoadConfigFile() (viper  Viper, error) {" src="https://user-images.githubusercontent.com/27032263/147370192-070d2487-a933-4a1e-ab40-6036c311fa48.png">

14. Once these two issues are fixed, the first error disappears, meaning that migrations were run on “lake” (NOT “lake_test”). This is because the init() function fires automatically when ```go test``` is run. 
<img width="885" alt="Pasted Graphic 20" src="https://user-images.githubusercontent.com/27032263/147370199-5b5ad4b6-32e2-4825-852c-c76b0c2caf20.png">

15. We still need to tackle the problem of running migrations on “lake_test” which we mean to do via the TestMain() function which fires before all tests. 

TBC

**Comment by kevin-kline** [comment]
Testing Continued:

2nd Error in TestMain call to RunDomainMigrationsDown / Up

1. Run make models-test
2. Error:
<img width="881" alt="KEVIN  migrationsPath fiteUserskevinklineMericotestdevlokemodelstest" src="https://user-images.githubusercontent.com/27032263/147371834-5aea0434-fcc0-47c3-9dbc-405f5a80e158.png">

3. Fixed path (same fix as earlier:
<img width="494" alt="Pasted Graphic 22" src="https://user-images.githubusercontent.com/27032263/147371838-030521ee-5378-4cd6-ae7e-4d5bfa47d99c.png">

4. Error is gone, but tests fail (migrations didn’t work)
<img width="890" alt="INFO no change" src="https://user-images.githubusercontent.com/27032263/147371845-89b13fee-72c4-4898-8980-024a3e333b0f.png">

5. Found connection string to wrong DB for migrations up:
<img width="880" alt="devlake git (migrations-v2) x make models-test" src="https://user-images.githubusercontent.com/27032263/147371847-ad90843d-97c1-4d36-aa7f-8f6cb33bde82.png">

6. Temporary fix for short term:
<img width="845" alt="driver, connectionString)" src="https://user-images.githubusercontent.com/27032263/147371849-c4c27c5c-1392-4af1-b920-7ba957467426.png">

7. Tests pass now; migrations worked.
<img width="940" alt="gration" src="https://user-images.githubusercontent.com/27032263/147371850-e9f04126-033f-4406-ae04-86372469395f.png">

<img width="295" alt="SCHEMAS" src="https://user-images.githubusercontent.com/27032263/147371853-23a71aa4-58cb-4ac1-a5aa-967d47ca5c7d.png">

**Comment by klesh** [comment]
Resolved
