### ISSUE TITLE
How to efficiently compute and store each branch's own commits?

### ISSUE THREAD

**Issue by liangjingyang** [merico-dev/lake#1011]
## The association between git references and commits

Related to #1004 

### Query the commits by a reference

When a customer consider to measure how much work has been put into a release or reference, means they want to get the difference between two different references. An implicit condition is that we must select a benchmark reference and compare the feature reference with the benchmark to find the workload they putted into.
客户想度量在某个版本或Ref上投入了多少工作量的时候，客户是想知道两个不同Ref的差异。一个隐含的条件就是，我们必须选取一个基准Ref（主干Ref），用度量Ref与基准进行对比，才能找到相应的工作量。

input | implicit input | output
-- | -- | --
Release Ref | Main Ref | commit difference set

To generalize, the customer wants to know how much content is added in a release compared to the previous release, which requires our data to be able to figure out the difference of the given two references.
泛化一下，用户还想知道，一个版本相对于上一个版本新增了多少内容，这就要求我们的数据能够挖掘出两个给定的Refs之间的差集。

input 1 | input 2 | output
-- | -- | --
Release Ref1 | Release Ref2 | Commit difference set

Both of the above are to find the commit set of a reference and compare the differences of two references.
以上两种，都是根据Ref找到commits集合，以及对比集合的差异。

### Query the references by a commit

Another type of requirement is that users want to know which references contain a feature or a bugfix . This situation can be abstracted as query the references by one or more commits.
另外一类需求，用户想知道某个特性或修复，都包含在哪些Refs里。这种情况我们可以抽象为一个或多个可能，查找他们所在的Ref集合。

input | output
-- | --
commit(s) | Ref set

### Requirements
1. List references
2. List the difference set of the commits between Ref1 and Main
3. List the difference set of the commits between Ref1 and Ref2
4. List the references which contain the given commit

### Assumption
1. There is a main branch, or the main branch can be figured out by certain patterns.
2. The comparable references are the main branch or the branches that checked out from the main branch. 

----

### Solution 1

Store the difference between a reference and the main reference in database.

##### refs

Field name | type | description
-- | -- | --
ref | string | The reference name
commit | string | The commit id that this reference included
is_main | string | Whether the ref is main branch
merge_base | string | The merge base commit of the main ref and the current ref

##### ref_commits

Field name | type | description
-- | -- | --
ref | string | The reference name
commit | string | The commit id that this reference included

##### commits

Field name | type | description
-- | -- | --
... | ... | ...
sha | string | The commit id
topo_seq | int | The sequence number in reverse topological order. (from git repo, not API)Used by listing the references which contain the given commit

##### Full data import

1. List revisions of all references in reverse topological order, and upsert into commits table. (commits.*)
2. Figure out the main reference. (refs.is_main)
3. Extract all references we needed, include the main reference, the commit they point to, and the merge base commit between them and the main reference, and upsert into refs table. (refs.ref, refs.commit, refs.is_main, refs.merge_base)
4. Iterate references and get the difference set of the commits between each reference and main reference, upsert into ref_commits table (ref_commits.*)

##### Incremental data import

1. The same as full data import.
2. Figure out the main reference. (refs.is_main)
3. If the main reference changed, it' better to truncate the refs and ref_commits tables, and all steps should be the same as full data import.
4. Else, TODO

#### How to Implement the requirements

1. List references
    1. select ref from refs
2. List the difference set of the commits between Ref1 and Main
     1. select * from ref_commits where ref = 'Ref1'
3. List the difference set of the commits between Ref1 and Ref2
     1. select * from ref_commits where ref = 'Ref1' and commit not in (select commit from ref_commits where ref = 'Ref2')
     2. select * from commits where topo_seq > 'Ref1.merge_base.topo_seq' and topo_seq <= 'Ref2.merge_base.topo_seq'
     3. Union a and b.(Assumption.2)
4. List the references which contain the given commit Sha1. (Assumption.2)
     1. select * from ref_commits where commit = 'Sha1'
     2. If the result of a is not empty, that means the result is the references which contain the commit Sha1
     3. If the result of a is empty, then select * from commits where sha = 'Sha1'
     4. If the result of c is empty, that means the Sha1 doesn't belong to this git repo.
     5. If the result of c is not empty, select * from refs join commits on refs.merge_base = commits.sha where commits.topo_seq >= sha1.topo_seq
     6. The result of e and the Main reference are the references which contain the commit Sha1.

#### Notes

1. Extracting data from git is a mapping of the current state of git, and does not go back to the historical state (there must be a hook for each reference change, and the logic is more complicated)
2. The current plan only considers unmerged references. If it has been merged, no matter whether the branch is deleted or not, it will not be processed. If we want to analyze the merged references, consider finding a way through merge commit instead of referencing.
3. Whether to introduce the serial number of the topological order in the commits table needs to be considered again. If it needs to be introduced, do the topological sequence numbers need to be continuous?
4. The ref_commits table only saves the association relationship of non-main reference. If a commit is not found in the ref_commits table, it means that it is the commit of the main reference. But it is not certain whether it belongs to other references, it requires additional calculations.

----

### Solution 2

Store the difference between every 2 references in database.

##### refs

Field name | type | description
-- | -- | --
ref | string | The reference name
commit | string | The commit id that this reference included
is_main | string | Whether the ref is main branch
merge_base | string | The merge base commit of the main ref and the current ref

##### ref_diffs

Field name | type | description
-- | -- | --
commit | string | The commit id that the 'ref' contains
ref | string | The reference which contains the commit
base_ref | String | The base reference

##### Full data import

1. List revisions of all references in reverse topological order, and upsert into commits table. (commits.*)
2. Figure out the main reference. (refs.is_main)
3. Extract all references we needed, include the main reference, the commit they point to, and the merge base commit between them and the main reference, and upsert into refs table. (refs.ref, refs.commit, refs.is_main, refs.merge_base)
4. Iterate references and get the difference set of the commits between each reference and main reference, upsert into ref_commits table (ref_diffs.*)

##### Incremental data import

1. The same as full data import(commits.*).
2. Figure out the main reference. (refs.is_main)
3. TODO

#### How to Implement the requirements

1. List references
   1. select ref from refs
2. List the difference set of the commits between Ref1 and Main
   1. select * from ref_diffs where ref = 'Ref1' and base_ref = 'Main'
3. List the difference set of the commits between Ref1 and Ref2
   1. select * from ref_diffs where ref = 'Ref1' and base_ref = 'Ref2'
4. List the references which contain the given commit Sha1.
   1. select distinct ref from ref_diffs where commit = 'Sha1' and base_ref = 'Main'
   2. If the result of a is not empty, that means the result is the references which contain the commit Sha1
   3. If the result of a is empty, then select * from commits where sha = 'Sha1'
   4. If the result of c is empty, that means the Sha1 doesn't belong to this git repo.
   5. If the result of c is not empty, select ref from refs where ref not in (select base_ref from ref_diffs where commit = 'Sha1' and ref = 'Main') 
   6. The result of e and the Main reference are the references which contain the commit Sha1.

----

### Solution 3

Most of Solution 3 is the same as Solution 2, except that `ref_diffs` is not computed at the data extraction stage, but computed after the data is written to the database.

**Comment by klesh** [comment]
Final Decision: Solution 3, and covered by #1068
