### ISSUE TITLE
Error when collecting GitHub issue labels in tag 0.5.0

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1017]
## Describe the bug
Error when collecting GitHub issue labels in tag 0.5.0

## To Reproduce
1. Follow the README to install DevLake 0.5.0 by docker-compose
2. Configure the Github endpoint and token
3. Trigger the collection of 'DevLake' project
`[
  [
    {
      "Plugin": "github",
      "Options": {
        "repositoryName": "lake",
        "owner": "merico-dev"
      }
    }
  ]
]`
4. Input command `docker-compose logs -f devlake` to see logs
5. see error

## Expected behavior
Successfully collect GitHub issue labels.

## Screenshots
![FTASwWiTAR](https://user-images.githubusercontent.com/14050754/147673738-c8e9d7fb-cc8e-4086-ac47-62cf69ea7838.png)

**Comment by klesh** [comment]
[retry 2] indicates a Network Connection failure,  try `GITHUB_PROXY`...
BTW. did your `pipeline` show a `FAIL` status correctly?

**Comment by klesh** [comment]
To be addressed on #1032
