### ISSUE TITLE
Release management: how should we deal with `docker-compose.yml`

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1028]
## Description
As issue #1026 mentioned, users don't have to clone our repo in order to deploy  devlake, a single `docker-compose.yml` is sufficient. With #1021 merged, we now have a Github Action to build and push docker images for us on `tag` pushing.

Previously, we had our `docker-compose.yml` from main branch fixed to latest released images tags, but it was problematic:
1. Our develop branch is the `main` branch, having images tags `docker-compose` fixed is not intuitive, no matther how `main` evolve, the `docker-compose.yml` stay at a certain point of time, and has nothing to do with our codebase.
2. Whenever we need to verify our local built images, we have to change the tags manually and revert it back whenever we need to commit some fixes for any problem we found during the verification process.

### Solution 1: `docker-compose.yml` points to `latest` on main, to `vX.Y.Z` on `tag`
1. `docker-compose.yml` from main branch will alway points to `latest`, it makes sense the develop branch having a cutting edge build for developer, and easier for us to do local image build and verification
2. `docker-compose.yml` from tag will be fixed to a set of images tags, so users can select a particular version when needed, also it's benificial for developer to do bug tracking.
This approach will require one more step before releasing: fix the images tags to certain versions

### Solution 2: `docker-compose.yml` moved to separate repo @narrowizard 
1. the `docker-compose.yml` from our main branch to be changed as `realtime build`, it will have `devlake` / `config-ui` / `grafana`  images built  automatically. it makes perfect sense for a develop branch.
2. all released `docker-compose.yml` hold by a separate repo, user can clone this repo and choose whatever version they like. 

### Solution 3: derived from Solution 2, except releasing fixed `docker-compose.yml` as attachment
1. same as solution 2
2. we write a script to generate a fixed `docker-compose.yml`, attach a generated `docker-compose.yml` as attachment when we releasing

### Solution 4
This is similar to solution two as well but does not require a new repo for the docker-compose file. Instead, we have a the same docker-compose.yml file in our main repo but we also have other files like docker-compose.test.yml or docker-compose.dev.yml or docker-compose-060.yml

```
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
```

You can then run this command: `docker-compose -f myfile.yml up`

https://docs.docker.com/compose/reference/#specifying-multiple-compose-files

### Comparision

|                         | Solution 1😄                                | Solution 2 ❤️                          | Solution 3 👍  |  Solution 4 🚀 |
| ----------------------- | ---------------------------------------- | ------------------------------------ | ---------- |---------- |
| Intuitive               | Good                                     | Perfect                              | Perfect    | Perfect |
| Image verification      | Perfect(using the real remote image)     | Good(build on scene)                 | Good       | Perfect|
| Release burden          | Bad(manually fix images tags)            | Bad(we had to maintain another repo) | Ok         | Ok |
| Good release likelihood | Bad(likely to forget fixing images tags) | Ok(easy to fix even if we forgot)    | Ok         | Ok|
| Developer friendly      | Ok                                       | Good(easy to do grafana development) | Good       | Perfect |

Feel free to propose new approach, or vote for your favourite solution by `reaction` from top right corner
😄 for Solution 1
❤️ for Solution 2
👍 for Solution 3
🚀  for Solution 4

## Has the Feature been Requested Before?
No

**Comment by narrowizard** [comment]
## Why we should provide a `docker-compose.yml` file?
1. For developers, 
2.  For quick start, 
3. For further usage(in prodution mode), users must mantain the `docker-compose.yml` themselves(maybe use solution 2 mentioned above or other ways), because they should
    - Persist the storage
    - Chose plugins they need
    - Config port and port expose
    - Chose version of lake

For case 1 and case 2, I think a `docker-compose.yml` file with `latest` tag is satisfied.  
For case 3, we don't need(actually cannot) to cover the situation.  
So my suggestion is that we only need to provide a `docker-compose.yml` file  with `latest` version in this repo.

**Comment by joncodo** [comment]
> So my suggestion is that we only need to provide a docker-compose.yml file with latest tag(or build in real time) in this repo.

I like this idea. If people want to use our product, they don't need our code. Just the docker-compose.yml file. In this case, we can keep this as a separate file or repo.

**Comment by klesh** [comment]
@joncodo Ok, let's try solution 4 on next release. You can check and close this issue now.

**Comment by joncodo** [comment]
I will do this for next release

**Comment by klesh** [comment]
Applied on v0.7.0, resolved
