### ISSUE TITLE
add `issue_changelog` entity in domain layer schema

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1031]
## Description
1. As a product manager, I want to see the `assignee` changelog of an issue, so that I know who is involved in an issue cycle. Based on that, I can calculate how much effort each assignee contributes to the same issue. This is a temporary solution before we achieve cross-tool user mapping.
2. As a product manager, I want to see the `status` changelog of an issue, so that I know for how long a requirement stays in each status. Based on that, I can find the bottleneck of delivering user value (accomplish user requirement).

## Describe the solution you'd like
According to domain layer schema in #700 , add the `issue_changelog` entity in the domain layer
![image](https://user-images.githubusercontent.com/14050754/148027041-d67574ce-2b51-4f3a-a176-4969338ef71d.png)

- [ ] update Jira collector (high priority)
- [ ] update Github collector (low priority)

## Additional context
N/A

**Comment by klesh** [comment]
We had `change` already, further development is addressed by #1778
