### ISSUE TITLE
Convert the config ui from using /env to use /ping

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1033]
## Description

In the config ui now, we call /env to see if the server is up.

I want to remove that route and replace it with /ping

- [x] remove the /env route
- [x] Add /ping route
- [x] Get the front end to use the new route

**Comment by joncodo** [comment]
Would this work for you @e2corporation ?

**Comment by e2corporation** [comment]
@joncodo Sounds good, will get this handled once it's added to an iteration.
