### ISSUE TITLE
Incorrect Datetime Value when collecting from gitlab

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1036]
## Describe the bug
In this scenario, a user has already used lake in the past and wants to re-collect data. They have data in their database before getting started.

When using the triggers page for gitlab in config-ui and having a gitlab_projects record already for vdev, gitlab fails to collect the project again.

## To Reproduce
1. Start the app with `docker compose up -d`
2. Open config ui and invoke collection from the triggers page.

Triggers config used:

```
GITLAB_ENDPOINT=https://gitlab.com/api/v4/
```

From config ui

```
8:8967944,8967945;9:8967946,8967947
```

NOTE: I was unable to get back to the triggers config that I used. Testing further on this in another ticket

![Screen Shot 2022-01-05 at 3 04 03 PM](https://user-images.githubusercontent.com/3011407/148274135-1c7ea805-9b90-47a5-a2d9-c5a73dba3d83.png)

ERROR From Docker Container:

```
[retry 0] GET https://gitlab.com/api/v4/projects/8967944/pipelines/441965158 - /app/plugins/core/apiclient.go:177 - \x1b[0m<nil>"

time="2022-01-05T18:57:42Z" level=info msg="\x1b[35m[DEBUG >>> [api-client][retry 0] GET https://gitlab.com/api/v4/projects/8967944/pipelines/442083520 - /app/plugins/core/apiclient.go:177 - \x1b[0m<nil>"

time="2022-01-05T18:57:42Z" level=info msg="\x1b[35m[DEBUG >>> [api-client][retry 0] GET https://gitlab.com/api/v4/projects/8967944/pipelines/442085144 - /app/plugins/core/apiclient.go:177 - \x1b[0m<nil>"

time="2022-01-05T18:57:42Z" level=info msg="\x1b[36m[INFO >>> running plugin progress - /app/services/task.go:193 - \x1b[0m 1 gitlab 70.000000%"

time="2022-01-05T18:57:42Z" level=error msg="\x1b[31m[ERROR >>> pipeline task failed - /app/services/pipeline.go:172 - \x1b[0mError 1292: Incorrect datetime value: '0000-00-00' for column 'created_date' at row 1"


2022/01/05 18:57:42 /app/plugins/gitlab/tasks/gitlab_repo_converter.go:20 Error 1292: Incorrect datetime value: '0000-00-00' for column 'created_date' at row 1

[3.007ms] [rows:0] INSERT INTO `repos` (`id`,`created_at`,`updated_at`,`name`,`url`,`description`,`owner_id`,`language`,`forked_from`,`created_date`,`updated_date`,`deleted`) VALUES ('gitlab:GitlabProject:8967944','2022-01-05 18:57:42.452','2022-01-05 18:57:42.452','vdev.co','https://gitlab.com/merico-dev/ee/vdev.co','','','','','0000-00-00 00:00:00',NULL,false) ON DUPLICATE KEY UPDATE `updated_at`=VALUES(`updated_at`),`name`=VALUES(`name`),`url`=VALUES(`url`),`description`=VALUES(`description`),`owner_id`=VALUES(`owner_id`),`language`=VALUES(`language`),`forked_from`=VALUES(`forked_from`),`created_date`=VALUES(`created_date`),`updated_date`=VALUES(`updated_date`),`deleted`=VALUES(`deleted`)
```

## Expected behavior
We should be able to collect all repos from gitlab

## Screenshots
This is the current record that I have. I believe this is the conflict in the insert statement from above
<img width="953" alt="Screen Shot 2022-01-05 at 3 08 32 PM" src="https://user-images.githubusercontent.com/3011407/148274590-f6085e32-a638-40eb-97fe-b45b4f128e0e.png">

And here are the tasks from my DB
<img width="1257" alt="Screen Shot 2022-01-05 at 3 16 21 PM" src="https://user-images.githubusercontent.com/3011407/148275641-afa70ee2-71c8-48a7-9222-7dd3193a1ce7.png">

## Additional context
I did have this gitlab_project in my DB already. It looks like there might have been a conflict in records and the new one it tried to overwrite with may have had null for a date or something?

**Comment by e2corporation** [comment]
@joncodo In case you need to restart a _**failed**_ pipeline with the same settings, Obtain the `Pipeline ID` after a Manual Trigger. Navigate to `/pipelines/activity/:pipelineID`. Click on the purple **Restart** action, it will redirect you to the Create New Pipeline flow with the previous task configuration pre-populated, and you'll just have to click Run.

<img width="1083" alt="Screen Shot 2022-01-05 at 2 41 36 PM" src="https://user-images.githubusercontent.com/1742233/148278774-42f2dc10-060e-4406-993d-29de29213667.png">

**Comment by e2corporation** [comment]
Relates to #998

**Comment by klesh** [comment]
Seems like I force pushed a wrong commit into my PR #1012, and I thought it was merged successfully....
Thanks to GIT, I managed to salvage the code,

See PR #1040
