### ISSUE TITLE
Creating a new pipeline is not easy to understand the red textbox validation box at the top

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1045]
This red box tells me that I have written the name of the pipeline wrong or that there is a conflict. What is the intended behaviour? @e2corporation 

![Screen Shot 2022-01-07 at 9 43 47 AM](https://user-images.githubusercontent.com/3011407/148552568-da4029c2-deed-423e-ac30-0fffc0fbac35.png)

**Comment by joncodo** [comment]
When I keep the default name and turn on Jenkins, it makes the box green.
![Screen Shot 2022-01-07 at 9 45 56 AM](https://user-images.githubusercontent.com/3011407/148552806-d7912580-eab2-4e24-bd70-119b86481e45.png)

**Comment by e2corporation** [comment]
@joncodo The Input field highlights red when there's a conflict with the entire configuration. It's intended to let the user know that the pipeline is not ready to run, once all settings are entered correctly it lights up success/green.

**Comment by e2corporation** [comment]
Only 1 provider is required to be a valid configuration, so once Jenkins is enabled (which requires 0 settings) it considers it valid. IF we don't want to run Jenkins alone we can simply require an additional provider if jenkins is the only 1 selected.

**Comment by e2corporation** [comment]
See main validation rules in the validation Hook for Pipelines `@/hooks/usePipelineValidation.jsx`. The main create form considers the pipeline valid with:

```
  const isValidPipeline = () => {
    return enabledProviders.length >= 1 &&
      pipelineName !== '' &&
      pipelineName.length > 2 &&
      validationErrors.length === 0
  }
```

for Jenkins we could further restrict it so that another provider must be enabled and Jenkins cannot be run by itself.

**Comment by joncodo** [comment]
> @joncodo The Input field highlights red when there's a conflict with the entire configuration. It's intended to let the user know that the pipeline is not ready to run, once all settings are entered correctly it lights up success/green.

I hear what you are saying and that makes sense now but at first glance, it seems like there is a problem with the text field itself. Maybe more of a full page warning is needed in some way? I don't know much about design and it's up to you. I just got confused here for a minute which makes me want to see if there is an easier way to convey this to the user

**Comment by e2corporation** [comment]
Yea I can see this making the user alert for a few seconds, I opted for highlighting the field red as a better alternative to too many messages. I think after user runs a couple pipelines it won't be a big issue and they will understand that it's simply indicating to them the form is not ready to run, however there are ways we could improve this.

**Comment by e2corporation** [comment]
Additionally there is a clear warning message at the bottom of the Submit button, like we do on the Integration forms. Whenever the field is read, there is always a message shown....

<img width="456" alt="Screen Shot 2022-01-07 at 9 02 56 AM" src="https://user-images.githubusercontent.com/1742233/148554871-535d1a7c-dbbb-456b-8ae7-e52e7e096936.png">

**Comment by joncodo** [comment]
I will leave it to you to decide. Feel free to close this issue. :)

**Comment by e2corporation** [comment]
I'd like to keep it open and will find a way to lessen the confusion with some additional tweaks. A popover err message near the red input would also make it more apparent.

**Comment by e2corporation** [comment]
Also a pipeline name is **required** and it if the user Blanks/Nulls the field or makes it less than 2 characters in length it will also trigger validation err.

**Comment by e2corporation** [comment]
This can be closed for now future validation enhancements can come under another ticket.
