### ISSUE TITLE
When cancelling a pipeline, the wording seems a bit confusing

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1048]
Not sure on the right design here. Just pointing it out

The user wants to cancel the job
The user is presented with another cancel button

Maybe a good idea would be to show "Are you sure?" + Cancel button + X in top right of modal?

![Screen Shot 2022-01-07 at 9 54 37 AM](https://user-images.githubusercontent.com/3011407/148553885-3851e658-aaa1-4ec7-8957-99ab31a75181.png)

**Comment by e2corporation** [comment]
Another bug that needs to be logged is that we need to DELAY a cancel action after first attempt. The backend takes a few minutes to cancel the pipeline.... so the user can send a cancel request again until backend finishes. My plan for this was to add a throttle delay, so if user cancels pipeline 123, we wait 30seconds before allowing another cancel request for the same pipeline to let the backend finish and cancel.

**Comment by e2corporation** [comment]
the second cancel action in the popover should have been labeled "NO" instead

**Comment by e2corporation** [comment]
Partial wording change has been applied with #1047. The cancel popover contains "NO" instead of a repetitive "cancel" for added clarity.
