### ISSUE TITLE
Improve pipeline debugging experience

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1050]
## Description
Currently, pipeline contains only error message itself, which is not so helpful for user to understand what went wrong in most cases, @narrowizard suggested we may add more information to help both user and us to identify which step went wrong.

## Describe the solution you'd like
1. Add field `FailedSubTask` to `tasks` table to indicate which step failed
2. Define a `SubTaskError` struct with fields `SubTaskName` along side error message to hold information during runtime
3. All `plugin.Execute` return `SubTaskError` when it failed on sub task with specific `SubTaskName`
4. `services/task.RunTask` check if returned error was a `SubTaskError` and save `SubTaskName` as `FailedSubTask` into `tasks` table.

By doing so, user and us can know better which step did error ocurr.

## Has the Feature been Requested Before?
No

## Additional context
EE need this for a better user experience.
![image](https://user-images.githubusercontent.com/61080/151558702-5aaec154-ef97-4cf1-adb9-8f365eac49fe.png)
dont know which step failed, not helping

**Comment by kevin-kline** [comment]
This looks like a really nice change to developer experience to give more context to the errors. I think it's a good approach.

**Comment by warren830** [comment]
# PLAN OF ATTACK
- [ ] Change table.tasks to contain  FailedSubTask field
- [ ] Define a SubTaskError struct with fields SubTaskName along side error message to hold information during runtime
- [ ] github-plugin.Execute return SubTaskError when it failed on sub task with specific SubTaskName
- [ ] services/task.RunTask check if returned error was a SubTaskError and save SubTaskName as FailedSubTask into tasks table.
- [ ] jira-plugin.Execute return SubTaskError when it failed on sub task with specific SubTaskName
- [ ] gitlab-plugin.Execute return SubTaskError when it failed on sub task with specific SubTaskName
- [ ] jenkins-plugin.Execute return SubTaskError when it failed on sub task with specific SubTaskName
