### ISSUE TITLE
config-ui: pipelines - activity multi-stage concept

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#1054]
### Config - UI  Pipelines / Pipeline Activity

We don't need this on the **Create** form as yet, but want to update the multi-stage display on the **Activity** screen for a pipeline.

- [x] Develop concept for a multi-stage pipeline on the Activity Page.

**Comment by e2corporation** [comment]
### Multi-Stage Concept UX
Concept mockups attached below showing **Multi-stage Pipeline Run ID 440**. Progression assumes a positive path, UI would update colors and states accordingly if a task were to fail.
```
⚠️ Some tasks shown such as "AE Engine" are hypothetical, it reflects an 
auto-created task that the backend would add to a specific stage under specific circumstances.
```

- 4 Stage Pipeline 
- 9 Total Tasks

**Stage 01**
- Jenkins
- JIRA `582718`

**Stage 02**
- JIRA `8`
- AE Engine

**Stage 03**
- GitLab `8967944`
- GitLab `4967944`
- GitLab `1967944`
- Merge Requests

**Stage 04**
- GitHub `merico-dev/lake`

![pipeline-440-multistage-stage-01](https://user-images.githubusercontent.com/1742233/149349393-07ae8af8-fdf6-4cb9-9b36-4d8c00c3ed5c.png)
![pipeline-440-multistage-stage-02](https://user-images.githubusercontent.com/1742233/149349402-aa6b79fb-94b1-4da9-9140-93e5e5a733fb.png)

**Comment by joncodo** [comment]
@Startrekzky and @klesh please provide feedback

**Comment by e2corporation** [comment]
I can add a toggle switch to control vertical vs horizontal layout.

**Comment by hezyin** [comment]
@klesh I don't think there's much difference between the vertical and horizontal layout and thus doesn't have a strong preference. The current layout is modeled after Gitlab's pipeline page.  @Startrekzky do you feel it's worth changing the design to vertical?

**Comment by Startrekzky** [comment]
> @klesh I don't think there's much difference between the vertical and horizontal layout and thus doesn't have a strong preference. The current layout is modeled after Gitlab's pipeline page. @Startrekzky do you feel it's worth changing the design to vertical?

Thanks @e2corporation, I like the overall design. Some thoughts on design details.
1. I don't have a strong preference for horizontal or vertical layouts either. I think the horizontal layout is an elegant solution to indicate the flow of information. My only concern about this approach is that if the stages are too many, the user needs to slide a lot to the right to see the full information. However, if the estimated total count of stages <= 5, the horizontal layout won't be a problem. 
2. Can we highlight the overall progress on this page? I think most users' primary goal is to check the overall progress.
![image](https://user-images.githubusercontent.com/14050754/149928995-48d42331-832b-4569-92be-ea3148d49a74.png)
3. Can we weaken the 'Cancel' button? It's an important function, but it's useful only when tasks get stuck. Our goal is to lower the task stuck rate to the minimum.
4. Does the current backend support canceling specific tasks in a stage? @klesh 
![image](https://user-images.githubusercontent.com/14050754/149930345-ab04ef60-a69e-4330-bfae-024cd7253e51.png)

**Comment by e2corporation** [comment]
@Startrekzky 

> I don't have a strong preference for horizontal or vertical layouts either. I think the horizontal layout is an elegant solution to indicate the flow of information. My only concern about this approach is that if the stages are too many, the user needs to slide a lot to the right to see the full information. However, if the estimated total count of stages <= 5, the horizontal layout won't be a problem.

@hezyin  has recommended that we proceed with horizontal layout (columns) for now based on feedback from daily standup meeting on 01/18/22.

> Can we highlight the overall progress on this page? I think most users' primary goal is to check the overall progress.
image

In the live version the completed task count is color coded in green, this area is a bit out of scope for this multi-stage ticket but we can see about adjusting this area. That bit of text was never a primary focus in previous design sessions since user is mainly interested in overall pipeline status, task progress is also easily viewed already.

Can we weaken the 'Cancel' button? It's an important function, but it's useful only when tasks get stuck. Our goal is to lower the task stuck rate to the minimum.

> I don't think this was designed for solely just stuck tasks, since we cannot currently cancel tasks that are stuck in running. 

This is one of the primary actions on the page, and it has a 2 step confirm process. We can look into changing the default inactive color to gray or something more neutral.

> Does the current backend support canceling specific tasks in a stage?

This "pause" icon is _not_ a user controlled action, these icon indicators in the task modules are **Status** Icons. The pause icon will be replaced with another icon instead to reduce confusion.

**Comment by e2corporation** [comment]
Implementation/Development Ticket created and added to `v0.7.0` iteration.
- #1077

**Comment by e2corporation** [comment]
Closing this ticket since concept has been approved and development ticket was created.
