### ISSUE TITLE
gitlab test connect res code is 401

### ISSUE THREAD

**Issue by yunweigo** [merico-dev/lake#1058]
## Question

The code of gitlab auth test is oauth token header , but  description in the document  is private-token.  Is the description correct？
```
"Authorization": fmt.Sprintf("Bearer %v", input.Query.Get("auth"))
```

## Screenshots
![image](https://user-images.githubusercontent.com/22978136/148894638-a3d1bd89-6268-4da7-a56e-3617cefc753f.png)

**Comment by warren830** [comment]
fixed in https://github.com/merico-dev/lake/pull/1298
