### ISSUE TITLE
Refactor some tasks did not care the scope parameter

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1060]
## Description

![image](https://user-images.githubusercontent.com/61080/149049263-010cd139-a7db-43ac-8119-ae8763015bab.png)

What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

## Has the Feature been Requested Before?
Please link any other

**Comment by kevin-kline** [comment]
I understand this will help limit the process of conversion to focus only on a single project (vs. all projects). That seems like a good change to me. I would only say to Klesh please don't leave the issue template in its default state when writing an issue :)
