### ISSUE TITLE
Remove `compound` plugin

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1065]
## Description
Now we connect jira / gitlab on Domain Layer level, `compound` plugin is not needed anymore.

## Describe the solution you'd like

- [ ] Finish #1020 first
- [ ] Remove `compound` plugin from Backend
- [ ] Remove setting following setting from `config-ui`
![image](https://user-images.githubusercontent.com/61080/149723951-765d5a9d-ab55-496b-951a-f39557029d21.png)

## Has the Feature been Requested Before?
No

**Comment by warren830** [comment]
can we delete compound directly?
