### ISSUE TITLE
Should not contain password in log

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1066]
## Describe the bug
When I called `/plugins/jira/test` api to test connection, the access log print out my auth info (it includes my jira endpoint and jira password). It causes a security problem once I want to provide the log when creating an issue.

## To Reproduce
1. Call `/plugins/jira/test` api and it occurs.

## Expected behavior
Should not print password info in log.

## Screenshots
![image](https://user-images.githubusercontent.com/11383928/149738179-5e3dff9e-0299-46a9-90e7-cd224c129dfc.png)

## Additional context
https://github.com/merico-dev/lake/issues/536

**Comment by warren830** [comment]
After discussing with @klesh , here is the suggestion:
Change GET method to POST to hide query info

**Comment by narrowizard** [comment]
Fixed by #1085
