### ISSUE TITLE
Failed when running jira task

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1067]
## Describe the bug
Sometimes it report an error when I create pipeline with jira tasks. 

## To Reproduce
Not sure.

## Expected behavior
It should sync jira data successfully without error. If there are duplicated data, it should be updated instead of panic.

## Screenshots
![zYnzX84WVc](https://user-images.githubusercontent.com/11383928/149737765-e6efcee8-d7d4-43bc-86d5-3aa59980944e.png)

## Additional context
Version: v0.6.0

**Comment by klesh** [comment]
This is a concurreny read/write error.
When concurrent tasks are trying to insert same record with `FindOrCreate` method, one of them failed with confliction.
Solution: ignore this particualar error

**Comment by narrowizard** [comment]
Seems fixed by #1075  
Closed, feel free to reopen or comment if this issue still exist.
