### ISSUE TITLE
GitLab collection fails on small project (MR notes / MR commits)

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1080]
## Describe the bug
GitLab collection for merge request commits and merge request notes fails on a small project. There appears to be something going wrong with the FetchWithPagination method getting the total pages. It continues to send requests indefinitely. ```page``` and ```per_page``` params appear incorrect.

## To Reproduce
1. Start DevLake
2. Send GitLab request to small project (example: https://gitlab.com/kevin-kline/test-project)
3. Watch too many requests occur

## Expected behavior
It should collect from only 1 page and be done.

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/150183391-d2532eb8-4357-477e-aad8-c3f17d0cb32a.png)

**Comment by warren830** [comment]
Will be fixed after raw layer implementation
