### ISSUE TITLE
Github and Gitlab Multi Data Source and Project Ids

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1082]
## Description
I think I heard we need to support many repos per user for Ping Cap requirements? Can you confirm @Startrekzky ?

## Describe the solution you'd like
Just like Jira, we need to support several sources of data and several different project ids to collect.

## Has the Feature been Requested Before?
I think we had some information in #455 but that ticket is really old.

In the end, users have more that one github or gitlab repo that they are interested in. We need to support that.

However, one thing to think about is that users may want to see grafana data on a per repo basis so we need to make sure we still support that.

**Comment by joncodo** [comment]
@Startrekzky to prioritize and assign to itteration

**Comment by warren830** [comment]
We need to add parameter projectId for gitlab sub tasks. github has beed resolved
