### ISSUE TITLE
Do we need to collect comments from reviews on pull requests (GitHub collection)?

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1089]
## Question
Do we need to collect comments from reviews of pull requests (GitHub collection)?

## Additional context
Currently, we are only collecting direct comments on pull requests. If we want to collect comments from reviews of pull requests, we need to make a new collection task to collect reviews on each pull request and also comments on each review. 

Before we answer this, we must consider the cost on performance and rate limits. GitHub rate limits are already very low, and this (in my opinion) would be a lot of requests for low value. It would also add considerable time to collection on an already pretty slow process. 

That being said, I came across this fact while performing QA tasks, and thought it was at least relevant enough to mention, and have some discussion if it is something important to any prospective or current users. This is probably a decision for @Startrekzky who may know more about business requirements.

**Comment by Startrekzky** [comment]
Hi @kevin-kline , thanks for bringing this up. I've considered collecting pull request comments when designing domain layer schema, see table `pull_request_comments` in the domain layer schema in #700.
However, I'm not going to schedule it for the next 1 or 2 milestones as we have lots of higher priorities.
