### ISSUE TITLE
GitHub Plugin: Pull Request Commits relationship

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1090]
## Describe the bug
When we collect `github_pull_request_commits`, if an existing commit has been merged on a newer pull request, we update the existing commit's column "pull_request_id" to the newer pull request.

## Solution
The `pull_request_id` column on `github_pull_request_commits` is obsolete. We should never use this column as a reference. It implies a one-to-many relationship, which is invalid. Instead we should always be using the association table `github_pull_request_commit_pull_requests`, which is currently working perfectly as intended to associate pull requests with their commits in a many-to-many relationship (a pull request can have one or more commits, and a commit can belong to one or more pull requests). 

In fact, we already are using this table to store data properly. However, to avoid any mistakes or confusion in the future, _**I strongly recommend removing the column `pull_request_id` on the table `github_pull_request_commits`**_

**Comment by kevin-kline** [comment]
You can see an example with this commit sha: "ad1e1164c62eb2646bcccfe981a12bd509decc59"
![image](https://user-images.githubusercontent.com/27032263/150415766-99bbf534-7aad-4303-bedc-cf3f54d12d04.png)

It belongs to two PRs, #132 and #180. If you look it up as a `pull_request_commit`, it's only associated to #180 

![image](https://user-images.githubusercontent.com/27032263/150416115-6592b3aa-d8c1-4eb4-8996-b5bbfd4f8f23.png)
![image](https://user-images.githubusercontent.com/27032263/150416146-ea516538-955d-4d09-87c7-d82c60b95334.png)

**Comment by klesh** [comment]
redesigned, no longer an issue.
