### ISSUE TITLE
std_status in jira_issues should be status_key rather than status_category

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1092]
## Describe the bug
Since field `status_category` is language sensitive, we cannot using it in different situations. The values will change when we changed our language settings in jira.  
Also, It's better to transfom `new`, `indeterminate`, `done` to `To Do`, `In Progress`, `Done` to fit our domain layer schema design.

## Screenshots
![Ew9hUOD6Ps](https://user-images.githubusercontent.com/11383928/150474431-6f2abe45-5aee-43d7-8369-ad85a6a31cf3.png)

**Comment by Startrekzky** [comment]
Is status_key the unique id of a status category?

**Comment by Startrekzky** [comment]
Already fixed.
