### ISSUE TITLE
"board_repos" table not being used (Domain Layer)

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1100]
## Describe the bug
`board_repos` table not being used (Domain Layer). In theory, it we would be converting Jira data to have this. Maybe it is a cross between code hosting and issue management tools? We should remove it to reduce confusion, or make it work if it is needed.

@klesh please comment if you have more information.

**Comment by klesh** [comment]
This table is to replace `jira_board_gitlab_project` table.
Please check #1020   #1065
