### ISSUE TITLE
Domain layer naming: "Changelogs"

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1101]
## Question
Right now, there is some confusion about what "Changelogs" in the domain layer refers to. It appears that it is "Changelog Items" that are converted to "Changelogs" in the domain layer, not "Changelogs". Why is this? Can we rename these tables to be less confustion?

@klesh @Startrekzky @joncodo

**Comment by klesh** [comment]
most of the time, `Changelog` has only one related `ChangelogItems` , sometimes it is multiple when user update multiple fields of an issue in one go, but is irrelavent to anaylsis that i can think of, so it was flatten out to simplify our algo, and this could avoid table join for user.
we can discuss if anyone has second thought.
@Startrekzky @joncodo

**Comment by Startrekzky** [comment]
This will be taken into consideration in the future data model design.
