### ISSUE TITLE
"Sprint_Issues" data not matching "Jira_sprint_issues"

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1102]
## Question
There are more records of `sprint_issues` than `jira_sprint_issues` after running the Jira plugin. I expect the same number after conversion. Is there any valid reason why there would be more after conversion? @klesh 

jira_sprint_issues: 9577
sprint_issues: 10490

**Comment by klesh** [comment]
@mindlesscloud I think we need to delete the relationship before insertion, so that removed issues can be flush out from Domain Layer

**Comment by klesh** [comment]
Resolved altogether during v0.10 refactor
