### ISSUE TITLE
Not Collecting Emails on GitHub Users

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1104]
## Describe the bug
We are not Collecting Emails on GitHub Users. We should.

![image](https://user-images.githubusercontent.com/27032263/150600102-f8bac913-8d90-4ae9-a501-c179059f1ef6.png)

**Comment by joncodo** [comment]
@Startrekzky This seems like it is worth looking into more in future iterations.

**Comment by warren830** [comment]
not sure if we need this?

**Comment by klesh** [comment]
Resolved.
