### ISSUE TITLE
GitLab: Merge Request Notes 

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#1105]
## Question
We are collecting / storing 2 types of MR notes in GitLab.
1. `system` = 1 (non-human)
2. `system` = 0 (human)

My question is: Do we have a use for the first type (non-human notes)? If not, should we only be saving human comments? 

I want to bring this issue to everyone's attention to make sure we are only using the 2nd type when we are computing metrics relating to human comments.

@Startrekzky @klesh

**Comment by warren830** [comment]
I think we can just keep notes with system = 1, we may use it for future metrics?

**Comment by klesh** [comment]
Not sure, will discuss when we run into same real scenario. Close it for now.
