### ISSUE TITLE
Config-UI for GitlabCI

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1120]
## Description
We have supported GitlabCI for months, but users still can't see the configure via Config-UI, as there's no entry for `GitlabCI` in the integration page and pipeline page.

## Describe the solution you'd like
The configuration of the GitlabCI plugin is similar to the Jenkins Plugin. Please talk to @joncodo to get more information about this plugin.

## Has the Feature been Requested Before?
No

**Comment by e2corporation** [comment]
Discuss and implement after `v0.9.0`

**Comment by e2corporation** [comment]
@klesh Backend will need to implement the necessary data source endpoints for this provider, ie (`http://localhost:4000/api/plugins/gitlabci/sources`)

Provider Resource Key : `gitlabci`

**Comment by e2corporation** [comment]
Placed on `HOLD`

**Comment by Startrekzky** [comment]
Closed as this issue doesn't exist.
