### ISSUE TITLE
Main readme update proposal

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1124]
1. Team code Icon is broken

<img width="452" alt="Screen Shot 2022-01-26 at 11 00 57 AM" src="https://user-images.githubusercontent.com/3011407/151187820-469c24ff-49a0-43e5-96fd-63141697bbb6.png">

2. Main screenshot is out of date
<img width="1032" alt="Screen Shot 2022-01-26 at 11 01 24 AM" src="https://user-images.githubusercontent.com/3011407/151187951-57d2ee3f-8081-4ff1-aa2f-86afe54827f9.png">

3. Config ui screenshots will be out of date once we merge in the multi stage code
<img width="490" alt="Screen Shot 2022-01-26 at 11 09 11 AM" src="https://user-images.githubusercontent.com/3011407/151189530-b5a8118f-8085-4d0f-80bc-8170596fadfb.png">

4. Do we still have 20+ metrics? Maybe this should be re-worded to the three questions we solve
<img width="867" alt="Screen Shot 2022-01-26 at 11 11 16 AM" src="https://user-images.githubusercontent.com/3011407/151189958-1090f9d6-95b3-49ed-ae2f-89c102cbe4f3.png">

5. We support more plugins now but I think these are the only 4 in the config ui. They are also the only four that can be used by the every day developer. Should we update this list?
<img width="716" alt="Screen Shot 2022-01-26 at 11 12 29 AM" src="https://user-images.githubusercontent.com/3011407/151190251-0e4a17f7-562c-4c8e-aea3-ee4c1cfdba93.png">

6. Update the readme to no longer get users to go to the triggers page. Instead, we should tell them how to set up a pipeline
<img width="587" alt="Screen Shot 2022-01-26 at 11 14 06 AM" src="https://user-images.githubusercontent.com/3011407/151190472-c50a0280-6172-4655-83dd-007a1fe93766.png">
<img width="622" alt="Screen Shot 2022-01-26 at 11 16 02 AM" src="https://user-images.githubusercontent.com/3011407/151190767-cd66106a-7db1-4613-8909-c5f2858f33a6.png">

7. We no longer support compose profiles
<img width="473" alt="Screen Shot 2022-01-26 at 11 15 22 AM" src="https://user-images.githubusercontent.com/3011407/151190671-e896cb7a-4f2f-4da6-b7db-c7c0dfef3028.png">

I am going to go ahead and fix all of these but maybe @Startrekzky can look this over to validate it is what he wants

**Comment by joncodo** [comment]
From @hezyin 

1. No action
2. No Action
3. No Action
4. No Action
5. Add git repo extractor plugin
6. Yes, change
7. Yes, change

**Comment by Startrekzky** [comment]
Resolved
