### ISSUE TITLE
github plugin hangs indefinitely if repo didn't exist

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1126]
## Describe the bug
![image](https://user-images.githubusercontent.com/61080/151213959-4f706a0c-aeaf-438c-9c2f-429e9dab1e47.png)

## To Reproduce
1. Create new pipeline for github plugin
2. Set `owner` and `repositoryName` to sth that doesn't actually exist
3. See `unmarshal failed` error message on `devlake` console
4. Pipeline/Task statuses keep showing `RUNNING` forever

## Expected behavior
Pipeline/Task statuses should be `FAILED`

**Comment by Startrekzky** [comment]
Already fixed in other PR.
