### ISSUE TITLE
Pingcap repo has too many commits on staging

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1133]
## Describe the bug
When I look in the DB here: 52.89.41.35:44306, I see this:

`SELECT count(*) FROM lake.github_commits;` = 133958
`SELECT count(*) FROM lake.commits;` = 21059

But in github, I see `16610` commits

<img width="1194" alt="Screen Shot 2022-01-27 at 10 55 12 AM" src="https://user-images.githubusercontent.com/3011407/151383611-7a080e98-7e20-4c31-b24c-3ca8e9630241.png">

## Assumptions

I think 133958 is too many. I also think that there is something up with the situation where 133958 commits are not in domain layer?

Is this what we expect @klesh @Startrekzky ?

**Comment by joncodo** [comment]
From git, we can see that 21070 is the correct number of commits to have

<img width="752" alt="Screen Shot 2022-01-27 at 2 58 28 PM" src="https://user-images.githubusercontent.com/3011407/151425650-3e8b8f32-9533-4756-ae99-db2e837d13ae.png">

**Comment by joncodo** [comment]
### Summary of Current Status:
The domain layer seems to have the right commits. So this is not release blocking in my opinion.

### What seems broken 
The tool layer having too many commits. This needs to be further validated to find out why this happened on staging.

### What we can try next
- We can run the gitrepo extractor on its own locally to see if we get 138k commits again or a different number
- We can ask @klesh if he collected the data from different repos
- We can look at the 138k commits and see which ones are not in the tidb repo and see if we can figure out which repo they came from
- We can look at all the correct commits in the github_commits table and see if they all happened in the same time interval for collection based on created_at. Maybe this was several attempts at collection or the DB was not clean when we started?

**Comment by klesh** [comment]
commits from PRs are more than commits from repo is expected IIRC, and that information came from .... you @joncodo and @kevin-kline during github pull request commits collection development

**Comment by joncodo** [comment]
<img width="1198" alt="Screen Shot 2022-01-28 at 9 05 56 AM" src="https://user-images.githubusercontent.com/3011407/151551976-39938d7b-b9e0-4e53-b66e-884190e1d76b.png">

**Comment by joncodo** [comment]
I am closing this issue since @klesh believes this is not a real issue we need to solve.

**Comment by klesh** [comment]
@joncodo I could be wrong though, it would be greate if you could fact check @😊

**Comment by joncodo** [comment]
Will do

**Comment by joncodo** [comment]
So I think these commits still exist in githubs database but no longer exist in the main project. When I clone the project, I do not see 133k commits. I think what has happened is that there were too many commits in the project and it took too long to download. So the maintainers squashed a bunch of commits. If you look here:

https://github.com/pingcap/tidb/search?q=squash&type=issues

You can see the maintainers asking contributors to squash their commits. This leads me to believe that this practice is used in their workflow. I think they even use the merge and squash option in github. I can prove that here:

So this user has made a PR that was merged: https://github.com/pingcap/tidb/pull/31984/commits

It has 9 commits

<img width="1676" alt="Screen Shot 2022-01-28 at 1 46 45 PM" src="https://user-images.githubusercontent.com/3011407/151596365-2b3722a0-8a49-40f5-866e-250a9146bf3a.png">

None of them are in the main git repo with `git show <sha>`

However, if you search all commits for the name of the PR,

`git log --all --grep="executor"`

You can find the single merge commit in the code

<img width="525" alt="Screen Shot 2022-01-28 at 1 46 49 PM" src="https://user-images.githubusercontent.com/3011407/151596567-734fee4e-2772-41b0-9d30-2fa7ef08940c.png">

Therefore, I believe the code we have is working as expected
