### ISSUE TITLE
How do domainlayer.issues relate to domainlayer.repos

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1136]
## Question
If I have collected from two different repos with github collection, I expect there to be two records in the `repos` table. Since there are more than one repo that an issue can belong to, how would I write a sql query to find the matching results?

The issues model:
<img width="311" alt="Screen Shot 2022-01-27 at 11 33 50 AM" src="https://user-images.githubusercontent.com/3011407/151390853-f0a8fd8a-2c84-44dc-b6d4-ff4ad8b1a4fa.png">

The repo model:
<img width="275" alt="Screen Shot 2022-01-27 at 11 34 19 AM" src="https://user-images.githubusercontent.com/3011407/151390932-3b9eb7d1-ac9e-4239-99d9-5016a5966b05.png">

I guess I expected a join table here. Am I doing this wrong? @klesh

**Comment by klesh** [comment]
they don't need a connection.
`issues` are connecting to `board` via `board_issues`.
Github has two roles: CodeHosting / TicketManagement
So a github repo will be convert to both Repo and Board
