### ISSUE TITLE
Add '_' before tool layer tables to differentiate them from domain layer tables

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1146]
## Description
The 2 series of tables are mixed up:
- for users who have no idea the difference between the tool-layer and domain-layer tables: be confused about why there're 2 issues tables, Github_issues and issues. 
- for users who know the difference: it's hard to find a table in the DB management tool as domain layer tables are mixed with tool layer tables.

![iXK5VEMxu1](https://user-images.githubusercontent.com/14050754/151532072-62424f07-2d15-4a1e-b997-ec5f691a9bc7.png)

## A better practice
Clear difference by table name: `_raw`, `_tmp`, or with no `_`.
![image](https://user-images.githubusercontent.com/14050754/151533161-63daa2f1-6943-4a81-aa47-4515724cfc5f.png)

**Comment by klesh** [comment]
Will be addressed by #1414
