### ISSUE TITLE
grafana password got reset after service restarted

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1155]
## Describe the bug
![middle_img_v2_54bdc4d2-9a55-4926-96e9-37114ef8700g](https://user-images.githubusercontent.com/61080/151643170-ad9b6093-baab-4c46-83a9-0093fef5edf5.png)

## To Reproduce
1. Change `mysql` password in `docker-compose.yml`
2. Update `mysql` password in `grafana` datasource
3. Click on `save & test`, make sure connection is working
4. Restart `grafana` service by running `docker-compose restart grafana`
5. Go to `gafana` data source page, click on `save & test`, see error

## Expected behavior
mysql password won't get reset in grafana

**Comment by Startrekzky** [comment]
resolved
