### ISSUE TITLE
Store pull request labels in table.pull_request

### ISSUE THREAD

**Issue by warren830** [merico-dev/lake#1166]
## Description
Store all pull requests in table.pull_request_labels

## Describe the solution you'd like
When converting pullRequestLabels, store them into table.pull_request_labels according to Domain Layer Schema

**Comment by warren830** [comment]
# PLAN OF ATTACK
- [ ] Create pull_request_labels on domain layer 
- [ ] Add task to convert github_pull_request_labels to pull_request_labels

**Comment by klesh** [comment]
resolved
