### ISSUE TITLE
demo return 503

### ISSUE THREAD

**Issue by qixiaobo** [merico-dev/lake#1196]
## Documentation Scope
README
## Describe the Change
demo return 503 
## Screenshots
![image](https://user-images.githubusercontent.com/2881751/153380657-ff763e82-4019-4947-ae12-fa2ca25e8de4.png)

**Comment by qixiaobo** [comment]
https://app-259373083972538368-3002.ars.teamcode.com/d/0Rjxknc7z/demo-homepage?orgId=1

**Comment by qixiaobo** [comment]
> 

Ok, I will try later.
Thanks for reply

**Comment by Startrekzky** [comment]
> > 
> 
> Ok, I will try later. Thanks for reply

Hi, the Demo site is up running. Please click [here](https://app-259373083972538368-3002.ars.teamcode.com/d/0Rjxknc7z/demo-homepage?orgId=1) to check it out. Username/password: test/test
