### ISSUE TITLE
User reported bug of jenkins

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1199]
## Describe the bug
![cc796f49f3f68e5436fcc4cff1d5b2a](https://user-images.githubusercontent.com/61080/153572351-2e58d3e7-07a0-40cd-b726-908289fc654e.jpg)

Looks like `SaveBuilds` from https://github.com/merico-dev/lake/blob/8af58c0af5e43d361f87c4e3f507c8ad7ab5c9f5/plugins/jenkins/tasks/storage.go#L57 unable to handle empty slice

I suggest we go through this plugin throughly, to prevent this kind of bug altogether, since this is very similar to what user reported last time (build has empty job slice)

## To Reproduce
No sure how to reproduce

## Expected behavior
1. jenkins should be able to handle all kinds of empty slices

**Comment by warren830** [comment]
Plan of attack:

**Comment by Startrekzky** [comment]
Resolved.
