### ISSUE TITLE
extract related commit sha for jenkins build

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1207]
## Description

Looks like jenkins keeps built commit sha, and it can be collected from api
![image](https://user-images.githubusercontent.com/61080/153848330-c5aafa5b-20da-4954-a58f-507b27c0f06c.png)
It's valuable for user to obtain this information for analysis.

## Describe the solution you'd like
Collect this information and convert it to domain layer accordingly

## Has the Feature been Requested Before?
Related to #894

**Comment by warren830** [comment]
Plan of Attack
- [ ] As we can not collect commit sha when collecting builds in batch, we have to add a sub task to enrich builds
- [ ] Create a new sub task to iterate table.jenkins_builds to collect commit sha

problems:
- [ ] Have to enrich every build at every time. 
- [ ] Alternatively, if we want to combine enrich and collect, we have to get all build ids before we request for the specific build.
