### ISSUE TITLE
make 'advanced options' more catchy

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1213]
## Description

The `advanced options` is awesome, and helpful, but it is hard to find.

![image](https://user-images.githubusercontent.com/61080/154233589-e74e7c4c-99ce-4652-8fdb-aa3f7e04131c.png)

I noticed this feature from PR screenshot, so, when I testing out this feature, I was unable to find it on the interface, so I went back PR detail to checkout the screenshots. It is kind of weird to have 'Advanced Options' placed in pipeline name input. 

## Describe the solution you'd like
Move 'Advanced Options' to place 1 or 2 as screenshot indicated.

**Comment by Startrekzky** [comment]
Merged
