### ISSUE TITLE
github events collection performance improvement

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1220]
## Description

Currently, devlake collects github events by iterating all issues and collect events for each indiviual which is extremely slow, and wasting many rate limit.

![image](https://user-images.githubusercontent.com/61080/154427397-acbb96d6-96ef-4d76-bc95-6e58702d0a12.png)

## Describe the solution you'd like

Replace [ List issue events](https://docs.github.com/en/rest/reference/issues#list-issue-events) with [List repository issues](https://docs.github.com/en/rest/reference/issues#list-repository-issues)

By treating events as an independant entity, we dont need to iterate over all issues and fetch events for each one of them,
Instead we fetch events directly, page by page, which reduces the number of api requests big time, meanwhile we can avoid many wasted requests as screenshot showed.

## Has the Feature been Requested Before?
No

**Comment by Startrekzky** [comment]
Merged
