### ISSUE TITLE
github pr commits collection should flush record before fetching not inbetween

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1222]
## Describe the bug
The following code seems like we will keep only the last page of records
![image](https://user-images.githubusercontent.com/61080/154435989-e8f45c9e-a07a-4272-99c5-6b635748a757.png)

## To Reproduce
Spotted by code reading, no existing reproduciable step available.

## Expected behavior
All records from all pages should be saved into database.

**Comment by warren830** [comment]
I should move the code block doing delete to the beginning of the func

**Comment by warren830** [comment]
Can we separate the pagination part. One is for which has a lot of pages, one is for which has even only one page?
