### ISSUE TITLE
`config-ui` supports new configuration settings for github

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1223]
## Description

These newly added settings for github were designed to enrich github issues/PRs data by their labels. they are all Regular Expression
- for GITHUB_PR_TYPE/GITHUB_PR_COMPONENT/GITHUB_ISSUE_SEVERITY/GITHUB_ISSUE_PRIORITY, the first matched group will be extracted and fill into issue/PR as a field
- for GITHUB_ISSUE_TYPE_BUG/GITHUB_ISSUE_TYPE_REQUIREMENT/GITHUB_ISSUE_TYPE_INCIDENT, the  issue with label that mathed respected regex would be set to type BUG/REQUIREMENT/INCIDENT accordingly.  
The reason they got separated into two part is because we had standardize issue type but not others.

these settings can be found on `.env.example` file
![image](https://user-images.githubusercontent.com/61080/154439225-a8fcb0a9-d975-457b-9dce-d5b94b237e33.png)

## Describe the solution you'd like
config-ui to add those settings for github settings, and updte the `README.md` accordingly

## Has the Feature been Requested Before?
No

**Comment by e2corporation** [comment]
Move to `v0.10.0` if not completed at the end of `v0.9.0`

**Comment by e2corporation** [comment]
Non-required fields, should have default values as shown in screenshots.
