### ISSUE TITLE
Improve github performance - pull_request_commits

### ISSUE THREAD

**Issue by warren830** [merico-dev/lake#1230]
## Description
Now, it's very slow to collect pull_request_commits, even it has only several records, but the process makes dozens of requests for empty pages

## Describe the solution you'd like
After discussion with @klesh , we can set the the number of concurrent to 1 when collecting this kind of data

## Has the Feature been Requested Before?
No

## Additional context
We also need to check if the process of collecting comments, events can be improved

**Comment by warren830** [comment]
github pulls: <https://api.github.com/repositories/384111310/pulls?page=1&+per_page+=1>; rel="prev", <https://api.github.com/repositories/384111310/pulls?page=1&+per_page+=1>; rel="last", <https://api.github.com/repositories/384111310/pulls?page=1&+per_page+=1>; rel="first"

github issues: <https://api.github.com/repositories/384111310/issues?page=1&+per_page+=1>; rel="prev", <https://api.github.com/repositories/384111310/issues?page=3&+per_page+=1>; rel="next", <https://api.github.com/repositories/384111310/issues?page=4&+per_page+=1>; rel="last", <https://api.github.com/repositories/384111310/issues?page=1&+per_page+=1>; rel="first"

github events:  <https://api.github.com/repositories/384111310/events?page=1&+per_page+=1>; rel="prev", <https://api.github.com/repositories/384111310/events?page=3&+per_page+=1>; rel="next", <https://api.github.com/repositories/384111310/events?page=10&+per_page+=1>; rel="last", <https://api.github.com/repositories/384111310/events?page=1&+per_page+=1>; rel="first"

github comments: <https://api.github.com/repositories/384111310/comments?page=1&+per_page+=1>; rel="prev", <https://api.github.com/repositories/384111310/comments?page=1&+per_page+=1>; rel="last", <https://api.github.com/repositories/384111310/comments?page=1&+per_page+=1>; rel="first"

github reviews: <https://api.github.com/repositories/384111310/pulls/1224/reviews?page=1&+per_page+=1>; rel="prev", <https://api.github.com/repositories/384111310/pulls/1224/reviews?page=1&+per_page+=1>; rel="last", <https://api.github.com/repositories/384111310/pulls/1224/reviews?page=1&+per_page+=1>; rel="first"

After check, if there is no next page, the link will be empty, otherwise, the link will give us the info above. And we can know how many pages the entity has from 'rel="last"'

**Comment by klesh** [comment]
What @warren830 suggested was that we can extract total page information from response header, sepcifically, the `Link` header
![image](https://user-images.githubusercontent.com/61080/154874719-a339ba81-8598-46c8-be09-00cc1ffea5ee.png)
