### ISSUE TITLE
GitExtractor does not collect dangling commits

### ISSUE THREAD

**Issue by warren830** [merico-dev/lake#1232]
## Describe the bug
GitExtractor does not collect commits which were squashed 

## To Reproduce
1. Use gitextractor to collect commits
2. Find a commit which has been squashed, and look up for it from db
3. It does not exist

## Expected behavior
We should also collect those commits

**Comment by klesh** [comment]
looks like git was designed this way, when cloning from a remote repo, all dangling commits are omitted, even they still exists on remote repo.
Check the following gist for detail
https://gist.github.com/fracz/b4a70b3ec195015cfb6aab5ef8fdb754

**Comment by klesh** [comment]
No viable solution at this point due to the fact these commits are not in the repo that we are collecting.
