### ISSUE TITLE
Github Proxy should be placed in `Configure Connection` section on `config-ui`

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1247]
## Describe the bug
Github Proxy should be placed in `Configure Connection` section, or the `Test Connection` would not be working if devlake could not connect to github directly.
![image](https://user-images.githubusercontent.com/61080/154911440-61a10544-3aef-40f9-ab67-facad43836ae.png)

## Expected behavior
Test connection should be ran via proxy

**Comment by e2corporation** [comment]
Github Proxy field should move to the `Connection Settings` group.
