### ISSUE TITLE
missing proxy support for jira source

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1248]
## Describe the bug
We supported jira proxy in the past, seems like we missed this feature when support multi-data-source feature
I added it back on the backend, please added it to `config-ui`  as well
Remeber this setting is belonged to `Configure Connection`, let me know if any question, thanks

![image](https://user-images.githubusercontent.com/61080/154912897-806735ec-90dc-4fdf-bf40-0c549c4c17bd.png)

**Comment by e2corporation** [comment]
@klesh Proxy field is available on EDIT and not Create screen. Proxy can be specified after a Connection is added.
