### ISSUE TITLE
`RemotelinkCommitShaPattern` setting for jira connection 

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1252]
## Description
Jira issue can have web link, and there is a plugin to add weblink to jira for gitlab
![image](https://user-images.githubusercontent.com/61080/154927208-35fc395f-223a-44e0-88c1-bb7a25a2ba2f.png)

This setting is for user to set up a Regex so we can build up issue/commit relationship in database for them.

![image](https://user-images.githubusercontent.com/61080/154927621-f0765ddf-8e41-4a52-bd29-405053777eb5.png)

## Describe the solution you'd like
Add a text input into jira configuration page to support this setting.

## Has the Feature been Requested Before?
No

**Comment by klesh** [comment]
README also need to be updated

**Comment by e2corporation** [comment]
1 new settings field to JIRA:
- `RemotelinkCommitShaPattern` (`String`) type

**Comment by e2corporation** [comment]
@klesh can you provide a possible/expected example RegExp value for the `RemotelinkCommitShaPattern` ?

**Comment by klesh** [comment]
@e2corporation /commit/([0-9a-f]{40})$
