### ISSUE TITLE
Only show pipeline run duration once

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1266]
## Description
The duration of a pipeline run is duplicated on this page, we can keep one of them.
![image](https://user-images.githubusercontent.com/14050754/155116290-14bc7c7d-6c6a-4174-b980-3c256e962054.png)

**Comment by klesh** [comment]
Top one is for pipeline
The other is for task
Try triggers multiple plugins and you will see it

**Comment by e2corporation** [comment]
@klesh @Startrekzky Klesh is correct, this is not a bug. _Pipeline_ Progress is separate from individual _Task_ progress.

**Comment by Startrekzky** [comment]
> @klesh @Startrekzky Klesh is correct, this is not a bug. _Pipeline_ Progress is separate from individual _Task_ progress.

I see.
