### ISSUE TITLE
The  pipeline job failed with panic after run task to get data from github for my repo

### ISSUE THREAD

**Issue by jennyli-z** [merico-dev/lake#1279]
## Describe the bug
The  pipeline job failed with panic after run task to get data from github for my repo
## To Reproduce
1. Go to 'Create New Pipeline'
2. Fill in my repo 
3. Click run
`$run task failed with panic (github.com/merico-dev/lake/utils.(*WorkerScheduler).WaitUntilFinish:87): [context deadline exceeded (Client.Timeout or context cancellation while reading body)

I have tried twice, one is failed after 3hours, another failed after 26 minutes

## Expected behavior
Should run successfully

## Screenshots
![image](https://user-images.githubusercontent.com/93511422/155644583-8a2d83c5-b21f-414b-9401-46a4f4c4a388.png)
![image](https://user-images.githubusercontent.com/93511422/155644607-5c594c97-03a7-4b3b-b06e-48118fc3b690.png)

## Additional context

Extended Logs
run task failed with panic (github.com/merico-dev/lake/utils.(*WorkerScheduler).WaitUntilFinish:87): [Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=5&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=6&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=10&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=8&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=9&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=12&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=11&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=17&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=13&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=14&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=15&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/milvus-io/milvus/issues/358/events?page=16&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79]

**Comment by jennyli-z** [comment]
the same for merico-dev/lake
```
run task failed with panic (github.com/merico-dev/lake/utils.(*WorkerScheduler).WaitUntilFinish:87): [Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=7&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=8&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=9&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=10&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=11&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=12&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=13&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=50&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=32&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=33&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=42&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=43&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=44&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=31&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=14&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=15&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=16&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=45&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=41&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=17&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=46&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=18&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=47&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=48&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=19&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=49&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=34&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=20&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=35&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=38&per_page=100": context deadline exceeded (Client.Timeout exceeded while awaiting headers) github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=39&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=40&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=27&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=30&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=22&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=29&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=21&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=26&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=37&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79 Get "https://api.github.com/repos/merico-dev/lake/issues/135/comments?page=36&per_page=100": unexpected EOF github.com/panjf2000/ants/v2.(*goWorker).run.func1:71 github.com/merico-dev/lake/utils.(*WorkerScheduler).Submit.func1:79]
```

**Comment by Startrekzky** [comment]
Hi @jennyli-z , please let me know if you still have the bug, perhaps we can arrange a meeting to debug together.

**Comment by jennyli-z** [comment]
> .
I am not sure what kind of github proxy I need to set up , I have already deployed to the cluster have better network to access github.

**Comment by Startrekzky** [comment]
> > .
> > I am not sure what kind of github proxy I need to set up , I have already deployed to the cluster have better network to access github.

I got it, I thought it might be the GFW that blocked GitHub access. Can @klesh help take a look?

**Comment by klesh** [comment]
Hi, Can I have your repo address? and what version were you running?

**Comment by jennyli-z** [comment]
![image](https://user-images.githubusercontent.com/93511422/156114281-53d17d66-9f8c-492f-8b69-6f6c7687cee7.png)

**Comment by jennyli-z** [comment]
> yes, but the whole cluster has the network with vpn to cross GFW already. I have tried to trigger again, and it have been stuck on 50% for 14hours. Is there any way to get the data from specified time instead of the whole time.

![image](https://user-images.githubusercontent.com/93511422/156114331-b201fe92-2d81-4dfe-8926-b52126547801.png)

**Comment by jennyli-z** [comment]
> Hi, Can I have your repo address? and what version were you running?

milvus-io/milvus, v0.8.0

**Comment by jennyli-z** [comment]
I have tried to use merico-dev/lake to have test now, how long to complete for your testing?

**Comment by klesh** [comment]
By default, github plugin will try to collect commits from api, this could be very slow for a big repo.
I suggest you use `triggers` with following json to speed up the process:

```
[
    [
        {
            "plugin":"github",
            "options":{
                "owner":"milvus-io",
                "repo":"milvus",
                "tasks":[
                    "collectRepo",
                    "collectIssues",
                    "collectPullRequests",
                    "enrichIssues",
                    "enrichPullRequests",
                    "convertRepos",
                    "convertIssues",
                    "convertPullRequests"
                ]
            }
        },
        {
            "plugin":"gitextractor",
            "options":{
                "url":"https://github.com/milvus-io/milvus.git",
                "repoId":"github:GithubRepo:208728772"
            }
        }
    ]
]
```

**Comment by jennyli-z** [comment]
> [
>     [
>         {
>             "plugin":"github",
>             "options":{
>                 "owner":"milvus-io",
>                 "repo":"milvus",
>                 "tasks":[
>                     "collectRepo",
>                     "collectIssues",
>                     "collectPullRequests",
>                     "enrichIssues",
>                     "enrichPullRequests",
>                     "convertRepos",
>                     "convertIssues",
>                     "convertPullRequests"
>                 ]
>             }
>         },
>         {
>             "plugin":"gitextractor",
>             "options":{
>                 "url":"https://github.com/milvus-io/milvus.git",
>                 "repoId":"github:GithubRepo:208728772"
>             }
>         }
>     ]
> ]

ok, thanks, I will try.

**Comment by jennyli-z** [comment]
> By default, github plugin will try to collect commits from api, this could be very slow for a big repo. I suggest you use `triggers` with following json to speed up the process:
> 
> ```
> [
>     [
>         {
>             "plugin":"github",
>             "options":{
>                 "owner":"milvus-io",
>                 "repo":"milvus",
>                 "tasks":[
>                     "collectRepo",
>                     "collectIssues",
>                     "collectPullRequests",
>                     "enrichIssues",
>                     "enrichPullRequests",
>                     "convertRepos",
>                     "convertIssues",
>                     "convertPullRequests"
>                 ]
>             }
>         },
>         {
>             "plugin":"gitextractor",
>             "options":{
>                 "url":"https://github.com/milvus-io/milvus.git",
>                 "repoId":"github:GithubRepo:208728772"
>             }
>         }
>     ]
> ]
> ```

It works. the issue can be closed now. Really appreciate it.

**Comment by abeizn** [comment]
> @klesh How could I find a repo ID Over here _{ "plugin":"gitextractor", "options":{ "url":"https://github.com/milvus-io/milvus.git", "repoId":"github:GithubRepo:208728772" }
> 
> I do face similar kind of issue mentioned above what could be the solution over that.

when you run github plugin, you can find it in repos table at database.

**Comment by shubham-cmyk** [comment]
Finding Repo id Could become easier run this query `$("meta[name=octolytics-dimension-repository_id]").getAttribute('content')` in your console.
