### ISSUE TITLE
add repoId to github tool layer

### ISSUE THREAD

**Issue by warren830** [merico-dev/lake#1281]
## Description
If we need to deal with multiple github projects, we should use repoId to distinguish the entities

## Describe the solution you'd like
First, we should fix issue #1060 , and add repo_id to tables: github_issue_labels, github_pull_request_commits, github_pull_request_issues, github_pull_request_labels, github_issue_events, github_issue_comments, github_pull_request_comments

## Has the Feature been Requested Before?
Please link any other

**Comment by klesh** [comment]
we should do that
