### ISSUE TITLE
Backend API does not allow `EMPTY`/Blank GitHub Settings fields

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#1294]
## Describe the bug
The newly added GitHub field settings are optional, and therefore should be allowed empty/null. On testing with both Config-UI and Postman it appears the API does not honor empty values.

In the example below, `GITHUB_ISSUE_TYPE_INCIDENT` is being set to `7` on the first Update. On the subsequent update, `GITHUB_ISSUE_TYPE_INCIDENT` is being set to `EMPTY STRING`. `200/Success` is returned by the API in both cases, but the backend appears to be remembering the previously saved value and not nulling out the field.

This is happening for **all** of the new settings fields.

#### Setting `GITHUB_ISSUE_TYPE_INCIDENT` to `7` succeeds
<img width="965" alt="Screen Shot 2022-03-01 at 10 19 33 AM" src="https://user-images.githubusercontent.com/1742233/156196916-d4429aed-6686-43df-858e-1948987aac80.png">
<img width="959" alt="Screen Shot 2022-03-01 at 10 19 51 AM" src="https://user-images.githubusercontent.com/1742233/156196913-d6a82054-a2c6-490b-a3a8-b418e005b445.png">

#### Attempt to EMPTY `GITHUB_ISSUE_TYPE_INCIDENT` fails.
<img width="957" alt="Screen Shot 2022-03-01 at 10 20 08 AM" src="https://user-images.githubusercontent.com/1742233/156196906-478750c9-90e6-4d7a-b293-357ec3d7f9e0.png">
<img width="958" alt="Screen Shot 2022-03-01 at 10 20 22 AM" src="https://user-images.githubusercontent.com/1742233/156196898-e933580a-5c96-4578-8eb2-255a764caa18.png">

**Comment by e2corporation** [comment]
@klesh Please confirm if this is behavior happening for you as well. Thanks!

**Comment by e2corporation** [comment]
Same behavior for `RemoteLinkCommitSha` (new JIRA Setting)

**Comment by klesh** [comment]
> Same behavior for `RemoteLinkCommitSha` (new JIRA Setting)

I couldn't reproduce this problem.
![image](https://user-images.githubusercontent.com/61080/156304295-15f5548e-23df-49ad-8ff5-c4b78bf9fdca.png)
![image](https://user-images.githubusercontent.com/61080/156304357-eca1f20d-1d58-4a32-9d26-1d033cbf5041.png)

**Comment by klesh** [comment]
As of GITHUB settings, @mappjzc is on it.

**Comment by mappjzc** [comment]
![image](https://user-images.githubusercontent.com/2921251/156322740-6c93f87d-1fa8-421a-bd3e-d78828e65bb4.png)
![image](https://user-images.githubusercontent.com/2921251/156322842-b923a543-2494-4d4d-a1e8-88b84b098dd6.png)
![image](https://user-images.githubusercontent.com/2921251/156323120-3372f02a-2079-49ad-b50e-1133c21cbbe1.png)
