### ISSUE TITLE
Replace api-forwarding from JIRA plugin api with specify APIs

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1312]
## Description
From #1308, we learn that use api-forwarding from config-ui directly was not a very good idea, because we have to support multiple versions of JIRA, let `config-ui` call JIRA api directly would increase frontend complexity in future.

## Describe the solution you'd like
1. Remove api-forwardling feature from JIRA plugin api
2. Add `issuetype` api to JIRA plugin api
3. Add `field` api to JIRA plugin api
4. config-ui calls `issuetype` / `field` apis instead of `proxy` api
5. No more proxy in future 

## Has the Feature been Requested Before?
No

**Comment by warren830** [comment]
not a big problem, no need to fix, will be closed for now.
