### ISSUE TITLE
plugin decoupling (link pr to this issue)

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1363]
## Description
Plugin subtasks are having global value dependency, like `lakeModels.Db`, as well as logger, that make Temporal support impossible.
They must be removed

## Related Pull  Requests

- #1318 
- #1321 
- #1324 
- #1325 
- #1327 
- #1328 
- #1329 
- #1330 
- #1331 
- #1332 
- #1333 
- #1335
- #1336 
- #1337 
- #1338 
- #1339 
- #1340 
- #1341 
- #1342 
- #1343 
- #1344 
- #1345 
- #1346 
- #1347 
- #1348 
- #1350 
- #1351 
- #1352 
- #1353 
- #1354 
- #1355 
- #1356 
- #1357 
- #1361 
- #1362 
- #1364
- #1359

## Has the Feature been Requested Before?
Please link any other

**Comment by warren830** [comment]
already finished in milestone v0.10.0
