### ISSUE TITLE
Default datasource is uneditable

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#138]
Should we consider the fact that user might change database password afterward, if so, this is problematic.
![image](https://user-images.githubusercontent.com/61080/128315053-79e29f38-8c5d-4b16-97d5-fe4040ea4b14.png)

**Comment by joncodo** [comment]
I think this is ok since they can add a new datasource to the grafana tool. Then they can switch the graphs to the new data source. 

Otherwise, they can edit the config file and restart the app?

Maybe we need a doc for how to do this?

**Comment by klesh** [comment]
Yup, I was updating the dashboards today and the work was tedious. We have dozen charts one our first stage, and more on the future, all charts need to updated independantly, so I modified the json file by replacing at the end.
I think it's preferable to support datasource modification, if it's not viable, we could use doc as last resort.
