### ISSUE TITLE
Prompt users to set multiple tokens for GitHub configuration

### ISSUE THREAD

**Issue by tanninghan** [merico-dev/lake#1385]
## Description
Due to GitHub API rate limit, it will take a lot of time to run data collection if only one token is configured.
![image](https://user-images.githubusercontent.com/102040651/159972988-0727c403-10e1-4e4b-ab33-b14b9d00a6e7.png)

## Describe the solution you'd like
Prompt users to set multiple tokens and tell them how to get these tokens.

## Design of the solution
Show an `Add Token` button and perhaps 5 input boxes on the `GitHub Add Connection` page, so that users can provide multiple tokens at once to speed up data collection.

**Comment by tanninghan** [comment]
Prototypes of GitHub configuration
![GitHub Add Connection](https://user-images.githubusercontent.com/102040651/160452934-cc979c60-f993-4654-990d-e9e7a3bc670c.jpg)
![Manage Github Settings](https://user-images.githubusercontent.com/102040651/160452938-3ad4321a-03cd-486c-b278-750f8e098610.jpg)

**Comment by tanninghan** [comment]
Prototype of GitHub configuration
![GitHub configuration](https://user-images.githubusercontent.com/102040651/160614521-99029c5b-9bd5-4957-a3b5-ac307acac4c1.jpg)
![Manage Github Settings](https://user-images.githubusercontent.com/102040651/160614528-fd7e7baf-0341-49a7-a5e2-41ef0ea33286.jpg)

**Comment by e2corporation** [comment]
@Startrekzky Moving this ticket for enhancing multi-token input to `v0.10.0`
