### ISSUE TITLE
Details on `Data Integration` page that can be improved

### ISSUE THREAD

**Issue by tanninghan** [merico-dev/lake#1386]
## Description
![image](https://user-images.githubusercontent.com/102040651/159975562-508e7c2f-d4f1-480a-b708-7da41b509404.png)
1. Error positioning is not intuitive. 
2. Placeholders are too long and increase users' reading burden. 
3. The length of `Connection Name` input box may mislead users that a long, complex answer is required here. 

## Design of the solution
1. Place the error message under the relevant input box. 
2. The help text in a input box only needs "eg: ..." 
3. Shorten the input box of `Connection Name`.

**Comment by e2corporation** [comment]
This a Product/Marketing Copy need - please provide copy replacements for the place holders @Startrekzky @tanninghan

**Comment by tanninghan** [comment]
For reference
![GitHub configuration](https://user-images.githubusercontent.com/102040651/160614947-ab0e9e80-5015-44be-9de9-fa5c326d378c.jpg)
![Manage Github Settings](https://user-images.githubusercontent.com/102040651/160614951-e1fbee10-0d29-4547-a84f-faebfa7fe793.jpg)

**Comment by klesh** [comment]
@tanninghan aah... the file size of references are too big, it took me 5 minutes to finally loaded them up...
![image](https://user-images.githubusercontent.com/61080/160984745-f1705071-f610-4ff0-9b2b-8c52554a77af.png)

**Comment by tanninghan** [comment]
@klesh Aha my fault... I've replaced them with smaller ones
