### ISSUE TITLE
A few design details of config-ui that can be improved

### ISSUE THREAD

**Issue by tanninghan** [merico-dev/lake#1387]
## Description
Different names for the same function cause confusion, e.g. `Create New Pipeline` and `Create Run`. 
![image](https://user-images.githubusercontent.com/102040651/159976464-817a234b-f2c7-4fd1-9776-c48fa7be9f53.png)

## Design of the solution
Unify the names to `Create Pipeline Run` to avoid confusion.

**Comment by e2corporation** [comment]
Please provide Breadcrumb Copy and Menu Title for "Create New Pipeline". Create Run and Create Pipeline Run are used interchangeably because pipeline is too lengthy.

**Comment by klesh** [comment]
fxied via #1436
