### ISSUE TITLE
Solve the issues of new users not knowing how to use config-ui

### ISSUE THREAD

**Issue by tanninghan** [merico-dev/lake#1388]
## Description
1. New users have to rely entirely on README to use config-ui and cannot get timely and accurate help when obstacles are encountered.
2. There is a lack of connection between `Data Integration`, `Pipeline` and `Dashboard` sections. New users who are unfamiliar with the entire flow and functions may feel confused about what to do next. For example, there is no tip on what should be done after a connection is saved.

## Describe the solution you'd like
1. Provide help/guide in the config-ui pages, so that users don't need to jump to other external links.
2. Always tell users what to do next after an action is done. A good example is that the `View Dashboards` button can navigate users to dashboards.
![image](https://user-images.githubusercontent.com/102040651/159977704-826f8c41-6819-4786-9e57-4636dcc07745.png)

## Design of the solution
1. Provide more proactive help/guide. On the right side of the page there can be a `Help panel` that people can display or hide. The content in the Help panel updates with contextually relevant help text when a person clicks one of the `Help icons` next to each input box.
2. When an action is completed, provide the user with a link/button to the next step or show the relevant page directly. The homepage can present an introduction consisting of brief descriptions and illustrations of the entire flow (an example as follows).
![image](https://user-images.githubusercontent.com/102040651/159977793-3648606d-ed92-4673-a630-2fe3f8bcc963.png)

**Comment by warren830** [comment]
will be handled in new design

**Comment by warren830** [comment]
will be handled in new design
