### ISSUE TITLE
Optimize config-ui `Pipelines` page

### ISSUE THREAD

**Issue by tanninghan** [merico-dev/lake#1389]
## Description
1. The page of `Run New Pipeline` is long, so users cannot know at a glance what they need to do. 
2. The input box of `Pipeline Name` looks complicated. 
![image](https://user-images.githubusercontent.com/102040651/159978579-9739fdd2-dbbc-40bf-9e1b-2fe99c54f76b.png)
3. The position of `Advanced Mode` button makes it not intuitive enough.  
![image](https://user-images.githubusercontent.com/102040651/159978523-d5ce0d5e-8aec-479b-8569-e2b128db4714.png)

## Describe the solution you'd like
Users can know at a glance what they need to do on a screen without having to scroll down more.

## Design of the solution
1. Shorten the space for `Data Providers` section and get the `Run Pipeline` button seen asap. 
2. Simplify the `Pipeline Name` format by moving some content out of the input box. 
3. Move the `Advanced Mode` button to the beginning of `Data Providers` section.

**Comment by warren830** [comment]
will be handled in new design
