### ISSUE TITLE
v0.9.0 github settings - field saving issues 

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#1393]
QA / Feedback Issues Hotfix reported by @klesh 

- [x]  when click on Save Connection. all the other settings are gone after page refresh. I think we have to send other settings along with connection settings as a temporary fix for now.
- [x] github settings page, once a value was set into Incident, it can never be removed, the old value kept coming back after page refresh.
- [x] Connection Save should also send `Settings` Payload (otherwise BE will empty fields)

**Comment by e2corporation** [comment]
Target `v9` **Hotfix** branch `release-v0.9`

**Comment by klesh** [comment]
fixed via #1395
