### ISSUE TITLE
Cannot save Jira connection in v0.9.1

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1396]
## Describe the bug

Cannot save Jira connection even test connection works in v0.9.1

## To Reproduce

<img width="1190" alt="Screen Shot 2022-03-26 at 8 45 26 AM" src="https://user-images.githubusercontent.com/2908155/160247781-bcabf7ff-edda-46eb-9ab9-fd90236e36d9.png">

Simply follow the user setup guide and change config-ui version to v0.9.1 in `docker-compose.yml` and run `docker-compose up -d`.

In the screenshot, I used invalid connection info. But even if I use valid data and the test connection passes, I still get the same error message.

## Expected behavior

To be able to save connection info successfully

**Comment by Startrekzky** [comment]
Verified. The estimated result of `save connection` is to "go back to the connection list page" no matter the configuration is right or wrong, and the error message should not be shown.
