### ISSUE TITLE
terms for pipeline execution and recurring pipeline

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1415]
## Question

please pick you favourite terms to represent historical pipeline execution / reccuring pipeline by emoji reaction:

1. 👍 pipeline run + pipeline plan
2. 😄 pipeline + blueprint
3. ❤️ pipeline run + pipeline blueprint

**Comment by Startrekzky** [comment]
I prefer `task` + `pipeline`, please +1 if you like this option.

**Comment by klesh** [comment]
@e2corporation seems like `blueprint` is winning LOL

**Comment by klesh** [comment]
ok, no objection, lets go with pipeline+blueprint @warren830
