### ISSUE TITLE
task list/detail should have `progressDetail` field

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1423]
## Description

Currently, we have out task list/detail output as following
![image](https://user-images.githubusercontent.com/61080/160741488-2011efd9-0d12-4dcb-ae92-9c6068f0f7a2.png)

Accordling to latest change, we can provide `progressDetail` as follow
```
{
    "count":1,
    "tasks":[
        {
            "ID":22,
            "CreatedAt":"2022-03-30T02:51:34.355Z",
            "UpdatedAt":"2022-03-30T02:51:34.395Z",
            "plugin":"refdiff",
            "options":{ ... },
            "status":"TASK_RUNNING",
            "message":"",
            "progress":0.1,
            "failedSubTask":"",
            "pipelineId":12,
            "pipelineRow":1,
            "pipelineCol":1,
            "beganAt":"2022-03-30T02:51:34.371Z",
            "finishedAt":null,
            "spentSeconds":0,
            "progressDetail": {
                "totalSubTasks": 9,
                "finishedSubTasks": 0,
                "totalRecords": -1,
                "finishedRecords": 1234,
                "subTaskName": "collectIssues",
                "subTaskNumber": 1
            }
        }
    ]
}
```

## Describe the solution you'd like
1. Update `services/task.go` to output `progressDetail` for list/detail api, `progressDetail` is available IFF `task.status == RUNNING`, and can be obtain from `runningTasks` variable.
2. config-ui to utilize this information on interface for user to have a better sense that devlake is running correctly in background, not hanged @e2corporation 

## Has the Feature been Requested Before?
No

**Comment by klesh** [comment]
@e2corporation the back api had been updated via #1425 , please take a look and update config-ui accordingly

**Comment by mappjzc** [comment]
Merged
