### ISSUE TITLE
Commits that don't belong to a PR appeared in the `pull_request_commits` table

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1426]
## Describe the bug
`pull_request_commits` records are incorrect. This [pr](https://github.com/tikv/tikv/pull/8940/commits) has only 10 commits, but there're more than 10 records with `pr.id = 'github:GithubPullRequest:514445706'` in the table.

## To Reproduce
1. Go to 'triggers' page in the config-ui
2. run 
`[
    [
        {
            "plugin":"github",
            "options":{
                "owner":"tikv",
                "repo":"tikv",
                "tasks":[
                    "collectPullRequestCommits",
                    "convertPullRequestCommits"
                ]
            }
        }
    ]
]`
3. Click on Trigger collection

## Expected behavior
table.Pull request commits has the right number and pair of records after collection is finished.

**Comment by klesh** [comment]
![image](https://user-images.githubusercontent.com/61080/160826363-5303621c-09a2-4fc3-8d49-66cdd6d2db7a.png)

**Comment by klesh** [comment]
I think the converter logic is incorrect:
https://github.com/merico-dev/lake/blob/v0.9.1/plugins/github/tasks/github_pull_request_commit_convertor.go
line 40 should be using `githubPullRequestCommit.PullRequestId` for domain id generation instead of `pullRequestId`

**Comment by klesh** [comment]
fixed
