### ISSUE TITLE
table.pull_requests lacks column `author_id` and `author_name`

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1428]
## Describe the bug
table.pull_requests lacks `author_id` and `author_name` according to the schema in #700.

## Screenshots
![UBX7q6TrqR](https://user-images.githubusercontent.com/14050754/160870069-34914b04-9a2b-4f96-8b3e-8a79f5c011d1.png)

**Comment by klesh** [comment]
fixed
