### ISSUE TITLE
Allow Grafana Dashboards to reference local icons

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#143]
Our current Grafana homepage uses a few web icons: https://z3.ax1x.com/2021/08/04/fAClNV.png
Considering that these icons may not work, it‘s better to reference local icons. I will upload the icon files later.
The same applies to other visual materials that may be used in the future, such as images, etc.

**Comment by UltimateBeaver** [comment]
@Startrekzky Hi Louis, anything we need to do for this issue?

**Comment by klesh** [comment]
Resolved by #186
