### ISSUE TITLE
[Vote] Initial committers for incubation at Apache Software Foundation

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1451]
## Background 
DevLake is going to be donated to Apache Software Foundation. Initial committers are required before transferring the project. Considering the past contribution and long-term willingness to engage in the project, we nominated several initial committers:

- @klesh
- @e2corporation 
- @mindlesscloud 
- @warren830 
- @joncodo 
- @hezyin 
- @MaximDub 

We nominate the initial committers mainly according to their code contributions measured by [this paper](https://per.pub/A1Pd7xaM.pdf). Below are the original top five code contributors in the past six months.

![image](https://user-images.githubusercontent.com/14050754/162191393-fa566fcf-a74e-4196-baab-2cbaf821278c.png)

We added Hezheng to the list because he is responsible for everything technical, and Maxim because he is responsible for user interviews and has made a lot of non-technical contributions.

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

**Comment by basicthinker** [comment]
+1

**Comment by joncodo** [comment]
I agree! 👍

**Comment by yumengwang03** [comment]
+1 yay~

**Comment by abeizn** [comment]
+1

**Comment by liangjingyang** [comment]
+1

**Comment by Startrekzky** [comment]
Agree

**Comment by e2corporation** [comment]
+1

**Comment by warren830** [comment]
+1

**Comment by klesh** [comment]
+1

**Comment by warren830** [comment]
already finished
