### ISSUE TITLE
User being able to select repo from a dropdown list instead of typing manually

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1465]
## Description
Currently, user have to somehow compose `repo_id` manually or copy it from database for `git extractor` plugin on `config-ui` which is quite cumbersome.

We found this missing piece is quite critical for v0.10, since it would make new user experience more smoother. So, we shall finish this one before code freeze(Mon 11th April)

## Describe the solution you'd like
It would be much easier for user to be able select `repo_id` from a dropdown list like we did for jira epic key, sth like type to search.

- [x] Backend provide an api to list out all repos from database, liek `GET /domainlayer/repos` @klesh #1469 
- [x] Frontend adopt the api and provide some type-to-search dropdown list feature for `gitextractor` `repo_id` field @e2corporation 

## Has the Feature been Requested Before?
No

## Describe alternatives you've considered
1. Let users query `repo_id` directly from database after github/gitlab collection
2. Teach users understand how DomainLayerId works, and they go to find out github repository id from somewhere and build the DomainLayerId on their own.

**Comment by e2corporation** [comment]
@klesh @Startrekzky I think this ticket can be closed? Please confirm if there are outstanding issues to resolve. Thanks!

**Comment by Startrekzky** [comment]
Relolved
