### ISSUE TITLE
dbt plugin is not supported in config-ui's advanced mode

### ISSUE THREAD

**Issue by abeizn** [merico-dev/lake#1484]
## Description
dbt plugin is not supported in config-ui's advanced mode.

![image](https://user-images.githubusercontent.com/101256042/164405082-4e21850e-5d7f-4136-8320-44e4b17dde5e.png)

**Comment by e2corporation** [comment]
@abeizn @Startrekzky Is "dbt" and "ae" the same plugin? The Ticket requests "dbt" support, but the screen mock has "ae". Do both need to be supported?

**Comment by abeizn** [comment]
@e2corporation sorry，the screen is wrong, "dbt" and "ae" is not same. The Ticket only requests "dbt" support in v0.11.0. The latest screenshot is correct. 
![image](https://user-images.githubusercontent.com/101256042/165410918-29df0b5e-04c6-4c9f-b3ad-4b0e76785921.png)

**Comment by abeizn** [comment]
@e2corporation Even better, if “dbt” and "ae" are already supported.
