### ISSUE TITLE
[Feat][ts] db migrate should load from plugins

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#150]
data schema defined in plugins
database initial and migrate should load from plugins.

**Comment by likyh** [comment]
# How plugin work? Just like this

## state and callback flow
```mermaid
graph TD;
    A[write your plugin]--copy files to plugins-->B[start]
    B --run app--> C[unregistered]
    C --"triforce call register()"--> D[unmigrated]
    D --"call unregister()"--> C
    D --"call migrateUp() when added or updated"--> V0[ready]
    V0 --"call migrateDown() when removed"--> D
```
<img width="593" alt="截屏2021-08-10 上午12 04 56" src="https://user-images.githubusercontent.com/3294100/128737698-dc0d7de9-098c-4df8-9ab4-38b3694a8678.png">


## picture generate by mermaid

view on github: `https://github.com/BackMarket/github-mermaid-extension`

or view online: `https://mermaid-js.github.io/mermaid-live-editor`

**Comment by joncodo** [comment]
@likyh I assume you are working on this. Please assign it to someone else if I am wrong. Assigning you for now.

**Comment by joncodo** [comment]
I think this code was merged. Feel free to re-open this issue if needeed @likyh
