### ISSUE TITLE
Nil pointer error after "context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

### ISSUE THREAD

**Issue by warren830** [merico-dev/lake#1506]
## Describe the bug
If we failed to request from remote server, the system reported nil pointer error.
This happened because the handler would be called twice if retry of api request occurred. 
When the handler is called at the second time, the res is still nil and the err is also nil.

## How to fix
We directly return the result of retry.

## Screenshots
<img width="877" alt="image" src="https://user-images.githubusercontent.com/39366025/163310018-44b89273-90ce-4859-b936-4762b6d5b79a.png">

**Comment by warren830** [comment]
This bug seems like an internal bug of gitlab itself

**Comment by klesh** [comment]
@warren830 do not post private repo information directly here

**Comment by warren830** [comment]
> @warren830 do not post private repo information directly here

Sorry, will delete it

**Comment by warren830** [comment]
relate to #1501
