### ISSUE TITLE
[ts] Plugin configuration management

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#151]
## Description
With our plugin system, there are configurations to each plugin, we should provide a easy-use way to set configuration for plugins. The configuration system should meet following requirements:  
- **Dynamically** update the configuration.
- Support multiple sets of configurations.

## Describe the solution you'd like
We will create the configurations through restful api. for example
```
POST  /sources
{
    type: 'Jira', // plugin name
    options: {
        host: '',
        username: '',
        password: 'password or api token'
    } // plugin configurations
}

response:
{ source: 'source id' }
```

## Context
The configuration system is based on our plugin system design, related to #244

**Comment by narrowizard** [comment]
We have some more work to do before adding the source api. 
## My plans
- [ ] adding class validator for request validation. #194 
- [ ] adding database layer and schema definition. 
- [ ] add source api (CRUD)
- [ ] add unit test and e2e test for source api
- [ ] add error handler for rest api

**Comment by joncodo** [comment]
So for this one, I have a few questions:

1. Does the data get fetched automatically on a loop for all sources in the DB?
2. Does this support many gitlab projects and many jira projects at once?
3. When the job to fetch data is created, do we create a parent job and many child jobs to be processed by bull? How does that part work?

Thanks in advance for the info 👍

**Comment by narrowizard** [comment]
> Does the data get fetched automatically on a loop for all sources in the DB?

There's no plan to implement the synchronize logic in lake, data fetch task for each source will be added by task api(#152 ). Maybe we can create a cron job to trigger the task api schedually.
> Does this support many gitlab projects and many jira projects at once?

Yes

**Comment by joncodo** [comment]
@hezyin would like us to change the name 'source' to 'plugin'

**Comment by narrowizard** [comment]
Close this because #242 is merged.  
> would like us to change the name 'source' to 'plugin'

Open another issue as a proposal for this, thank u : )
