### ISSUE TITLE
[Feat][ts] queued task should be managed 

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#154]
## Why

Plugins is a sequence of tasks are executed in the queue service. Plugins should define the task workflow and send it to the queue service. So how we describe the workflow should be abstract. Make the task focus on the collect or the enrich.

## How

we may need to add some abstract class to help defined the workflow. some thing like
```
Task([Collector/Issue, Collector/Changelog]).next([Enricher/Issue]).schedule();
```
Or maybe more complex
```
Map(Collector/IssueList).Next(['Collector/Issue', 'Collector/Changelog']).Next([Enricher/Issues]).schedule();
```
And we would save the scheduled task and workflow info into database/redis then add Job into queue by the workflow. after jobs done then get the next workflow to add job into queue.

how to send the job events: https://github.com/merico-dev/lake/pull/172

**Comment by joncodo** [comment]
@jaxzhou  I assume you are working on this. Please assign it to someone else if I am wrong. Assigning you for now.

**Comment by joncodo** [comment]
Since the PR was closed and this ticket is very abstract, I will close this. Feel free to re-open it if we are still doing this @jaxzhou
