### ISSUE TITLE
Turning on GitHub's "update pull request branch" feature

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1540]
Hi everyone,

Manually rebasing branches to maintain a linear git history has proven to be a burden for our developers. GitLab provides a rebase button on the PR page which really helps with the process. And today I found the corresponding feature on GitHub and turned it on. 

From now on, on each PR page, you'll see an "Update branch" button when your PR branch is not on top of the base branch and can be automatically rebased on top of the base branch (no conflict with the base branch). There're two options for updating your PR branch and please select the 2nd option "Update with rebase", as shown in the screenshot below. If you don't want to wait for the CI to finish again, you can select "Merge when pipeline succeeds" afterward.

![image](https://user-images.githubusercontent.com/2908155/163077697-e50976ab-6280-4d14-98d3-9ee09dd1000d.png)

References:

1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch
2. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

**Comment by abeizn** [comment]
Great!!!
