### ISSUE TITLE
Update domain layer schema document to v0.10.0

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1561]
## Documentation Scope
- [x] update this domain layer schema [doc](https://merico.feishu.cn/docs/doccnvyuG9YpVc6lvmWkmmbZtUc) 
- [x] convert the lark doc to a MD file and push it to the doc site.

## Why
With this doc,
- users can understand the algorithm of metrics in pre-built dashboards
- users can do custom analysis based on the domain layer schema
- contributors can understand the standard output when adding a new data source plugin

**Comment by klesh** [comment]
@yumengwang03 had finished the second task
