### ISSUE TITLE
Summary of docker platform issues

### ISSUE THREAD

**Issue by abeizn** [merico-dev/lake#1572]
## Description
docker platfrom parameter is confused on mac and windows，example: #465 #707 #966 and #1549
.so we need to summarize.

## Describe the solution you'd like
finding a solution which can adapt different os, it should be a doc summary or code solution。

**Comment by Startrekzky** [comment]
Need a plan of attack.

**Comment by abeizn** [comment]
Summary of docker platform issues:
1.  docker version should be upgrated to 19.03+ at least (better latest version)
2. docker-compose should be upgraded to v2.2.X + at least (better latest version)
3. if you use apple(M1) and don't have libraries for amd64, you can likely use the amd64 image by adding the **--platform=linux/amd64** flag on docker.
