### ISSUE TITLE
Cannot login demo grafana

### ISSUE THREAD

**Issue by dkhwangbo** [merico-dev/lake#1580]
## Describe the bug

Cannot login demo grafana with test/test ([README described](https://github.com/merico-dev/lake/blob/main/README.md?plain=1#L24))

## To Reproduce
1. Go to 'https://app-259373083972538368-3002.ars.teamcode.com/login'
2. Login with test/test

## Expected behavior
Login success

## Screenshots
<img width="829" alt="image" src="https://user-images.githubusercontent.com/13585249/163338280-4e5a582c-b45a-4c83-bb46-f84616834765.png">

**Comment by klesh** [comment]
Sorry for you inconvenience, seems like someone changed the password.
We had already reset the account, please try again.

**Comment by dkhwangbo** [comment]
@klesh Thanks. Login successed
