### ISSUE TITLE
The feishu official api data is incorrect

### ISSUE THREAD

**Issue by abeizn** [merico-dev/lake#1605]
## Describe the bug
https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/report/get_top_user
The results of Feishu's official API do not match the actual results。Awaiting official feedback。
meeting_duration in seconds should be minutes.

**Comment by abeizn** [comment]
update:
![image](https://user-images.githubusercontent.com/101256042/165067845-bd4a6058-b5a0-4e48-aa4b-93fde1cbe3d3.png)

**Comment by abeizn** [comment]
![image](https://user-images.githubusercontent.com/101256042/165072963-dce9d827-fa32-4b34-a67c-8ee75a41bb0f.png)

**Comment by abeizn** [comment]
![image](https://user-images.githubusercontent.com/101256042/165074916-bf901ed7-f17f-44a0-8227-fb9074345494.png)

**Comment by klesh** [comment]
The unit from document was off, should be `minutes`, not `seconds`
