### ISSUE TITLE
Config UI - Jira Add Connection Input Warning

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake#1606]
## Describe the bug
When adding a connection for Jira, the input fields are highlighted with warning, which can be misleading because the user hasn't entered anything.

## To Reproduce
1. Go to 'Data Integrations'
2. Click on 'Jira'
3. Click on 'Add Connection'

## Expected behavior
Text input fields should not be shown with warning.

## Screenshots
<img width="1315" alt="Screen Shot 2022-04-15 at 3 23 25 PM" src="https://user-images.githubusercontent.com/9535430/163538984-c5613b37-23c1-4510-a6b1-851fc543051d.png">

**Comment by e2corporation** [comment]
@yumengwang03 @Startrekzky This is not a bug, the product/design team previously requested that errors be moved closer to the form inputs. This is standard inline form validation that lets the user know that required fields are needed.
