### ISSUE TITLE
Config-ui: save connection failed in Github connection page

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1613]
## Describe the bug
Save connection failed
Version: v0.10.0

## To Reproduce
1. Go to config-ui, click 'Github' 
2. Click on the default connection in the list
![image](https://user-images.githubusercontent.com/14050754/163546774-99edbf2d-1bbe-41d3-8fd8-517f83793328.png)

3. Enter valid endpoint and url, click 'Save Connection'. It'll show a success message.
![image](https://user-images.githubusercontent.com/14050754/163546992-17d0f25c-b42d-4ddc-9731-a20a08ad4a84.png)
![image](https://user-images.githubusercontent.com/14050754/163547198-883a30c2-cb71-496c-b60b-554889ee2b5f.png)

4. Scroll down to the bottom of the page, click 'Save Settings'. It'll show a success message.
5. Go back to the connection list, see connection 'status'. It's still disconnected.

## Expected behavior
The connection is successfully created after this process, as it's a common user journey to configure GitHub connection.

**Comment by e2corporation** [comment]
@klesh GitHub provider is working as expected on my local `main` branch, if the auth token is bad then it would lead to a bad connection test. Also why was the status message changed in the code from 'offline' to 'disconnected' ?
