### ISSUE TITLE
Config UI - Managing Jira Settings: Epic Key and Story Point Field are Disabled

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake#1614]
## Describe the bug
After adding a Jira connection, in Manage Jira Settings, the Epic Key and Story Point Field are disabled.

## To Reproduce
1. Go to 'Data Integrations'
2. Click on 'Jira'
3. Add a Jira connection
4. Go to Settings
5. Scroll down to Epic Key and Story Point Field

## Expected behavior
The user should be able to select from these two fields.

## Screenshots
<img width="797" alt="Screen Shot 2022-04-15 at 4 57 09 PM" src="https://user-images.githubusercontent.com/9535430/163550023-8a152397-96f8-4371-8ade-e65147f94966.png">

**Comment by klesh** [comment]
addressed #1539
