### ISSUE TITLE
Config UI - Create Blueprint Naming Confusion

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake#1616]
## Describe the bug
Either creating a Blueprint from the Pipeline Blueprint page or the Create Pipeline Run page, the default name shows "Daily Blueprint". Clicking on Hourly, Weekly, Monthly or Custom still shows "Daily Blueprint".

## To Reproduce
1. Go to 'Pipeline Blueprints'
2. Click on 'Create Blueprint'
3. Clicking on radio buttons to select the frequency.

## Expected behavior
The name should correspond to the selected frequency.

## Screenshots
<img width="547" alt="Screen Shot 2022-04-15 at 5 59 55 PM" src="https://user-images.githubusercontent.com/9535430/163558252-b7cfccb0-867f-4708-a4b5-c8e0e0d39410.png">
<img width="535" alt="Screen Shot 2022-04-15 at 6 00 28 PM" src="https://user-images.githubusercontent.com/9535430/163558269-eef9a9bf-efdf-4f01-9680-8aa8d1ea9f96.png">

**Comment by e2corporation** [comment]
I can make this change, however this is a user controlled field, It's expected that the user defines a proper name, regardless of what frequency is selected. "Daily Blueprint" is just a default value.

**Comment by e2corporation** [comment]
@Startrekzky @klesh @yumengwang03 Team consensus is that we will set the default name value to "MY BLUEPRINT"
