### ISSUE TITLE
Config UI - Wrong Example for RefDiff Input Fields (in both regular and advanced mode)

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake#1628]
## Describe the bug
The example for RefDiff input fields are incorrect in both regular and advanced mode(JSON).

## To Reproduce
1. Go to 'Create Pipeline Run'
2. Turn on the RefDiff toggle
3. When filling in the input, the suggested examples are wrong (see screenshots).

## Expected behavior
There should not be a letter "v" before 0.6.0.

## Screenshots
<img width="634" alt="Screen Shot 2022-04-15 at 8 49 30 PM" src="https://user-images.githubusercontent.com/9535430/163572715-104acb28-bf6d-4fa3-9944-11bedaba17d8.png">
<img width="746" alt="Screen Shot 2022-04-15 at 8 49 56 PM" src="https://user-images.githubusercontent.com/9535430/163572797-ef48e2e0-af12-4ef7-950f-55cbe7f0e36a.png">

**Comment by e2corporation** [comment]
@klesh @Startrekzky No action being taken at this time for the `RefDiff` sample config code, as tags and semantics may be arbitrary depending on project, we will have to discuss sane default values to use on next iteration.

**Comment by warren830** [comment]
closed for now
