### ISSUE TITLE
Why do I need to set 'x-token' in request headers?

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#163]
```
app.post('/', async (req, res) => {
  if (config.token && req.headers['x-token'] !== config.token) {
    return res.status(401).json({ message: 'UNAUTHORIZED' })
  }
```

This means that users have to set the value but where does this token come from and why are we checking for it?

@UltimateBeaver

**Comment by joncodo** [comment]
<img width="804" alt="Screen Shot 2021-08-09 at 10 22 08 AM" src="https://user-images.githubusercontent.com/3011407/128713043-87a47fb9-8301-4fc1-b0ef-acc007b764c1.png">

**Comment by UltimateBeaver** [comment]
Already resolved.
