### ISSUE TITLE
GitLab plugin collects commits on all branches instead of just on main

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1660]
## Description

The GitLab plugin only collects commits on the main branch right now, can you modify its behavior to collect commits on all branches? This would give the plugin user more comprehensive info about their coding activities.

**Comment by Startrekzky** [comment]
According to design, commits data will not be collected by the GitLab plugin but GitExtractor. We just have to improve the workflow based on the design of #1725 to make this data collection experience more user-friendly. So I'll close this issue for now.
