### ISSUE TITLE
Support Jira data center version

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1687]
## Description
Investigate into the api version of Jira data center to make sure the existing Jira plugin supports Jira data center, such as v8.18.0, v8.18.1.

## Describe the solution you'd like

- [ ] If there's a clear doc that shows Jira data center and Jira server are using the same set of API, then a doc url is acceptable
- [ ] If not, please set up an instance of Jira data center to test out.

## Has the Feature been Requested Before?
#886

**Comment by mindlesscloud** [comment]
Devlake supports the Jira data center as well as the server version.
issues:
![image](https://user-images.githubusercontent.com/8455907/164369532-d3c6b78f-c8a9-49e0-8115-340a9a6a7a00.png)
changelogs:
![image](https://user-images.githubusercontent.com/8455907/164369973-66332f42-a1cf-4a43-ab16-b09e678530b9.png)
sprint_issues:
![image](https://user-images.githubusercontent.com/8455907/164370113-5d284379-e228-441c-a67d-56741db2bc8d.png)
_tool_jira_changelog_items:
![image](https://user-images.githubusercontent.com/8455907/164370421-5b4cc6dc-4f3b-48ed-8bf7-27b028797dd9.png)
