### ISSUE TITLE
GitExtractor: support private repo

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1704]
## Description
What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

## Describe the solution you'd like
for `HTTP` or `HTTPS`, by providing a username and access token in the URL, gitextractor can access the private repos.
> https://username:token@host/path/to/repo.git

for the `ssh` protocol, It could be achieved by setting the private key and passphrase in the `options`
```json
{
    "name": "git repo extractor",
    "tasks": [
        [
            {
                "Plugin": "gitextractor",
                "Options": {
                    "url": "https://github.com/merico-dev/lake.git",
                    "repoId": "github:GithubRepo:384111310",
                    "privateKey": <your private key>,
                    "passphrase": <passphrase for the private key>
                }
            }
        ]
    ]
}
```

## Has the Feature been Requested Before?
Please link any other

**Comment by mindlesscloud** [comment]
Already supported. For `Gitlab`, `Github`, `Bitbucket`, by providing `username` and `access token` in the URL,  `gitextractor` can access the private repos.
```
git clone https://username:token@host/path/to/repo.git
```

**Comment by klesh** [comment]
Please fill out detail @Startrekzky
