### ISSUE TITLE
Need document for jira issue type configuration.

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#171]
Seems configed in [config/constants.json](https://github.com/merico-dev/lake/blob/main/config/constants.json), but never mentioned in [readme](https://github.com/merico-dev/lake/blob/main/README.md) or [jira plugin doc](https://github.com/merico-dev/lake/blob/main/src/plugins/jira-pond/README.md).  
/cc @UltimateBeaver

**Comment by UltimateBeaver** [comment]
this is resolved by @klesh latest PR.
