### ISSUE TITLE
Add the version number to the config-UI

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1747]
## Why
It helps:
- when users are reporting a bug and trying to provide version info.
- when users have deployed multiple instances and try to figure out the version of them.

## Describe the solution you'd like
- Add the version number to config-UI. Users can see the version number no matter what pages they are visiting.
- The value should be up-to-date. Is there a way to not forget to update version No. before a release.

**Comment by klesh** [comment]
Backend part is ready

**Comment by tanninghan** [comment]
@e2corporation Prototype is ready, with the name issue#1747  https://www.figma.com/file/qpUZN3dJqnOcXxPZs36wTj/Config-UI-update?node-id=65%3A1433
