### ISSUE TITLE
Convert GitHub's pr and issue comments to the domain layer

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1758]
## Describe the solution you'd like
- [x] Convert Github PR comments to the domain layer's [pull_request_comments](https://www.devlake.io/docs/DevLakeDomainLayerSchema)
- [x] Convert Github issue comments to the domain layer's [issue_comments](https://www.devlake.io/docs/DevLakeDomainLayerSchema)

## Belongs to
#1746

**Comment by abeizn** [comment]
![image](https://user-images.githubusercontent.com/101256042/167335737-47d29288-47d1-4707-8a30-ba0a69955efe.png)
![image](https://user-images.githubusercontent.com/101256042/167335763-34c4d7a7-b796-44b9-a666-c490ea27ee1c.png)
![image](https://user-images.githubusercontent.com/101256042/167335882-75bab774-5e20-4fc7-9fc5-bf9b388cf16e.png)

test and verity: 1821(raw) = 1296(issue) + 525(pr)

issue_comments:
![image](https://user-images.githubusercontent.com/101256042/167335941-e2891211-a549-442c-8673-a980dfd4abdf.png)

pull_request_comments:
![image](https://user-images.githubusercontent.com/101256042/167335983-936d1769-0331-493d-a0d4-023ffaa5bfc4.png)
