### ISSUE TITLE
Add `icon` for table `issues`

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1774]
## Description
When we list issues, an icon is useful for users to check type and source of the issue. eg: It is a bug from jira.  
We Suggest adding an `icon` column for `issues` entity, using original type icon of this issue.

## Additional context
![image](https://user-images.githubusercontent.com/11383928/165747126-26219ef9-857e-4b76-9eec-bb16feece164.png)  
Or  
![image](https://user-images.githubusercontent.com/11383928/165747198-d7344b7c-c6aa-4c82-bcba-0ee74a8824c0.png)

**Comment by leglars** [comment]
Issue icons have too many human factor, user can customize each issue type's icon by themselves. It is hard to give a normalized icon set to cover different issue types across all issue tracking apps. And it's also unnecessary to do this normalization. 
Meanwhile, icon can give user a quick visual clue to identity the type of issues.
Therefore, the easiest way to achieve this benefit is to fetch issues' icon url directly and provided by domain schema.
