### ISSUE TITLE
Jira data collection failed v0.10.1

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1801]
## Describe the bug

I tried to collect Jira data using v0.10.1 but encountered an error.

## To Reproduce

1. Use DevLake version v0.10.1
2. Set up our own Jira instance
3. Try to collect board 53 and see the following error message

<img width="2278" alt="Screen Shot 2022-05-05 at 11 09 55 PM" src="https://user-images.githubusercontent.com/2908155/167076742-54941b34-9530-4dd1-a59c-9ae96faeb3fb.png">

**Comment by klesh** [comment]
Use `tasks` option when creating pipeline with following subtasks to avoid Sprint Collection:
```
		"collectProjects",
		"extractProjects",
		"collectBoard",
		"extractBoard",
		"collectIssues",
		"extractIssues",
		"collectChangelogs",
		"extractChangelogs",
		"collectWorklogs",
		"extractWorklogs",
		"collectRemotelinks",
		"extractRemotelinks",
		"convertBoard",
		"convertIssues",
		"convertWorklogs",
		"convertChangelogs",
		"convertIssueCommits",
		"convertIssueRepoCommits",
		"ConvertUsers"
```

**Comment by warren830** [comment]
close for now, will be reopen when get feedback
