### ISSUE TITLE
Jira data collection stuck v0.10.1

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1820]
## Describe the bug

I tried to collect Jira data using v0.10.1 but the pipeline got stuck at 31.58% for 2 hours (still running).

## To Reproduce

1. Use DevLake version v0.10.1
2. Set up our own Jira instance
3. Try to collect board 53 using advanced mode with the following JSON 

```
[
  [
    {
      "Plugin": "jira",
      "Options": {
        "sourceId": 1,
        "boardId": 53,
        "since": "2006-01-02T15:04:05Z",
        "tasks": [
                "collectProjects",
		"extractProjects",
		"collectBoard",
		"extractBoard",
		"collectIssues",
		"extractIssues",
		"collectChangelogs",
		"extractChangelogs",
		"collectWorklogs",
		"extractWorklogs",
		"collectRemotelinks",
		"extractRemotelinks",
		"convertBoard",
		"convertIssues",
		"convertWorklogs",
		"convertChangelogs",
		"convertIssueCommits",
		"convertIssueRepoCommits",
		"ConvertUsers"
           ]
      }
    }
  ]
]
```

4. Observe that the pipeline gets to 31.58% rather quickly (15 mins):

<img width="2274" alt="Screen Shot 2022-05-08 at 9 56 05 PM" src="https://user-images.githubusercontent.com/2908155/167350838-23c03317-e55a-4df2-9320-ed2c37aa522e.png">

Here's the DevLake service log:

<img width="849" alt="Screen Shot 2022-05-08 at 10 14 51 PM" src="https://user-images.githubusercontent.com/2908155/167350958-e79ce33e-3c56-4ac8-8744-b40ec1fe1c00.png">

5. But 2 hours later, it's still at 31.58%:

<img width="2276" alt="Screen Shot 2022-05-08 at 11 11 12 PM" src="https://user-images.githubusercontent.com/2908155/167350899-ab107133-df61-46d8-a992-3c8253a152e4.png">

The DevLake service log remains the same as 2 hours ago:

<img width="849" alt="Screen Shot 2022-05-08 at 10 14 51 PM" src="https://user-images.githubusercontent.com/2908155/167351024-986bafe6-8a32-4d1d-b347-766dc2f9603c.png">

## What's the expected behavior?

The pipeline finishes without getting stuck and collects the specified Jira data.

**Comment by abeizn** [comment]
DevLake service log is Incorrect, it is a gitlab plugin not a jira plugin, and the time is 2022-04-21  which seems not right.

**Comment by abeizn** [comment]
The amount of board 53 data is so large that the subtask collectChangelogs is too slow. The collectChangelogs subtask took six hours。
![image](https://user-images.githubusercontent.com/101256042/167407299-107a85e4-7585-4fb6-8a99-64fb669c705c.png)

**Comment by hezyin** [comment]
Ok, thank for looking into this for me @abeizn , closing now since it's just slow and not a bug.
