### ISSUE TITLE
Demo account  in README-zh-CN.md is WRONG

### ISSUE THREAD

**Issue by xgdyp** [merico-dev/lake#1825]
When logging in with the test account in README-zh-CN.md, the website shows "Invalid username or password".

I found the link in readme.md is not the same as the one in zh-CN.md. Is it possible to change the link in README-zh-CN.md?

<img width="971" alt="image" src="https://user-images.githubusercontent.com/37795442/167431880-b14a40df-dab2-44b7-a6d0-8a40712f6e8e.png">

**Comment by klesh** [comment]
Thanks for reporting, will update it soon
