### ISSUE TITLE
jira can not save connection

### ISSUE THREAD

**Issue by abeizn** [merico-dev/lake#1827]
## Describe the bug
jira can not save connection.

## Screenshots
![image](https://user-images.githubusercontent.com/39366025/167448047-f6b8a11b-3cc2-4983-97c9-5feec258ef25.png)

**Comment by warren830** [comment]
please pull the newest version, just checked, it's alright
<img width="740" alt="image" src="https://user-images.githubusercontent.com/39366025/167447541-87deec2d-91bc-4361-ab57-88e7aa5ae07b.png">

**Comment by abeizn** [comment]
it is the newest version, sometimes normal and sometimes abnormal
