### ISSUE TITLE
plugins in typescript branch

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#184]
## Plugin

plugin would be the entry. it should be executable or it should return a executable task.  [#154 Task Queue Should Be managed](https://github.com/merico-dev/lake/issues/154)

directly execute
```
class Jira implements Plugin { 
     async execute(options) {
           const {collector, enricher} = options;
           for (const col of collectors) {
                await Collectors[col].execute();
           }
           for (const enr of enricher) {
                await Enrichers[enr].execute();
           }
     }
}
```

scheduled task
```
class Jira implements Plugin { 
     async execute(options): Promise<Task> {
           const {collector, enricher} = options;
           cont task = new Task();
           task.next(collectors.map(col => Collectors[col]));
           task.next(enricher.map(enr => Enrichers[enr]));
           return task;
     }
}
```

## Collector And Enricher

collector and enricher should be the components which do the real job. the jobs should be called from the pulgin or scheduled by the plugin.

### collector

collector fetch data from server. we may not need all the fields from the server api. so defined the fields we saved is important. also that would be easy to use by enricher.
So may we need entity and collector together
```
\\ collector\Issue.entity.ts
@Entity()
class Issue {
}
\\ collector\Issue.ts
@Injectable()
class IssueCollector {

}
```

### enricher

enricher process datas saved by the collector. after enriched, we may save all fields that collector fetched, or we would only save part of fields collector fetched and with some extended fields calculated by enricher.
So there should be another entity defined by enricher
```
\\ enricher\Issue.entity.ts
import JiraIssue from '../collector/issue.entity.ts';
@Entity()
class Issue extends JiraIssue {
}
\\ enricher\Issue.ts
@Injectable()
class IssueEnricher {

}
```

**Comment by klesh** [comment]
I thought we were going to have a tool-layer that is close to data-source original sturcture (say JiraIssue in this case)?
and then converted to standard type (say Issue).
If that was the case, I don't really understand the pseudo-code here, I'd like more input about last part "Collector And Enricher"
