### ISSUE TITLE
Updated the Jira dashboard and un-archive it

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1856]
## Describe the bug
Updated the archived Jira dashboard according to the up-to-date domain layer schema.

## Found in Version
[tag v0.11.0-test3](https://github.com/merico-dev/lake/releases/tag/v0.11.0-test3)

## To Reproduce
1. Add a Jira connection
2. Import Jira data

## Actual behavior
There's no Jira dashboard to see.

## Expected behavior
The Jira data is properly displayed in the Jira dashboard.

**Comment by mindlesscloud** [comment]
fixed by #1857
