### ISSUE TITLE
New issues and pull request labelling

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#188]
## WHY
We need to setup some labels & structure to our issues (and pull requests). The issues are starting to pile up, so this will help organize them. We want something simple (not too cumbersome for newcomers), but structured. 

Also one of the most important labels needed is `in progress`, combined with using the **Assignees** feature. This prevents a few issues, especially doing work already being worked on.

## WHAT
- New labels setup with only the most necessary ones we need right now
- Added labels to existing open issues, testing out this setup
- No milestones/projects right now, but this can be something we factor in later (mvp, v2, typescript version etc)

![Screen Shot 2021-08-11 at 3 16 35 PM](https://user-images.githubusercontent.com/3789273/129089580-6ac02870-122d-4758-931f-5a998eb2ef30.png)

## DISCUSSION
Any proposed changes, ideas etc comment in this issue and we can discuss modifying it. Then agree on a finalized version and close this issue.

**Comment by klesh** [comment]
👍 nice

**Comment by oddscenes** [comment]
Additional label added by @joncodo is `feedback requested`

**Comment by joncodo** [comment]
Looks like this was accepted. Closing
