### ISSUE TITLE
GitLab Plugin

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#189]
This is a proposal to implement the GitLab Plugin in the TypeScript version of Lake.

## Why

Now that we have some fundamental infrastructure laid out in the ts-main branch, we need to further the goal of replicating our functionality from the JS MVP in the TS version of Lake. 

## What

Building an actual working Plugin with collection and enrichment functionality that can be triggered via API request is the next step. 

# How

- We will need a POST request listener for API calls to our service
- We need our service to add jobs to our task queue
- We will need tasks to call our plugin methods (collect data from GitLab API, enrich data from our DB)
- We will need a data schema for storing data from GitLab
- We will need migration scripts to run on our DB within the plugin 
- We will need to hook up Grafana to our data source and present metrics based on data collected

Please add comments to this proposal if I am missing something! 

If this proposal is approved, the NA team will begin work on it as soon as we are available.

Thanks.

**Comment by klesh** [comment]
Maybe we can trigger next step by  pushing a new job onto the queue directly?
API may exist but for another reason, like external accessing, i.e. trigger manually.
For internal logic, we can skip the API request overhead.

**Comment by kevin-kline** [comment]
> Maybe we can trigger next step by pushing a new job onto the queue directly?
> API may exist but for another reason, like external accessing, i.e. trigger manually.
> For internal logic, we can skip the API request overhead.

Thanks for the feedback. I think this is a good suggestion!

**Comment by joncodo** [comment]
@UltimateBeaver assigning to you for approval. How are issues approved? Are you adding an approval label? Please let me know and I will update the contribution guide

**Comment by joncodo** [comment]
This is blocked until we have a framework that we can leverage. Unless you think there are any tasks we can get started with @kevin-kline
