### ISSUE TITLE
[feat][ts] we need a logger in ts-main

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake#192]
https://docs.nestjs.com/techniques/logger

**Comment by joncodo** [comment]
Feel free to re-open with more details on why we need this and what you are proposing.

**Comment by narrowizard** [comment]
nestjs providers a built-in log module, I've added some example at #265(for controllers, services and providers). Seems the buit-in log is enough for us now, do you have any other ideas? @likyh

**Comment by likyh** [comment]
> nestjs providers a built-in log module, I've added some example at #265(for controllers, services and providers). Seems the buit-in log is enough for us now, do you have any other ideas? @likyh

No more idea about this. Just want a example for how to log some message

**Comment by narrowizard** [comment]
close due to language switch
