### ISSUE TITLE
WIP: Application review with Maxim

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#200]
Notes:

MAXIM call about reviewing usage

- [x] Missed the discord link
- [x] Easy to set up via docker * provide link
- [ ] Add section for : Dev lake leverages, docker, grafana. All third party words as links to their homepages
- [x] Requirements title should be changed to “Required packages to install”
- [x] “Data source” plugins to “Data sources we currently support”
- [x] We need a preview at the top for what the final thing looks like
- [ ] We need a video screencast
- [ ] Dummy proof installation of docker and node.js
- [x] #212

**Comment by kevin-kline** [comment]
> * Easy to set up via docker * provide link

Going through the motions, I found this to interrupt the flow by taking me into the overwhelming world of docker too early. 

There are 2 cases:

1. Person knows docker -> no action needed
2. Person doesn't know docker -> We hold their hand as much as possible by giving them specific commands so they don't need to know too much about docker to get it going.

That's my proposal. Let's just give them minimal info to get going.

**Comment by joncodo** [comment]
This has been completed and the feedback was really helpful
