### ISSUE TITLE
[feat] Grafana default homepage configuration

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#206]
### Why
There're scenarios that our MVP users may not import both Jira and Gitlab data.
As a result, a lot of charts will be look like this:
<div align="left">
<img src=https://user-images.githubusercontent.com/14050754/129307193-66681608-432d-43ec-84a6-863043c5cc47.png width=30%>
</div>

### Solution
The reason is that our charts are grouped by cognitive domain(efficiency/quality/cost) and practice domain(requirment/development/test/operation) on our current dashboards. See [current design](http://13.212.147.78:43002/d/RXJZNpMnz/homepage?orgId=1)

Therefore, I designed another set of dashboards, charts on which are grouped by data sources (Jira/Gitlab) and analyzed objects (requirement/bug/incident/...). See [new design](http://13.212.147.78:43002/d/QxI1iCM7k/homepage_grouping_by_data_source?orgId=1)

### Action
A logic needs to be added to determine which set of dashboards should be displayed to the user by default based on the configuration of the user's data source.

We can do it in the next phase.

**Comment by joncodo** [comment]
So for this, we can use the new command line interface. If the user sets up jira only, we can modify the grafana.json file and set the default dashboard to the Jira dashboard or we can hide the other dashboards.

I think this will be needed anyway with many data sources and many graphs. Some users will only want Gitlab data and not even use Jira.

**Comment by Startrekzky** [comment]
> So for this, we can use the new command line interface. If the user sets up jira only, we can modify the grafana.json file and set the default dashboard to the Jira dashboard or we can hide the other dashboards.
> 
> I think this will be needed anyway with many data sources and many graphs. Some users will only want Gitlab data and not even use Jira.
> 
> Does a Jira only dashboard exist now? And a Gitlab only one?

Hi @joncodo The Jira-only and Gitlab-only dashboards have been designed, I'll put up a PR later. This feature is planned to be implemented in phase 2 (Sep. 15). We'll prioritize the open issues(feats/bugs) until most of the phase 2 requirements come out next week.

**Comment by Startrekzky** [comment]
Duplicate with #408
