### ISSUE TITLE
Set config files with user terminal prompt system

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#212]
Maxim was unable to configure the plugins on his own. This leads me to believe this is too confusing of a task for new developers to lake. 

I have since updated the plugin readmes to be more informative but we may also need further simplification. https://github.com/merico-dev/lake/pull/211/files

## IDEAS
    - [ ] Maybe npm start should prompt you with messages to tell you what to do. Then we save the user's responses in their config file for them?
    - [ ] Interactive command line interface to set the config files with the right parameters

## Added features
    - [ ] encode base64 on the Jira Token, and remove this requirement from the user

**Comment by joncodo** [comment]
I think we should do something like this:

https://www.codecademy.com/articles/getting-user-input-in-node-js

When the user runs `npm start`, we show them the following prompts:

```
const prompt = require('prompt-sync')({sigint: true});
 
let enableJira = prompt('Would you like to enable jira?');
writeJiraConfig(enableJira)

let enableGitlab = prompt('Would you like to enable gitlab?');
writeGitlabConfig(enableGitlab) 

let gitlabRepoUrl = prompt('What is the url of your gitlab repo?');
let projectId = extractIdFromGitlabUrl(gitlabRepoUrl)
writeGitlabConfig(projectId)

let token = prompt('Now you need to git your gitlab token so we can save it in your config files. Please see these steps: https://github.com/merico-dev/lake/tree/main/src/plugins/gitlab-pond#create-a-gitlab-api-token?');
// an example of how we could sanitize this data
let validToken = validateTokenWithTestApiCall(token)
validToken ? writeGitlabConfig(token) : prompt('Your token was invalid. Please try again')

}
```

**Comment by oddscenes** [comment]
- Programmaticly base64 encoding jira token
- Troubleshooting API key validity with a test call
- Step-by-step flow easier setup for user

I like this approach

**Comment by joncodo** [comment]
This could even call oauth to make the user sign into gitlab in a browser and then save their tokens to config

**Comment by kevin-kline** [comment]
I believe this is a HUGE Usability upgrade that needs to happen

**Comment by klesh** [comment]
Cool

**Comment by joncodo** [comment]
Fixed
