### ISSUE TITLE
For our docs, should we make all link target _blank

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#215]
## WHY

It seems that there are so many links in our docs and clicking them takes the user away from the main context. 

## WHAT 

Change all links like this:

`[docs/DEVELOPER_SETUP.md](docs/DEVELOPER_SETUP.md)`

to

`<a href="https://docs.docker.com/get-docker" target="_blank">Docker</a>`

**Comment by hezyin** [comment]
Either is fine imo, if someone takes the effort to make a PR, I'll accept it.

**Comment by joncodo** [comment]
@kevin-kline wanted this issue. I think is a good thing to add and for him to work on :)

**Comment by kevin-kline** [comment]
> @kevin-kline wanted this issue. I think is a good thing to add and for him to work on :)

it appears that even with target=_blank, the links do not open in a new tab.
