### ISSUE TITLE
Make README more user friendly, and less dependent on domain knowledge

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#216]
Here is a suggestion for substitution our current "User Setup" section:

> ## User Setup<a id="user-setup"></a>
> 
> **NOTE: If you only plan to run the product, this is the only section you should need**
> 
> 1. Clone this repository<br>
> 
>    ```shell
>    git clone https://github.com/merico-dev/lake.git
>    cd lake
>    ```
> 2. Create a copy of the sample configuration files with
> 
>    ```
>    cp config/docker.sample.js config/docker.js
>    cp config/plugins.sample.js config/plugins.js
>    ```
> 
> 

3. Get tokens for the data sources you want to pull from 

## Data Sources we Currently Support:

....insert data source chart....

For example, if you want to get an API token from GitLab, follow these directions:

[gitlab](https://github.com/merico-dev/lake/blob/main-readme-update/src/plugins/gitlab-pond/README.md#create-a-gitlab-api-token)

4. Open your favourite IDE to start editing files

5. Find the plugin config file that we just created (config/plugins.js)

6. Replace the "token" fields with the tokens you created in step 3 

NOTE: For more info on plugin configuration, please see: [data-source](#data-source-plugins)

> 4. Start the service with `npm start`
>     > you can stop all docker containers with `npm run stop`
> 
> 5. Run `docker-compose logs -f lake` to check the logs and see when lake stops collecting your data. This can take up to 20 minutes for large projects. (gitlab 10k+ commits or jira 5k+ issues)
> 
> 6. Navigate to Grafana Dashboard `https://localhost:3002` (Username: `admin`, password: `admin`)

**Comment by kevin-kline** [comment]
This is needed unless we change to a programmatic configuration prompt system:

#212

**Comment by joncodo** [comment]
We ended up doing programatic configuration with `npm run configure`. Since we are doing this, this ticket is no longer needed. Feel free to re-open it. :)
