### ISSUE TITLE
Add  token validation to CLI

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#239]
**Is your feature request related to a problem? Please describe.**

The potential for problems exists when a User using the CLI to configure the application inputs an incorrect auth token for Jira or GitLab (or any other plugin) where the application will not work, and it may not be clear why.

**Describe the solution you'd like**

We should check that the tokens are valid before allowing the user to proceed with configuration.

**Describe alternatives you've considered**

I don't know of any alternatives, but I am open to them.

**Additional context**

**Comment by kevin-kline** [comment]
Here is another thought: Do we want create access tokens programmatically? Looks like we can if we have their user name. But we need start a "rails console".  

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token-programmatically

Thoughts?

**Comment by joncodo** [comment]
There is no need for token validation if we just allow the user to log in with the browser. 

1. Open up the right url to show the browser the third party login: https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url

2. Use passport js to grab the token and write it to the config files.

**Comment by joncodo** [comment]
You can also get all their project ids etc and allow them to choose what they want. If this gets much larger, we can always use a webpage to configure the application

**Comment by kevin-kline** [comment]
> There is no need for token validation if we just allow the user to log in with the browser.
> 
> 1. Open up the right url to show the browser the third party login: https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url
> 2. Use passport js to grab the token and write it to the config files.

Ok, thanks for the direction on this.

**Comment by kevin-kline** [comment]
> There is no need for token validation if we just allow the user to log in with the browser.
> 
> 1. Open up the right url to show the browser the third party login: https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url
> 2. Use passport js to grab the token and write it to the config files.

If anyone knows any more details on how to do this, that would be helpful.
