### ISSUE TITLE
[feat] dependency resolver

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#245]
## Description
We have entities and tasks in plugin. all the task doing is transform data from one or more entities into another entity.
So we Use Entity as the interface to connect tasks. the resolver would receive the output entities and find the producer tasks. the producer tasks would required other entities that also with producers. then go through all the required entities to create a DAG describe the workflow.

## Additional context
#184 
#244

**Comment by kevin-kline** [comment]
What is a DAG?

**Comment by jaxzhou** [comment]
DAG:Directed acyclic graph
our task dependency graph would be a DAG. so we could know the startup tasks and what tasks could execute concurrency
