### ISSUE TITLE
[feat] 819 Plugin entities migration

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#247]
## Description
According to proposal 1, we are now all agree that Plugin could have entities, and it should be able to migrate its own entities.

## Describe the solution you'd like
A plugin could have a `migrations` folder contains all its database migration scripts. Our framework is responsible for applying those scripts.

## Has the Feature been Requested Before?
No

**Comment by likyh** [comment]
https://github.com/merico-dev/lake/pull/253

**Comment by klesh** [comment]
closed due to language switching.
