### ISSUE TITLE
[feat] 819 Plugin installation / development

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#248]
## Description
According to proposal 1, we are now all agree that plugin is a folder under `plugins` for the moment.

## Describe the solution you'd like
Plugin developer should clone our repo and create an subfoder under `plugins` for his plugin. Plugin could import stuff from Framework, but not the other way around, that is, Framework should not import anything from a specific plugin directly.

## Has the Feature been Requested Before?
No

## Describe alternatives you've considered
Could we leverage `npm`  for our Plugin Installation? Feel free to share your thought.

**Comment by likyh** [comment]
https://github.com/merico-dev/lake/pull/243

**Comment by klesh** [comment]
closed due to language switching.
