### ISSUE TITLE
[CI] Pipeline settings

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#254]
## Description
Do you have any questions about our github actions pipeline? I'll list our current checks, please comment if you have any ideas.

### current checks for PR
- coverage rate should be more than base branch's coverage rate (node 14.x)
- coverage rate for added lines should more than base branch's coverage rate (node 14.x)
- unit test (node version 12.x, 14.x, 15.x)
- e2e test (node version 12.x, 14.x, 15.x)
- commit message lint
- eslint (also prettier)

**Comment by narrowizard** [comment]
## suggestion for @jaxzhou 
- target our main node version to 12.x
- remove other node version for e2e test (only keep 12.x)
- move coverage calculation to node version 12.x
- setup coverage rate limitation to a fixed value.

**Comment by hezyin** [comment]
@narrowizard I'm on the same page with @jaxzhou's suggestion.

**Comment by narrowizard** [comment]
closed by #264
