### ISSUE TITLE
Break down "Requirement Lead Time" by development stages

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#256]
## Description
Phase 2 Metric:  Requirement Lead Time
Requirement lead time should be broken down into 5 stages of development process (requirement analysis, design, development, test, build and deploy), so users could find out the bottleneck of a requirement delivery process by observing in which status the requirement stays for the most time.

## Describe the solution you'd like

- [ ] Get Jira changelog and calculate issue staying time in each issue status
- [ ] Let users configure the mapping between Jira issue status and 5 development stages

## Has the Feature been Requested Before?
#141 

## Nice to Have
Requirement Lead Time can also be broken down into the user's original issue status(to_do, in-progress, under_review, resolved), which means users can also query the tool-layer schema for analysis and visualization.

**Comment by hezyin** [comment]
@Startrekzky Is this issue done? Can we close it?

**Comment by klesh** [comment]
feature got cancelled
