### ISSUE TITLE
Add a metric "Pull Request Review Rounds"

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#257]
## Description
Task: Add a metric "Pull Request Review Rounds" (Phase 2 Metric)

This metric reflects:
1. the quality of code submitted by developers, with fewer review rounds representing a higher one-off pass rate, i.e. higher quality code
2. the cost of code reviews, effectively reducing the number of code review rounds and reducing the cost of wasted manual reviews

Definition of this metric: The number of code review rounds

## Describe the solution you'd like

- [ ] Find out the method to calculate review rounds based on Gitlab data we can get @klesh 
- [ ] Collect and enrich data to analysis-ready 

## One Possible Calculation Method (logically)
Get the timeline of all time that we can get from a MR, such as "MR submission time", "Comment time", "Commit creation time", "Commit update time", etc.
If the timeline looks like:
- 18 Aug 16:00 :  MR submission (including Commit_1, Commit_2, Commit_3)
- 18 Aug 17:00 :  User A comment_1
- 18 Aug 17:05 :  User A comment_2
- 18 Aug 18:00 :  User B comment_3
- 18 Aug 19:00 :  A new commit "Commit_4" is added to this MR
- 18 Aug 19:05 :  A new commit "Commit_5" is added to this MR
- 19 Aug 09:00 :  User A comment_4
- 19 Aug 09:05 :  User A comment_5
- 19 Aug 09:10 :  User B comment_6
- 19 Aug 19:00 :  A new commit "Commit_6" is added to this MR
- 20 Aug 10:00 :  MR merged

Then PR/MR review round will be 3, because there're 2 rounds of commit change which indicate 2 round of review, and the merge action implies another review.

This calculation method is just a suggestion. The final method depends on the workflow and the data we can get from Gitlab.

**Comment by joncodo** [comment]
What happens when you merge your own pull request? Is that a review round?

IE: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/342

What happens if you comment on your own merge request? Do we ignore those since you are your own reviewer?

IE: Paul's first comment here: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/424

**Comment by Startrekzky** [comment]
1. What happens when you merge your own pull request? Is that a review round?
I think 



> What happens when you merge your own pull request? Is that a review round?
> 
> IE: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/342
> 
> What happens if you comment on your own merge request? Do we ignore those since you are your own reviewer?
> 
> IE: Paul's first comment here: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/424



> What happens when you merge your own pull request? Is that a review round?
> 
> IE: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/342
> 
> What happens if you comment on your own merge request? Do we ignore those since you are your own reviewer?
> 
> IE: Paul's first comment here: https://gitlab.com/merico-dev/ce/ce-backend/-/merge_requests/424

**Comment by Startrekzky** [comment]
1. What happens when you merge your own pull request? Is that a review round?
I'm not sure, to be honest. Both make sense to me. What's your idea?

2. What happens if you comment on your own merge request? Do we ignore those since you are your own reviewer?
Yes, we ignore it.

**Comment by klesh** [comment]
vdev PR 2539 currently has 0 review_rounds, but I can see some comment and respond between @liyh and @leric.

**Comment by joncodo** [comment]
> 2539

I am looking into this now

**Comment by hezyin** [comment]
@joncodo when you finishes tasks at hand, could you please take a look at this again?

**Comment by joncodo** [comment]
For gitlab, when we hit the rate limit, it returns "Rate limit exceeded" but only about 6 times. After that, all requests look like 200 requests but return no data. This is giving us a false positive for 98% of requests working.

**Comment by joncodo** [comment]
Done and merged
