### ISSUE TITLE
Add a metric "Requirement Granularity"

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#258]
## Description
Task: Add a metric "Requirement Granularity" (Phase 2 Metric)

Theoretically, the smaller the granularity of requirements the better, as smaller requirements are easier to understand, estimate and design. Although too small a granularity of requirements may lead to rework due to incomplete consideration.
This metric can be seen as an important indicator of important metrics such as "requirement lead time" and "delivered requirement count".

Definition of this metric: The workload of the requirement

## Describe the solution you'd like

- [x] get the story point or estimated time of Jira issue
- [x] allow users to configure the way(story point/estimated time/...) to measures workload.

## Describe alternatives you've considered
If users use "estimated time" and Jira API gives us data like '2d', '1w', we should also get the conversion rules (1 week = 5 or 6 days, 1 day = 6 or 8 hours) to calculate the actual estimated time in minute.

**Comment by hezyin** [comment]
This is implemented in Dev Lake phase 2.
