### ISSUE TITLE
Add metrics "Build Count" and "Build Success Rate"

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#259]
## Description
Task: Add metrics "Build Count" and "Build Success Rate" (Phase 2 Metric)

These metrics help users quickly locate problems with your build while visualizing how your project is building.

Metric Definitions:
- Build Count: The number of builds created
- Build Success Rate: The percentage of successful builds

## Describe the solution you'd like

- [x] Collect Jenkins data
- [x] Jenkins-related configuration

## Why Jenkins?
- largest market share
- our EE team is using it so we got data

**Comment by Startrekzky** [comment]
test Lark webhook

**Comment by Startrekzky** [comment]
test Lark webhook2

**Comment by Startrekzky** [comment]
test Lark webhook2

**Comment by Startrekzky** [comment]
test Lark webhook3

**Comment by Startrekzky** [comment]
test Lark webhook4

**Comment by hezyin** [comment]
This is implemented in Dev lake phase 2
