### ISSUE TITLE
Lint our new Golang code 

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#272]
## Description
We need a way to have the same lint for all developers. Something like what we have in this guide: https://freshman.tech/linting-golang/

## Describe the solution you'd like
I want us all to have the same code formatting and catch small errors that we can.

- [x] Run go lint with every run of CI/CD

## Has the Feature been Requested Before?
We used to have it in lake JS and lake TS

## Describe alternatives you've considered
The Go compiler does a few things but we need better formatting

**Comment by klesh** [comment]
LGTM

**Comment by kevin-kline** [comment]
It is not recommended to install from source (using go get): https://golangci-lint.run/usage/install/#install-from-source

Therefore, I will go forward with using a GitHub Action to trigger golangci-lint, and recommend we all install locally according to our OS: https://golangci-lint.run/usage/install/#local-installation

**Comment by joncodo** [comment]
done
