### ISSUE TITLE
Database ORM (gorm)

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#275]
## Description
We need models to store data in our mysql database

## Describe the solution you'd like
I would like us to add the following tables
- [ ] Jira issue (With lead time)
- [ ] Source -> Renamed `Plugin`
- [ ] SourceTask -> Renamed `Task`
- [ ] Base Model class - https://github.com/merico-dev/lake/blob/ts-main/apps/rest/src/models/base.ts

We can use `gorm` for this as we already have it.

Here is an example: https://github.com/merico-dev/lake/blob/go-main/api/models/source.go

**Comment by klesh** [comment]
I'm looking a way to define models within plugin, any input is welcome

**Comment by hezyin** [comment]
Outdated.
