### ISSUE TITLE
Copy all Readmes from the main js branch to go-main

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#278]
## Documentation Scope

We put a lot of time into these docs and we need to rework them all once the MVP is done in go.

Having said that, we should try to update the docs as we go as well.

### Docs to migrate
- [ ] https://github.com/merico-dev/lake/blob/main/README.md
- [ ] https://github.com/merico-dev/lake/blob/main/CONTRIBUTING.md
- [ ] https://github.com/merico-dev/lake/blob/main/db/README.md
- [ ] https://github.com/merico-dev/lake/blob/main/src/plugins/HOW-TO-ADD-METRICS.md
- [ ] https://github.com/merico-dev/lake/blob/main/src/plugins/README.md
- [ ] https://github.com/merico-dev/lake/blob/main/src/plugins/jira-pond/README.md
- [ ] https://github.com/merico-dev/lake/blob/main/docs/GRAFANA.md
- [ ] https://github.com/merico-dev/lake/blob/main/docs/DEVELOPER_SETUP.md

**Comment by klesh** [comment]
LGTM
I think we can do all except for plugins, the plugin system for Go would be different, I'm working on that currently, maybe leave that part tp me and go for others.

**Comment by hezyin** [comment]
Done
