### ISSUE TITLE
Change db auto migrations to individual migrations

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#287]
## Description
Auto migrations on database may fail for a number of reasons and then we wouldn't be able to handle these failures as effectively. If we built the migrations individually and set them up without using auto migrations it would be a more robust solution. 

## Describe the solution you'd like
In `/api/services/init.go` we should modify the following function to not use AutoMigrate:
```go
func migrateDB() {
  db.AutoMigrate(&models.Source{})
  // TODO: create customer migration here
}
```

## Has the Feature been Requested Before?
no

**Comment by hezyin** [comment]
Closing for now.
