### ISSUE TITLE
Dev Lake Phase 2 Plan - week 2 [8/30-9/03] Migrate MVP plugins and add Jenkins

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#308]
# WHY
Last week, we had successfully finished the foundation for all of us to work on. Thanks all for your contribution and collaboration, kudos to all!! 
@Startrekzky is going to hold a Demo for new Charts next Tuesday, our goal is to provide a working grafana dashboard before that.
The new Charts will need some missing data from MVP which described in [Triforce Missing Attributes for Phase 2 Metrics - Feishu Docs](https://merico.feishu.cn/docs/doccnxIoIgmUbhX1aUWS4haTvkg)

# HOW
In order to achieve the goal, the following tasks are to be done:
To @joncodo : all NA tasks are assigned to you, pls help making arrangement

1. Migrate Jira plugin and add missing data @klesh @likyh
2. Implement Jenkins @narrowizard @jaxzhou
3. Migrate Gitlab plugin and add missing data @joncodo
4. Migrate grafana dashboards and documentation @joncodo 

# WHAT

## Following artifacts should be delivered:
- A working code base could be checkout on our local machine to verify
- A guide to show how to view grafana Dashboards
- A working  Jira Plugin to collect all required data for demo
- A working Gitlab Plugin to collect all required data for demo
- A working Jenkins Plugin to collect all required data for demo

## Following features should be fulfilled:
- User can trigger each plugin by the API request.
- User can view all dashboards on browsers
- User can do all these things with help of our Guides

**Comment by klesh** [comment]
# Plan of the week

## 08/31

- Define jira board issues schema and database model
- Collect jira issues by boardId page by page
- BoardIssue entity

## 09/01

- Jiar leadtimes enrichment
- Jira changelogs collection
- Compound plugin: connect jira board and gitlab project

## 09/02

- Parallelization with go-routine for jira
- Retry mechanism for `ApiClient`

## 09/03

- Integration and test
- Bug fix and improvement

**Comment by narrowizard** [comment]
## Jenkins plan
- create jenkins plugin and get jobs data - 8/31
- get build data and add some test - 9/01
- create grafana dashboard - 9/02

**Comment by hezyin** [comment]
## Updated plan

1. Parallelization of collecting Jira changelogs @likyh 
2. Jira issue type and status mapping @klesh 
3. Fix Jira related metrics in Grafana dashboards @klesh 
4. Fix Gitlab related metrics in Grafana dashboards @joncodo @kevin-kline 
5. docker and user setup workflow @narrowizard 

------------------------------------------------

6.  Support new metrics for Gitlab @joncodo @kevin-kline (https://github.com/merico-dev/lake/issues/257)
7. Create new charts for all 4 new issues @Startrekzky 
8. Cron job @narrowizard 
9. Polish docs
