### ISSUE TITLE
GitLab Plugin: Endpoints for metrics

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#309]
## Description

We need the GitLab collection to target specific endpoints to cover the metrics we want:

- [x] Projects API - https://gitlab.com/api/v4/projects/:id
- [x] Commits API -  https://gitlab.com/api/v4/projects/:id/repository/commits?with_stats=true
- [x] Merge Requests API - https://gitlab.com/api/v4/projects/:id/merge_requests
- [x] Notes API - https://gitlab.com/api/v4/projects/:id/merge_requests/merge_request_iid/notes

*Note merge_request_iid is NOT a typo. iid is correct.

## Describe the solution you'd like

We should be able to trigger a task that collects from these API sources and saves the data into a database.

## Has the Feature been Requested Before?
Not specifically.

**Comment by kevin-kline** [comment]
@joncodo The enriched objects we want look like this:

## Projects: 

{
    name: project.name,
    id: project.id,
    pathWithNamespace: project.path_with_namespace,
    webUrl: project.web_url,
    visibility: project.visibility,
    openIssuesCount: project.open_issues_count,
    starCount: project.star_count
  }

## Commits: 

{
        projectId: commit.projectId,
        id: commit.id,
        shortId: commit.short_id,
        title: commit.title,
        message: commit.message,
        authorName: commit.author_name,
        authorEmail: commit.author_email,
        authoredDate: commit.authored_date,
        committerName: commit.committer_name,
        committerEmail: commit.committer_email,
        committedDate: commit.committed_date,
        webUrl: commit.web_url,
        // some commits can happen with no additions or deletions so stats is not populated
        additions: commit.stats && commit.stats.additions,
        deletions: commit.stats && commit.stats.deletions,
        total: commit.stats && commit.stats.total
      }

## Merge Requests:

{
        projectId: mergeRequest.project_id,
        id: mergeRequest.id,
        numberOfReviewers: mergeRequest.reviewers && mergeRequest.reviewers.length,
        state: mergeRequest.state,
        title: mergeRequest.title,
        webUrl: mergeRequest.web_url,
        userNotesCount: mergeRequest.user_notes_count,
        workInProgress: mergeRequest.work_in_progress,
        sourceBranch: mergeRequest.source_branch,
        mergedAt: mergeRequest.merged_at,
        gitlabCreatedAt: mergeRequest.created_at,
        closedAt: mergeRequest.closed_at,
        mergedByUsername: mergeRequest.merged_by && mergeRequest.merged_by.username,
        description: mergeRequest.description,
        reviewers: mergeRequest.reviewers && mergeRequest.reviewers.map(reviewer => reviewer.username),
        authorUsername: mergeRequest.author && mergeRequest.author.username
      }

## Notes:

{
      id: mrNote.id,
      noteableId: mrNote.noteable_id,
      noteableIid: mrNote.noteable_iid,
      authorUsername: mrNote.author && mrNote.author.username,
      body: mrNote.body,
      gitlabCreatedAt: mrNote.created_at,
      noteableType: mrNote.noteable_type,
      confidential: mrNote.confidential
    }

**Comment by kevin-kline** [comment]
Authentication is set through headers using PRIVATE-TOKEN like this:

res = await axios.get(`${host}/${apiPath}/${resourceUri}`, {
        headers: { 'PRIVATE-TOKEN': token },
        agent: proxy && new ProxyAgent(proxy),
        cancelToken: abort.token
      })

**Comment by klesh** [comment]
We also need changelog for new metrics .
![image](https://user-images.githubusercontent.com/61080/131425093-fd74f215-be9f-4840-a299-6c506bbc92c6.png)
