### ISSUE TITLE
Collector should write data with data schema

### ISSUE THREAD

**Issue by jaxzhou** [merico-dev/lake#31]
- we should defined the data schema
- the data schema would simple handle some validator and primary keys
    - for 'mongodb' the primary keys should generate to '_id' 
    - maybe we would use some ORM later. eg TypeORM
- the schema would have an abstract implement
    - jira schemas would extends from abstract schema
    - and gitlab
    - and github

**Comment by joncodo** [comment]
We will switch to typescript and TypeORM after the MVP release on Aug 18.

I am working on schemas now and primary keys for mongo records
