### ISSUE TITLE
Config dashboard

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#337]
## Description
It would be useful to have a config/monitoring dashboard setup to use with lake. In the MVP version the user can add their config for the plugins (api keys, project ids etc) easily via browser inputs, and with easy guidance. Then in future versions the goal would be to integrate more configuration elements such as global config, grafana config, process monitoring, and maybe some other things like running server commands. 

## Describe the solution you'd like
Potential idea for the best flow of this dashboard:
1. We store executable files on github for each os
2. user runs it, it starts docker container + opens up browser with this interface
3. users can shut it down via ui commands when done (as an option)

## Describe alternatives you've considered
We have considered a CLI tool also for config settings. This may still be a good thing to build (for a focus on devs). But at least for now, devs can navigate config files directly just fine. This proposed UI for non-dev users is more important.

## Screenshots
**Plugins (would be integrated something like this, in a minimal way at first)**
![gitlab](https://user-images.githubusercontent.com/3789273/132023114-8df1dc3d-e6f2-4cd7-9680-2f1c16158510.png)
![jenkins](https://user-images.githubusercontent.com/3789273/132023115-387d50c1-421c-49c6-91ad-0f4c2b266784.png)
![jira](https://user-images.githubusercontent.com/3789273/132023116-cdc7668c-fcd0-40a9-a424-8c1497f6b6a8.png)

**Couple other ones we could do after**
![config](https://user-images.githubusercontent.com/3789273/132023256-0a0b1cf2-342e-4693-b441-9caf7fc9755c.png)
![home](https://user-images.githubusercontent.com/3789273/132023258-5de46d4a-b5d6-4e83-9856-f1650cdecf55.png)

**Comment by hezyin** [comment]
Closing this as the first version has been implemented and we're working on the improvements.
