### ISSUE TITLE
Auto release to docker hub

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#369]
## Description
I suggest adding github action to build and push image to docker hub when `go-main` branch is updated. it'll keep docker image for lake always up to date.

## Describe the solution you'd like
- Add a github action that triggered when go-main branch is pushed.
- The action will build a image for lake, tagged with git commit hash and `latest`
- Push the image to docker hub

**Comment by klesh** [comment]
Good idea! I'm thinking the same thing, except I would prefer auto build on TAG instead of every commit.

**Comment by narrowizard** [comment]
#433
