### ISSUE TITLE
Simplify review_round algorithm and improve performance

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#383]
## Description
Take vdev Merge Request #2539 as example, current algo produce 0 as `review_rounds`, but the `gitlab_merge_request_notes` table indicated differently.
![image](https://user-images.githubusercontent.com/61080/133070243-a16c3d47-6205-47fb-a3ba-c3ffd021f44e.png)

The current approach use commits and notes together to calculate `review_rounds`, which is unnecessary, by observing the screenshot above we can see the notes alone is sufficient for the job, and this is what displayed on the Gitlab MergeRequest Page.

## Describe the solution you'd like
Calculate `review_rounds` with notes only to simplify the algo, and remove all nested queries to improve the performance and lower down the memory footprint.

## Has the Feature been Requested Before?
No

**Comment by hezyin** [comment]
The problem with only using `Notes` is that not all notes with body `added X commits` represent actual new commits. Rebase would also generate this message.
