### ISSUE TITLE
Clearly indicate which configurations are required to change, which are ok to use default values

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#398]
## Description

When users open config-ui, they're given tens of configurations and it's not clear which are required to change, and which are ok to use default values.

## Describe the solution you'd like

Indicate which fields are required via adding a red star or something similar. Below is a list of required configurations:

### Lake core

None

### Jira

1. `JIRA_ENDPOINT`
2. `JIRA_BASIC_AUTH_ENCODED`

### Gitlab

1. `GITLAB_ENDPOINT`
2. `GITLAB_AUTH`

### Jenkins

1. `JENKINS_ENDPOINT`
2. `JENKINS_USERNAME`
3. `JENKINS_PASSWORD`

## Has the Feature been Requested Before?

No

**Comment by klesh** [comment]
Should be resolved by https://github.com/merico-dev/lake/pull/402
Please confirm.

**Comment by oddscenes** [comment]
Done in this: https://github.com/merico-dev/lake/pull/412
