### ISSUE TITLE
Gitlab CI plugin

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#405]
## Description
Integrate a new plugin for gitlab CI

## Describe the solution you'd like
It should capture the same things as the Jenkins Plugin does.

Models:
- gitlab_build

Props:
```
type JenkinsBuildProps struct {
	Duration          float64 // build time
	DisplayName       string  // "#7"
	EstimatedDuration float64
	Number            int64
	Result            string
	Timestamp         int64     // start time
	StartTime         time.Time // convered by timestamp
}
```

Grafana Graphs (We can make the same ones for gitlab):
```
"SELECT\n  now() AS time,\n  count(*)\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1",
"SELECT\n  now() AS time,\n  -- result as metric,\n  result as metric,\n  count(*) as result\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nGROUP BY 1,2\nORDER BY 1",
"SELECT\n  now() AS time,\n  1.0 * count(case when result = 'SUCCESS' then 1 else null end)/count(*)\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1",
"with _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(start_time), INTERVAL -$interval(date(start_time))+1 DAY) as time,\r\n    result\r\n  FROM\r\n    jenkins_builds\r\n  WHERE\r\n    $__timeFilter(start_time)\r\n)\r\n\r\nSELECT \r\n  timestamp(time) as time,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Build Success Rate\"\r\nFROM _build_success_rate\r\ngroup by 1\r\norder by 1",
```

## Questions

1. What is the purpose of capturing Jenkins_job? Do we even use that information anywhere? It seems like we do not use it in the code.
2. Does the API support all the columns we need

## API Docs

https://docs.gitlab.com/ee/api/pipelines.html
https://docs.gitlab.com/ee/api/pipeline_triggers.html
https://docs.gitlab.com/ee/api/pipeline_schedules.html
Note: NOT Available with graphql https://docs.gitlab.com/ee/api/graphql/#available-queries

**Comment by joncodo** [comment]
Data from /plugings

```
{
    "id": 47,
    "iid": 12,
    "project_id": 1,
    "status": "pending",
    "soure": "push",
    "ref": "new-pipeline",
    "sha": "a91957a858320c0e17f3a0eca7cfacbff50ea29a",
    "web_url": "https://example.com/foo/bar/pipelines/47",
    "created_at": "2016-08-11T11:28:34.085Z",
    "updated_at": "2016-08-11T11:32:35.169Z"
  },
```

Data from fetching a single plugin:

```
{
  "id": 46,
  "iid": 11,
  "project_id": 1,
  "status": "success",
  "ref": "main",
  "sha": "a91957a858320c0e17f3a0eca7cfacbff50ea29a",
  "before_sha": "a91957a858320c0e17f3a0eca7cfacbff50ea29a",
  "tag": false,
  "yaml_errors": null,
  "user": {
    "name": "Administrator",
    "username": "root",
    "id": 1,
    "state": "active",
    "avatar_url": "http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
    "web_url": "http://localhost:3000/root"
  },
  "created_at": "2016-08-11T11:28:34.085Z",
  "updated_at": "2016-08-11T11:32:35.169Z",
  "started_at": null,
  "finished_at": "2016-08-11T11:32:35.145Z",
  "committed_at": null,
  "duration": 123.65,
  "queued_duration": 0.010,
  "coverage": "30.0",
  "web_url": "https://example.com/foo/bar/pipelines/46"
}

```

**Comment by joncodo** [comment]
@Startrekzky once this is merged, you can make more charts if you want :)

**Comment by hezyin** [comment]
@Startrekzky Could you please interview the user that request this data source (Letu) to see what additional metrics he needs? Letu will probably be our first user.

**Comment by Startrekzky** [comment]
> @Startrekzky Could you please interview the user that request this data source (Letu) to see what additional metrics he needs? Letu will probably be our first user.

Interview Result:

**Comment by Startrekzky** [comment]
Hi @joncodo  
**Question 1: What is the purpose of capturing Jenkins_job? Do we even use that information anywhere? It seems like we do not use it in the code.**
No, we don't use Jenkins_job for now.  @narrowizard kept this table with the consideration that if we use "Job name" as a filter, it's relatively slower to query filter options by "select distinct job_name from jenkins_build".  @narrowizard you can add your full thoughts in the comment section below.

**Question2: Does the API support all the columns we need**
If you mean GitlatCI API, then Yes.
However, The existing table jenkins_build lacks 1 attribute to describe "on which branch or MR the build is running",
while I saw it in the GitlabCI API response you put in the comment section.
![image](https://user-images.githubusercontent.com/14050754/133731080-c1aed9a5-b5a9-4d80-92a1-2354329d1f30.png)

**Comment by joncodo** [comment]
For this: "He wants to see the job pass/fail rate regarding a specific “job name”, such as "node-test", "node-lint", and to see its variation over time." - The API does not support this data. https://docs.gitlab.com/ee/api/pipelines.html

**Comment by joncodo** [comment]
Updated in this PR: https://github.com/merico-dev/lake/pull/406

**Comment by joncodo** [comment]
@Startrekzky This is ready for you to make charts with

**Comment by leglars** [comment]
please check https://github.com/merico-dev/lake/issues/442. I have some idea related with Gitlab CI integration.
