### ISSUE TITLE
Github Plugin

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#407]
## Description
We would like to collect from more sources and Github is the next big one I think.

We will try to mirror Gitlab as much possible.

## Describe the solution you'd like
models:

### General
- [x] API Pagination @kevin-kline 
- [x] API Auth @kevin-kline 

### Coding Work
- [x] Repositories @kevin-kline 
- [x] Commits @kevin-kline 
- [x] Pull Requests @kevin-kline 
- [x] Pull request labels @kevin-kline 
- [x] Reviewers @kevin-kline 
- [x] Notes on Pull requests @kevin-kline 

### Project management
- [x] Issues @kevin-kline  
- [x] Issue labels @kevin-kline  
- [x] Changes on an issue @kevin-kline  
- [x] Comments on an issue @kevin-kline  

### Devops
- [ ] #564
- [x] @Jon Performance - Remove the get total requests and use sequential for next page header
- [x] @Jon Performance - **Refactor the one network scheduler
- [x] @Jon Performance set the rate ants rate to (number of tokens*1 = 3600 REQUESTS PER HOUR * number of tokens)
- [x] #567
- [x] #568
- [x] @Kev Look at labels problem
- [x] @Kev Collect Changes on issue
- [x] @Kev Collect **Comments on issue
- [ ] #565
- [ ] #566

## Grafana
We have to convert GitHub data to the domain layer to present in Grafana.

- [x] #432

**Comment by joncodo** [comment]
@klesh Kevin is working on this

**Comment by kevin-kline** [comment]
I'm working on implementing ants.

**Comment by kevin-kline** [comment]
I will assume "Changes on an issue" means "Issue events" for now:

https://docs.github.com/en/rest/reference/issues#events

We can refine this later if needed. This is the closest approximation I could find. Let me know if we want something else!

**Comment by joncodo** [comment]
Closing this in favour of new tickets
