### ISSUE TITLE
Datasource specific dashboards

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#408]
## Description
When a user only gathers data from one or two sources, the graphs look bad since a lot of them are missing data.

## Describe the solution you'd like
I think we should have a dashboard for each type of plugin.
This way if you only enable one or two, you will be able to see those dashboards.

Go through all grafana charts for each doashboard and extract all the charts that are only specific to one platform to their respective dashbards for: 
- [ ] Gitlab
- [ ] Jira
- [ ] Jenkins
- [ ] Github

## Questions:

1. If a user only enables gitlab, do we disable all the grafana dashboards except the gitlab one? - Yes. But add to docs to explain.
2. Once they enable more, we show more? - Yes
3. What happens when the user finally enables all dashboards? Do we hide the ones that are only one provider specific? - No. Keep them

**Comment by klesh** [comment]
@joncodo How is this issue going? what is the status of #422?

**Comment by joncodo** [comment]
Done and merged
