### ISSUE TITLE
Fixes for the UI from Klesh Review

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#409]
I notice something is missing from #402:

- [x] All ORIGIN_ should be replaced with YOUR_ (which more descriptive)
- [x] Jira/Gitlab relation must be added: 2c46626
- [x] The required sign (*) is missing.
- [ ] Status mapping / type mapping should be separated to different sections and the status mapping should come first.
- [ ] I like the overall design, pls fix above issues, and we can merge it.

This came from https://github.com/merico-dev/lake/pull/401

**Comment by oddscenes** [comment]
Points 1 and 2: https://github.com/merico-dev/lake/pull/411

**Comment by oddscenes** [comment]
Point 3: 

[x]  The required sign (*) is missing.

https://github.com/merico-dev/lake/pull/412

**Comment by klesh** [comment]
Closing issue due to PRs were all merged
