### ISSUE TITLE
The code should base 64 encode your tokens. You should not have to do it as a user

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#415]
It's too hard for users to figure out. Rankin had some problems.

Instead of making a user do it, let's do it in code for them! :)

**Comment by joncodo** [comment]
Example:
<img width="1069" alt="Screen Shot 2021-09-17 at 1 26 19 PM" src="https://user-images.githubusercontent.com/3011407/133822137-9fae1c10-a11f-4317-9abe-0ebfd89652b0.png">

**Comment by klesh** [comment]
@oddscenes What do u think?

**Comment by oddscenes** [comment]
> @oddscenes What do u think?

Yea definitely should be done in config ui. We also discussed doing it for users in the jira go files, so that the user (even dev setup) won't have to do this step. I can do these in the same pr next week. Then we can remove this encoding step entirely

**Comment by klesh** [comment]
I think for CLI user, a command line example is sufficient, they are technical guys after all, as a heavy CLI user, I would prefer what I see in `.env` fille is what actually sent out, so I can test with `curl` whenever I like without the need to generate base64 auth string by myself.
GUI is meant for no-so-technical guys so we should offer this  kind of ability, I'm thinking a popup dialog for user to enter email and token, when Generate button was clicked, base64 string populated automatically.
