### ISSUE TITLE
Add Domain Layer Push api (Create only)

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#428]
## Use Case

1. Push api makes it more flexible to write plugins
2. It provides a better user experience for async data outside our system. IE: Real time data

## Why do we want this?

1. There are companies that use their own software that we can't make a plugin for. If they want that data, they have to make it and its only for them.
2. Not every company has golang devs. They need to interface with a REST api for our domain layer. 
3. The api we expose does not handle all cases. 
4. Push apis allow 3rd party services to push data to us when the time is right.

## What should it do?

1. Exposes CRUD access to all models in the domain layer.
2. Let sql constraints validate the input. The api returns actual sql debugging information
3. This should be a service separate from lake.

## How secure is it?

1. Prevent some queries from breaking data?
2. Prevent security threats?

## Questions

1. Why do we maintain a plugin architecture AND a REST api? ANSWER: We need both
2. Do we want to maintain both? ANSWER: Yes

## Notes

- This is simply a REST api and not a message queue for real time events
- This should be written in golang

**Comment by kevin-kline** [comment]
## Description
The basic task, as I understand it:

To allow data access to domain layer entities via an API layer.

Not very much is known about this proposal yet. I would like to learn more details on what is needed to complete this task. Please add your input when available @klesh @narrowizard @joncodo 

## Questions

- Why is this needed?
- Can users who wish to inject data do so directly using SQL instead?
- What are the security concerns we need to consider?
- Are we looking for full CRUD routes for all entities?
- Would we consider a single route that is highly configurable?
- What technologies would be useful for this task? (example - a sailsJS server? - https://sailsjs.com/documentation/concepts/blueprints)

## Assumptions

- This is needed for data injection

## Blocked by
- Need for further details

**Comment by joncodo** [comment]
From @hezyin : We should also look into this: https://github.com/smallnest/gen

**Comment by joncodo** [comment]
> From @hezyin : We should also look into this: https://github.com/smallnest/gen

So for this, I think we should not use it. Here is why:

1. It creates code by generation. If we change anything and regenerate, we lose everything. Therefore, at best, this is a one time operation to make an api
2. There is a lot here we do not need in the generated code
3. The code that is generated does not save us that much real time
4. The generated code makes gorm models which we will now have to maintain in two places

We should use @kevin-kline 's generic api instead.
