### ISSUE TITLE
 CI auto-build docker image / trigger mechanism

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#433]
## Description
We are having our first schedule release coming soon, so it's important for us to have a CI/CD system on our first iteration.

## Describe the solution you'd like
A "release task"(CI/CD) should be triggered when a "release tag"( `v\d+\.\d+\.\d+\`) was pushed to our repo.
This "release task" would perform following tasks:
1. Code linting
2. Unit testing
3. Compilation
4. Build docker images 
5. Push all docker images to hub.docker.com

When task was executed successfully, we can then create a new release on Github along with changelog.

**Comment by joncodo** [comment]
I think this is something we don't need as of now since we only release every 2-3 weeks. It's also a lot of work for very payoff at this stage in my opinion. Feel free to re-open

**Comment by narrowizard** [comment]
Is it time to think of it? Beside production release, we may build some alpha(beta) version for integration testing. (eg: Integration with Merico EE System)

**Comment by narrowizard** [comment]
Since we have released version `v0.6.0`, does the auto-release CI work properly? If so, I think we can close this issue now. @klesh

**Comment by joncodo** [comment]
Im not aware of the CI auto build feature. Can you point me to what you mean? I released the last one manually

**Comment by narrowizard** [comment]
The feature is introduced by https://github.com/merico-dev/lake/pull/1021  
It will build and push 3 images (devlake, config-ui and grafana) to docker hub automatically when we push a git tag to this repo.  
After this, you can create a release on it. (Next plan is add the release creation to CI too? ).

**Comment by klesh** [comment]
@joncodo @narrowizard Judge by the log from https://github.com/merico-dev/lake/runs/4764042111?check_suite_focus=true I think the feature was working nicely.
