### ISSUE TITLE
Translate READMEs, config-UI and Grafana dashboards into Chinese

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#435]
## Description
For marketing purpose, we want to support Chinese and enable language switching in the product.

## Describe the solution you'd like
I think these tasks should be done to deliver good UX to a Chinese user:

- [x] A Chinese version of README 
- [x] An link for repo visitors to switch language in both English and Chinese README
- [ ] A Chinese version of config-UI page 
- [ ] A Chinese version of dashboard content, including dashboard name, filter name, chart name and description, chart legends/axis description, and MARI Guide.

## Describe alternatives you've considered
Once we have README in 2 languages, any change of any README should notice @klesh or @Startrekzky  to make sure the other is consistent.

## Additional context
N/A

**Comment by klesh** [comment]
@Startrekzky Note that The PR submission deadline is Monday 6:00 PM CST.

**Comment by Startrekzky** [comment]
> @Startrekzky Note that The PR submission deadline is Monday 6:00 PM CST.

I've moved it to Iter2 according to Dev Lake Phase 3 Plan Discussion #379

**Comment by Startrekzky** [comment]
Hi @oddscenes , I forgot the multi-language support for the CONFIG-UI itself. In order to better translate it, can you give me files or webpages that I can work on?  Another benefit is that when it's done, you can directly use the Chinese version webpages.
I don't know if I made myself clear.

**Comment by klesh** [comment]
Long overdue, nobody asked, nobody cared, close it for now, feel free to re-open
