### ISSUE TITLE
[WIP] Identity mapping across issue management platform and code hosting platform

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#436]
## Description
To measure the productivity of a developer/team/organization, for instance, the story points and PRs that Triforce team delivered in the last month, we have to map developers' identities in Jira and Github/Gitlab.

The scope of identification mapping in this i

## Principles
1. Team and Organization can be seen as the metadata of a user. Their relations:
   - User n:1 Team
   - User n:1 Organization
2. Mapping should apply to the data at the domain layer
3. Mapping action should be performed on UI to make it easy to use.

## Mapping Rules
1. Create domain layer identities from the tool layer identity. A user identity in the domain layer should incorporate at least 5 attributes:
   - user_name
   - email
   - team
   - organization
   - original_identities (a list of identities from specific tools in the same domain)
2. How to map tool identity to domain identity?
   - If the user only import **ONE** tool in a domain, then the domain identity will be the same as the tool identity 
   - If the user imports **more than one** tool in a domain, then the domain user identity can only be determined after another identity-mapping between the tools under the same domain. (@klesh Does this situation exist for now?  For instance, can a user import Jira and TAPD data simultaneously? If not, we can leave it for later, as it'll largely increase complexity.)
3. How to map issue management domain identity to 
4. A paper prototype of identity mapping 

## Describe alternatives you've considered
1. What if a domain has no user identity.
2. What if a user has multiple accounts on the same tool？

**Comment by klesh** [comment]
Related #582

**Comment by klesh** [comment]
Addressed by #1680
