### ISSUE TITLE
AE integration Plan

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#448]
## Description
DevEq is a fair metric to measure contribution among developers, it's important for devlake to be able to display data from AE.

## AE

1. An API to provide analysis result of all commits for specified Git repo with pagination. Oct 20th @liangjingyang 
2. An API to trigger analysis Oct 26 @liangjingyang

## devlake

1. An AE plugin fro AE data collection/enrichment before Oct 26th @klesh 
2. One or more charts showsDevEq metrics before Oct 28th @Startrekzky 
3. Setup cronjob to trigger AE analysis @klesh

**Comment by klesh** [comment]
Discussed with @hezyin , this issue assigned to @joncodo @kevin-kline .

**Comment by joncodo** [comment]
1. Dev lake will never trigger analysis from AE, it only pulls the data that AE already collected through another service.
2. There is already data in the AE instance I can use for sample data

**Comment by joncodo** [comment]
# PLAN OF ATTACK

- [ ] Get familiar with the api
- [ ] Find out an auth key I can use to test
- [ ] Make sure the api contains sample data I can use
- [ ] Create the plugin folder
- [ ] collect projects
- [ ] collect commits
- [ ] Create domain layer plugin
- [ ] Domain layer enhancement based on sha
- [ ] Write readmes
