### ISSUE TITLE
[Jira]Customization of the range of data to collect

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#450]
## Description
For some jira users from ee, they have many many data in their jira instance. It costs too much time and resources to collect all the data from their jira instance.  
We hope to control the data scope by some filters when collecting: 
- update_time: collecting data updated after update_time. 
- project: collecting data belongs to some projects
- board: collecting data related to some boards.

**Comment by klesh** [comment]
support update_time for iter2, project would be delay and further discuss.
