### ISSUE TITLE
Data consistency

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#453]
## Description
For now, if we consume data when the data collect job is running, we will get intermediate state of data, It will confuse users.  
We hope data in intermediate state will not be read by consumers.

## Describe the solution you'd like
Maybe isolate data by data version?

**Comment by klesh** [comment]
You could filter out tasks by status to see if any task was running.

**Comment by narrowizard** [comment]
Not exactly, we should provide a previous version of data when data updating is running, rather than a 'Data is collecting, please waiting' tips.
