### ISSUE TITLE
Multi datasource support

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#455]
## Description
Users of EE often have multi instances of jira, we should set up multi jira source and collect data independently. It's important to isolate data that from multi source.

**Comment by klesh** [comment]
Finally, most of the developers agreed that we should let Plugin management its Multi Connections, who were in favor:

@hezyin 
@mindlesscloud 
@warren830 
@abeizn 
@klesh 


This is final until situation change or new evidence emerge.
