### ISSUE TITLE
Polish config-ui wording and style

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#460]
## Describe the bug
Polish wording and style on config-ui

## Describe the Change

- [x] change `Main Database Connection` to `Dev Lake Database Connection`
![image](https://user-images.githubusercontent.com/14050754/135075549-b382a6a8-f42a-4d91-ae69-2b7d8818c839.png)

- [x] change `mySQL` to `MySQL`

![image](https://user-images.githubusercontent.com/14050754/135075982-9e731eb9-8cde-44dd-abf4-c64ea4fbf0f3.png)

- [x] change `REST Configuration` to `Dev Lake API Server`

![image](https://user-images.githubusercontent.com/14050754/135075852-76ad2e7b-6655-427b-b15d-f6786e03b7bb.png)

- [x] Move section `Jira/Gitlab Connection` in `Jira` config page to `Gitlab` config page. 
Reason: a user who wants to import Jira and Gitlab data will first configure Jira, then configure Gitlab due to the order on UI. It makes more sense for users to configure Jira/Gitlab connection when the individual config for the 2 plugins is completed.

- [x] `Requirement` here should be `Rejected`
![image](https://user-images.githubusercontent.com/14050754/135081930-13256a7f-6d50-41cd-810d-7c905194acbe.png)

- [ ] #504
![image](https://user-images.githubusercontent.com/14050754/135081746-b123ddb3-ebbd-4960-b37c-ed41850db0e4.png)

**Comment by oddscenes** [comment]
> @Startrekzky Im not sure what this one means:
> 
> > add the calculation method in coefficient field to explain to users what is this field for
> 
> Can you share with me the text to include?

This question is part of a new issue, rest of changes are merged
