### ISSUE TITLE
Jira Issues vs. GitHub Issues

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#470]
One of the development tasks for the GitHub Plugin is to collect "Changes on Issues".  My assumption is this is analogous to Jira Changelogs, which are used to calculate Issue Lead Time. However, Issues in GitHub are different from Issues in Jira. So if we are going to calculate Issue Lead Time based on GitHub data, we will need a different approach. 

My understanding is that Jira Changelogs tell us about changes in status from opening to closing. We will want to consider how we can infer changes in status from GitHub data. 

One thing we should consider is that Issues in GitHub are often linked to Pull Requests. We can consider enriched fields like "Time to First Pull Request" on an issue. In this way, we could tell the time between when an Issue is first opened to when a Pull Request is first opened for that Issue, to when that Pull Request is finally merged, and maybe some steps in between, like "reviewed", "commented on" or "assigned". 

These are some suggestions of how we can infer something similar to Lead Time and status changes. Please comment below with any further thoughts or suggestions.

Thanks!

**Comment by hezyin** [comment]
@klesh @Startrekzky Key differences between Jira issue and Github issue:

1. Github issue doesn't have the various statuses that Jira issue has. For Github issue, it's just open or closed.
2. Github issue doesn't differentiate between resolved and rejected. We only know it's been closed.

@kevin-kline Please correct me if I'm wrong.

@klesh @Startrekzky We'll need to factor these differences in when we design the domain layer.

**Comment by klesh** [comment]
Yep, we still need to collect the label-event we talked about the other day.
We may work sth out base on that.

**Comment by joncodo** [comment]
This is now covered in our design docs
