### ISSUE TITLE
Update progress of jira issues with more details

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#479]
## Jira plugin
We hope that task progress info includes number of finished subtasks and total subtasks, and following data if possible:
- number of updated issues
- number of added issues
- number of total issues associated with current task

**Comment by joncodo** [comment]
Moved to other ticket

**Comment by klesh** [comment]
@kevin-kline Why this issue got reopen? Looks like we reached an agreement on #822 already?
Close this for now, feel free to reopen if needed.
