### ISSUE TITLE
DB Records for failed/canceled Tasks

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#486]
## Description
Right now we don't save records for failed tasks in the DB. In the long run we would like to have records of failed tasks.

## Describe the solution you'd like
When a task fails, or is cancelled, we should save a record of the failure or cancellation with a message into the DB.

## Has the Feature been Requested Before?
No.

## Describe alternatives you've considered
None.

**Comment by klesh** [comment]
Will be addressed by #500
