### ISSUE TITLE
Compile-Plugins refactor

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#487]
## Description
Every time we run lake, we compile all of the plugins. This takes development time, which adds up. It is also not necessary, since it is unlikely we are making changes to all plugins at once. 

## Describe the solution you'd like
I would like to see a solution that allows us to pre-select which plugins to compile and run.

## Has the Feature been Requested Before?
No.

**Comment by klesh** [comment]
plugin compilation is quite fast on my machine, especial from the second time forward, golang has this cache mechanism, we could do such an improvement if it was easy to do so, or we don't do it at all.

**Comment by joncodo** [comment]
I got this working locally but I can't seem to get it working on github CI.
<img width="633" alt="Screen Shot 2021-11-23 at 1 08 37 PM" src="https://user-images.githubusercontent.com/3011407/143071097-7da26648-2a28-4079-b633-01c899c86b61.png">

Closing for now as I am not willing to invest more time in this
