### ISSUE TITLE
map issue and commit entities in Jira tool layer

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#490]
## Description
Map issue_id (from issue management domain) and commit_id (from issue management domain) to calculate metrics such as `bug count per commit`.

This is a requirement proposed by our EE team to observe the delivery quality of their work.

## Describe the solution you'd like
Users have 2 logical ways to map the 2 entities: issue and commit.

1. associate commit(s) to an issue, no matter it's the id, url, or value that contains the distinct identifier of a commit. Eg. use a field in Jira issue to store commit url.
2. associate issue(s) to a commit, no matter it's the key, url, or value that contains the distinct identifier of an issue. Eg. add an issue key like "EE-2581" in a commit message in Gitlab.

The EE team uses [Gitlab for Jira](https://docs.gitlab.com/ee/integration/jira/connect-app.html), a Jira plugin that enables commits, branches, and MR in Gitlab projects to be synced to Jira.

When developers submit a commit with a commit message that includes an issue key like "EE-5315", the Gitlab url of this commit will automatically be stored in the `web link` field of a Jira issue. E.g. merico.gitlab.com/xxx/~/commit-abcdefg.

We can parse the value of  `web link` to get the commit id, `abcdefg`, by parsing the web link that matches the commit url rule.

![image](https://user-images.githubusercontent.com/14050754/136651204-d1525f5b-f072-4689-9f32-7ef947304833.png)

However, this approach is only used by our EE team. Other users may use various personalized ways to log the commit identifier in a field of an issue. Therefore, we should 

- [ ] allow users to specify the field to be parsed, no matter in which domain the field is
- [ ] hardcode the parsing rule

## ER Relation between Issue and Commit
Issue:commit  = n:n
An issue can map to multiple commits, a commit can map to multiple issues.

## Questions
1. It seems different users may use different methods to link Jira issues to Gitlab commits, this may lead to a result that Commit url may appeared in Jira issue's comment section or remote link or other fields.

**Comment by narrowizard** [comment]
## Additional information for `GitLab.com for Jira Cloud` 
- https://marketplace.atlassian.com/apps/1221011/gitlab-com-for-jira-cloud?tab=overview&hosting=cloud

> GitLab for Jira requires:
> - GitLab.com. Self-managed GitLab is not supported.
> - Atlassian Cloud.

**Comment by narrowizard** [comment]
TODO: add jira-gitlab testing data getting handbook. @narrowizard
