### ISSUE TITLE
Remove all tooltips in config-ui

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#497]
## Describe the bug
Tooltips are sometimes buggy, flashing on input hover. Layout will still work in most cases, but I think its best to remove these tooltips. As the layout has lots of labels and stuff they're kind of redundant at this point too.

## To Reproduce
1. Go to any page on config ui
2. Hover over an input
3. Move mouse around and hover over different inputs. Better experience to take these out

## Expected behavior
No unnecessary tooltips

## Screenshots
![Screen Shot 2021-10-12 at 2 33 56 PM](https://user-images.githubusercontent.com/3789273/137010348-1639445b-fed8-4e0a-9673-47bd868e2089.png)

**Comment by e2corporation** [comment]
Existing tooltips appear to be working fine, this is a non-issue for now. Closing ticket.
