### ISSUE TITLE
Convert Jira issue types to standard issue types in domain layer

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#501]
## Description
Convert users' own Jira issue types to standard issue types in "Issue Management Domain Layer".

## Describe the solution you'd like
1. standard issue types
   - Requirement
   - Bug
   - Incident
   - Other

2. Users only need to configure `Requirement`, `Bug`, `Incident` on config-UI, and all the rest issue types will be converted to `Other`. See prototype below
![image](https://user-images.githubusercontent.com/14050754/137462917-303180c0-105c-4222-b7fa-32c9094fec31.png)

## Describe alternatives you've considered
As many users use 'subtask' in Jira and TAPD as a real-life task/action item for developers, I'm considering adding another standard type called "Task".
However, due to the unclear usage of this issue type, we can leave it to later iterations.

**Comment by klesh** [comment]
The problem is... How can we sort data by its 'priority'  when priority is not numeric?
