### ISSUE TITLE
Enable language switching in config-UI and Grafana Dashboard

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#502]
## Description
For marketing purpose, we want to support Chinese and enable language switching in the configuration process and Grafana dashboards.

## Describe the solution you'd like
I think these tasks should be done to deliver good UX to a Chinese user:

- [ ] Files for config-ui that @Startrekzky can translate on it.
- [ ] Allow users to switch the language of the configuration page.
- [ ] Allow users to switch the language of Grafana dashboards.

## Describe alternatives you've considered
- This issue is blocking https://github.com/merico-dev/lake/issues/435

**Comment by oddscenes** [comment]
For my part in this there's 3 things that I see, just to keep track of:
- [ ] Seperate language files into English / Chinese
- [ ] Localize component/layout files with language file vars

step 2
- [ ] add language switching ability in UI/routes

**Comment by klesh** [comment]
Long overdue, nobody asked, nobody cared, close it for now, feel free to re-open
