### ISSUE TITLE
API Specific Plugin Layer for Validation

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#503]
## Description

Right now if we receive a bad data input from the API request, the plugin checks those inputs and if one fails, we are not able to send back a 500 status error to the request. This prevents us from giving the user a helpful error message to fix their JSON format. 

The reason this happens is that we UnMarshal all requests at the API level and the plugins only receive the unmarshalled response. 

## Describe the solution you'd like
Pass the raw HTTP request to the plugins, and let the plugins validate it and return errors to the HTTP request. This could be in the form of having the API layer call a plugin.Validate() method before plugin.Execute().

## Has the Feature been Requested Before?
No.

**Comment by klesh** [comment]
To verify if a request body is valid json format should be dealt with on framework level, because it was not related any specific plugin logic.
Now we had 400 status code and a Offset to indicate this kind of error, I think it's sufficient for now.
Closing this
