### ISSUE TITLE
add the calculation method in `coefficient field` to explain to users what is this field for

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#504]
@Startrekzky Extracted this issue on its own because we need some more discussion on how to best present this one to the user. Its an important field but a hard one to explain (in config ui)

Once we got a good solution here, I can implement it. Maybe just some text/image or a different form element

![135081746-b123ddb3-ebbd-4960-b37c-ed41850db0e4](https://user-images.githubusercontent.com/3789273/137184228-1956b03c-2a5f-40f9-bd6e-bb4067491f58.png)

**Comment by Startrekzky** [comment]
This field `coefficient` will be removed from the future design.
