### ISSUE TITLE
Config UI - "Filter Status Mappings" search bar appears to not work.

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#507]
## Describe the bug
Typing into the search bar yields no results.

## To Reproduce
1. Go to http://localhost:4000/plugins/jira
2. Click on "Filter Status Mappings" search bar, and type something.
3. See no results

## Expected behavior
I expect to see some result.

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/137321867-e9b044b6-579b-496e-8101-ed993ab1a4cc.png)

**Comment by klesh** [comment]
redesigned
