### ISSUE TITLE
npm run commit has some issues?

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#51]
@narrowizard when I run the comman `npm run commit`,

If get this message: 

```
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

Is this something that can be ignored? Or do you want this husky thing running?

**Comment by UltimateBeaver** [comment]
I got the same warning and the following command solved the problem for me.

`chmod +x .husky/commit-msg`

Could you please make a PR for this change?

**Comment by UltimateBeaver** [comment]
Resolved in https://github.com/merico-dev/lake/pull/54
