### ISSUE TITLE
Clicking on input removes a tag in config ui

### ISSUE THREAD

**Issue by oddscenes** [merico-dev/lake#512]
## Describe the bug
When clicking on an input a tag gets removed and flickers a bit in the `/plugins/jira` page

## To Reproduce
1. Go to `/plugins/jira`
2. Click on any input with a tag
3. Notice some of the tags get removed

## Expected behavior
Clicking on a tag in the tag input makes tags disappear

## Screenshots
![Screen Shot 2021-10-14 at 3 04 33 PM](https://user-images.githubusercontent.com/3789273/137380021-f41f2260-26ba-439b-993f-d7ef5c121a25.png)

**Comment by klesh** [comment]
Aah... this `TagInput` component seems buggy quiet a lot,  might as well roll our own!

**Comment by e2corporation** [comment]
Closing for now, I don't see an issue with how the current input+tag selectors are working.
