### ISSUE TITLE
`config-ui` adopts JIRA configuration API and new UI designs

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#516]
## Description
Due to breaking change of PR #491, `config-ui` will have to update accordingly, or jira configuration part wouldn't function at all.

1. @Startrekzky  will design an prototype for multi-datasources supporting (#519)
2. @e2corporation  will implement the new design for `config-ui` with a focus on the multi data sources part for now

**Comment by klesh** [comment]
Due to #517, we will remove status mapping from jira configuration to simply the setup process.

**Comment by joncodo** [comment]
Broken into other tickets
