### ISSUE TITLE
Refactor: make all scoping parameters optional

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#529]
## Description
The requirement originates from a discussion about "how to collect Jira Epics" between @runjinz @klesh @Startrekzky  
As we collect Jira issues by `board`, if Epic-type issues are not in the board, they can't be collected.

## Why don't we collect issues just by `board`
There're several reasons:
1. Issues are collected by `board`, but metrics `requirement lead time` is not calculated according to board column (a set of statuses), which are not consistent
2. Issues in the Backlog or in particular types are not collected, but they're needed in project management
3. The fewer items configured by the user, the better
4. Dev Lake's core is data, we should collect as much data as possible 

## Describe the solution you'd like
1. Collect all Jira issues by default
2. Users can choose the specific boards they want to analyze, but it's an option

## Describe alternatives you've considered
1. As We're focusing on small to medium-sized companies, we don't have to consider too much about the performance when collecting all issues.
2. This change may affect the logic of config-UI, such as the issue type list and customized field list.
3. Another possible solution for this is to let Dev Lake link to Users' own Jira DB.

**Comment by klesh** [comment]
Not only for jira, but also all plugins.
Right now we dont have a consistence way of handling scoping parameters like (boardId for jira/projectId for gitlab)
Some tasks take scoping parameters as compulsory, and other might just ignoring them altogether which quite confusing.
We should deal with these parameters consistently

**Comment by klesh** [comment]
Long overdue, nobody asked, nobody cared, close it for now, feel free to re-open
