### ISSUE TITLE
More accurate task status

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#532]
## Description
Now we have 3 status for task: `TASK_CREATED`, `TASK_COMPLETED` and `TASK_FAILED`. I think `TASK_CREATED` is not equal to `TASK_RUNNING`. we need more accurated task status to clarify wether the task is running or queueing.

## Describe the solution you'd like
Add status `TASK_RUNNING` for task status list.

**Comment by joncodo** [comment]
This seems old. Do we still need this? @kevin-kline @klesh

**Comment by klesh** [comment]
@joncodo yes, I would address this issue as I work on #824
