### ISSUE TITLE
Encrypt jira configuration

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#536]
## Description
Now we stored jira configuration directly into database or config file. It doesn't meet security requirement from some customers of EE. Mostly caused by user credits config keys.

## Describe the solution you'd like
We should encrypt user credits (eg: jira token) before store it, and keep the encrypt key away from the encrypted user credits. I means store them in different place. Then it is safe even if the encrypted user credits is leak.

## Additional context
I create this issue for recording, no need in this iterator.

**Comment by mappjzc** [comment]
# PLAN OF ATTACK
1. Add the functions Encode and Decode in /plug/core/plugin_utils.go to be responsible for encryption and decryption respectively
2. The key is stored in the .env file, if it is not set, it will be automatically generated (or encryption and decryption does not work?)
3. Use this key to encrypt sensitive data of jira.

- [ ] Find suitable encryption algorithms and related tool libraries
- [ ] Complete the Encode and Decode logic
- [ ] Complete the processing logic for jira's sensitive data
- [ ] complete test

**Comment by klesh** [comment]
merged
