### ISSUE TITLE
Standardize how we lint code locally

### ISSUE THREAD

**Issue by UltimateBeaver** [merico-dev/lake#55]
We need a solution for the linting problem. The goal is to standardize how we do linting locally so we never see the linting changes in PR in the future.

**Comment by joncodo** [comment]
I think we should all use prettier. It is what is required by react open source.

## Config

There are two config files needed: 

Ignore file: https://github.com/facebook/react/blob/main/.prettierignore
Config file: https://github.com/facebook/react/blob/main/.prettierrc.js

## Command

React supports two command: `npm run prettier` and `npm run prittier-all`. The first one only checks on your changes.

https://github.com/facebook/react/blob/main/package.json#L138

## How it works

This file runs prittier with npm. https://github.com/facebook/react/blob/main/scripts/prettier/index.js

## Packages Required

`const prettier = require('prettier');`

https://www.npmjs.com/package/prettier

## Using with vs code or other editors

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by joncodo** [comment]
It looks like the ts-main branch does something very close to this already. We can stick with that :)
