### ISSUE TITLE
Product Introduction video

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#558]
## Description
Apart from README and test-based product introduction documents, we want to have a product introduction video. It can be a supplementry to our demo sites.
No R&D resources are required.

## Describe the solution you'd like
A 2-3 minutes video that introduces:
1.  what is Dev Lake
2. what's the value of using Dev Lake
3. how to use Dev Lake
   - installation
   - analysis
   - conduct a customized analysis

## Describe alternatives you've considered
1. It's for marketing purpose and @Startrekzky will be collaborating with @MaximDub @nitinvasanth to work on this task in the way that 
   - @Startrekzky  provide raw content: screenshots, documents, etc
   - @MaximDub @nitinvasanth do the video shooting, dubbing and editing, etc.
2.  The priority of this task is lower than it of demo sites #557 .  
3. it's blocked by #537 and #557

**Comment by klesh** [comment]
@Startrekzky Please update progress

**Comment by Startrekzky** [comment]
> @Startrekzky Please update progress

We have an intro video about WHAT and WHY of DevLake,  the HOW part is missing. I don't think we should make such video until DevLake has a major version with a stable and easy-to-easy installation process.
