### ISSUE TITLE
Complete all data required by EE Sprint Performance

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#561]
## Description
To support EE implemented the following charts base on devlake

![image](https://user-images.githubusercontent.com/61080/138910204-882434b3-80e3-488f-99c2-5e9e0977c2f2.png)

## Describe the solution you'd like
Collect all data needed to implement those charts

## Has the Feature been Requested Before?
No

**Comment by Startrekzky** [comment]
Duplicated with #700
