### ISSUE TITLE
Github Actions Collection

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#564]
We want to get data from GitHub about pipelines.

Questions:
- What data specifically do we need?

We have endpoints for:
- Workflows
- Workflow runs
- Workflow jobs

**Comment by Startrekzky** [comment]
Hey Kevin, is this pipeline data similar to it from Jenkins or GitlabCI?

**Comment by klesh** [comment]
Long overdue, nobody asked, nobody cared, close it for now, feel free to re-open
