### ISSUE TITLE
Improve application unit and integration testing

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#571]
## Description
I feel like our repository will get less user adoption since we have a low amount of tests. Good code needs tests and we need to make this more of a priority. 

We need some tests to cover:
- [ ] all util methods
- [ ] All api route calls mocked out so we can test collection
- [ ] Tests to make sure all records exist in the db that should
- [ ] Tests in CI with DB

**Comment by klesh** [comment]
Addressed by #1754
