### ISSUE TITLE
Jira will not return emails to us in the api

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#582]
## Description
In order for us to link users together in the future we need to use the key of emails. In the Jira API, you can't get emails unless you are an approved atlassian application. For this, you get keys from attlassian for your public application. This will likely not work for our users since they all will need to get an approved app.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-user-email-bulk-get

"Returns a user's email address. This API is only available to apps approved by Atlassian, according to these guidelines.

Connect app scope required: ACCESS_EMAIL_ADDRESSES"

I think this means we can't rely on emails from Jira

**Comment by klesh** [comment]
@Startrekzky  @hezyin @mindlesscloud @kevin-kline @runjinz @narrowizard 
Any thought? We have to come up a solution for user identity across different platform.

**Comment by Startrekzky** [comment]
My proposal is to parse the filter field in issue changelog to get the projects those issues belong to, and then we can get user email by the project lists we have.

**Comment by klesh** [comment]
> My proposal is to parse the filter field in issue changelog to get the projects those issues belong to, and then we can get user email by the project lists we have.

How so?  We can't get user email by project AFAIK.

**Comment by Startrekzky** [comment]
> > My proposal is to parse the filter field in issue changelog to get the projects those issues belong to, and then we can get user email by the project lists we have.
> 
> How so? We can't get user email by project AFAIK.

Sorry, I thought we could get user email by project

**Comment by klesh** [comment]
No Automated User Identitification Mechanism is viable.
Close this for now
