### ISSUE TITLE
Develop Source APIs to read/write to DB (instead of .env)

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#592]
## Description
To enable multi-source plugin functionality, we need to save to the DB.

- [ ] GitLab
- [ ] Jenkins

## Describe the solution you'd like
I would like to store source data to the DB instead of .env.

## Has the Feature been Requested Before?
No.

**Comment by klesh** [comment]
Different plugins would support multi data source at different timing, It doesn't seem right to make them all support MDS at once.
We should create issue like #636 one by one, and tackle them separately.
Closing this for now, feel free to reopen and discuss.
