### ISSUE TITLE
JIRA Settings Management: API Endpoints

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#594]
## Description
In order to satisfy the needs of the **Config-UI Refactor**, the **JIRA Settings Management** UI needs specific endpoints to drive the **Selector** Widgets that pertain to the following settings:

- **Epic Key** (`epics`)
- **Requirement Granularity** (`granularities`)
- **Board ID** (`boards`)

## Describe the solution you'd like
BE needs to implement 3 individual endpoints to provide this data. At minimum the following fields must be provided for each response entry for all of the 3 above data sets, **epics**, **granularities** and **boards**.

- **id** (`Integer` `UNIQUE` Index ID)
- **title** (`String` Label for selector)
- **value** (`String` actual field name value)

Additional fields

**GET** Epics
`/plugins/:provider/sources/:sourceId/epics`

```
{
[
    { id: 0, title: 'Custom Field 1000', value: 'customfield_1000' },
    { id: 1, title: 'Custom Field 2000', value: 'customfield_2000' },
    { id: 2, title: 'Custom Field 3000', value: 'customfield_3000' },
    { id: 3, title: 'Custom Field 4000', value: 'customfield_4000' },
    { id: 4, title: 'Custom Field 5000', value: 'customfield_5000' },
  ]
}
```

**GET** Granularities
`/plugins/:provider/sources/:sourceId/granularities`
```
{
[
    { id: 0, title: 'Story Points', value: 'customfield_6000' },
    { id: 1, title: 'Original Estimate', value: 'customfield_7000' },
]
}
```

**GET** Boards
`/plugins/:provider/sources/:sourceId/boards`

```
{
[
    { id: 1, title: 'Open', value: '1' },
    { id: 2, title: 'Backlog', value: '2' },
    { id: 3, title: 'QA / Testing', value: '3' },
    { id: 4, title: 'Pre-release', value: '4' },
    { id: 5, title: 'Production', value: '5' },
    { id: 6, title: 'Closed', value: '6' },
]
}
```

## Has the Feature been Requested Before?
No

## Describe alternatives you've considered
Hard-coded static values (mock data) could be used however that would not be a sensible production-ready solution.

## Additional context
See the current config-ui code on `main` branch for UX reference, also see additional screenshots below for where these data points would map to.

<img width="1424" alt="Screen Shot 2021-11-02 at 1 32 49 PM" src="https://user-images.githubusercontent.com/1742233/139918222-ef909d97-005f-4e4f-b533-5cb96a71d2bd.png">
<img width="755" alt="Screen Shot 2021-11-02 at 1 33 14 PM" src="https://user-images.githubusercontent.com/1742233/139918209-b20a8adb-de45-4c8d-b6e4-1be9ce6584f2.png">
<img width="775" alt="Screen Shot 2021-11-02 at 1 33 04 PM" src="https://user-images.githubusercontent.com/1742233/139918216-75328d04-6c39-44e2-8b53-358b6f66e050.png">
<img width="874" alt="Screen Shot 2021-11-02 at 1 32 59 PM" src="https://user-images.githubusercontent.com/1742233/139918219-84cba2af-cfcb-491e-bd36-03a43a62f99d.png">

**Comment by klesh** [comment]
I don't think PR #597 could solve this issue.
Configuration happen before Data Collection, so there would be nothing in database during configuration phase.
I suggest that using https://github.com/merico-dev/lake/pull/639 for this kind of purpose.

**Comment by joncodo** [comment]
Closing this for now. If we want to make these into drop downs again, we need backend support and a new ticket needs to be opened
