### ISSUE TITLE
Use `*time.Time` instead of `time.Time` for null value handling

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#599]
## Description
Now we have most of our datetime fields as type `time.Time`, and using `IsZero` to check if fields were `null`. That is due to documentation we found indicated the way to handle null value in database should be wrapped inside `sql.NullTime`.

According to @mindlesscloud , gorm can handle `*time.Time` being `nil` and represent null value in database correctly.
And seems like `json.Unmarshal` could also handle the pointer correctly. 

So, it appears that using `*time.Time` is a better way to handle the null value situation. We should verify these information, and consider other factors, and see if we opt for this way of nullable time.Time handling.

## Describe the solution you'd like
1. Verify if `json` lib and `gorm` can `*time.Time` as expected
2. Change all `nullable time.Time` type to `*time.Time`  if everything work out 

## Has the Feature been Requested Before?
No

## Describe alternatives you've considered
Stay with `time.Time` with `IsZero` which is less elegant and error-prone

**Comment by joncodo** [comment]
IE: 

```
type Commit struct {
	base.DomainEntity
	RepoId         uint64 `gorm:"index"`
	Sha            string
	Additions      int
	Deletions      int
	Message        string
	AuthorName     string
	AuthorEmail    string
	AuthoredDate   *time.Time
	CommitterName  string
	CommitterEmail string
	CommittedDate  time.Time
}
```

Where `ComittedDate` is `not null` and `AuthoredDate` is `null`

This is further validated here: https://stackoverflow.com/a/65951503/825094

**Comment by kevin-kline** [comment]
> # PLAN OF ATTACK
> IE:
> 
> ```
> type Commit struct {
> 	base.DomainEntity
> 	RepoId         uint64 `gorm:"index"`
> 	Sha            string
> 	Additions      int
> 	Deletions      int
> 	Message        string
> 	AuthorName     string
> 	AuthorEmail    string
> 	AuthoredDate   *time.Time
> 	CommitterName  string
> 	CommitterEmail string
> 	CommittedDate  time.Time
> }
> ```
> 
> Where `ComittedDate` is `not null` and `AuthoredDate` is `null`
> 
> This is further validated here: https://stackoverflow.com/a/65951503/825094
> 
> ### NOTES
> * I am not sure how to decide which ones can be null or not. I think one way of determining this is to set all fields to nullable and run a full test to make sure nothing fails. I think the null time should probable be the default case. Please advise

I faced that problem of which one's should be nullable / not nullable. I made the ones I thought should be nullable sql.NullTime types using my best judgement. So for starters we could just replace those with *time.Time

**Comment by kevin-kline** [comment]
I'd like to make a case for closing this issue instead of spending additional time on it. 

1. We already decided on sql.NullTime and invested time in that solution: #426 
2. We are not solving a concrete problem and should be considered low priority.
3. It will take considerably more time to change this due to the intricacies of how we've done it thus far.
4. Any new plugin that we implement can choose to use *time.Time instead of sql.NullTime, but I don't see the logic in changing old ones.

@joncodo @klesh

**Comment by joncodo** [comment]
I agree with @kevin-kline and I am closing this. Feel free to re-open with a reason @klesh

**Comment by klesh** [comment]
No problem, I will do it.

**Comment by joncodo** [comment]
Sure but can you tell me why we need this change? I don't understand the technical reason.

**Comment by klesh** [comment]
1. `*time.Time` is neater and easy to work with.
2. Handle nullable time in different ways creates confusion for new team member and contributor (if any)
3. By removing `sql.NullTime` we can remove those conversion logic as well, those are liability. I would like to remove `Iso8601Time` code if we could find a better solution, like some reliable lib.
4. It's easy to do so, 15mins of coding, although collecting data for testing tooks me more than an hour thanks to GFW 😂
