### ISSUE TITLE
Config-UI: Implement "Collect" buttons to Plugin connections tables.

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#601]
Each plugin has a connections table. Each item in the table has 3 buttons (Settings, Collect, and Test). We need to add "Collect" and "Test".
Collect should allow us to send a POST request to the Task API. We should let the user configure the request via modal (or some other way)
Test should send a GET request to the Plugin API to test if the currently saved credentials for the Plugin get a 200 response from the third-party API.

![image](https://user-images.githubusercontent.com/27032263/140063862-fa82fa97-f213-4f73-9e93-469d9348e1ec.png)

**Comment by klesh** [comment]
Keep "Collect", remove "Test", make this solo task

**Comment by e2corporation** [comment]
Linked to #843

**Comment by hezyin** [comment]
This is waiting for #843
