### ISSUE TITLE
Config-UI: GitLab to Jira Board Mappings

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#604]
## Description
Allow user to map Jira Boards to GItLab Projects with intuitive modal.

![image](https://user-images.githubusercontent.com/27032263/140066544-357679a3-d2d0-49a1-820d-8693cd1da81c.png)

![image](https://user-images.githubusercontent.com/27032263/140066472-8c31a01f-bc58-4999-b604-8d1ab2eb9934.png)

**Comment by klesh** [comment]
This kind of relationship will be dealt with on Domain Layer level. Closing this.
