### ISSUE TITLE
Config-UI: Edit GitLab Connection

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#608]
## Describe the bug
- [ ] Page has incorrect fields
- [ ] Should load real data from /sources
- [ ] Placeholder text is incorrect (it is same as Jira)

## To Reproduce
1. Go to http://localhost:4000/connections/edit/gitlab/<source_id>

## Expected behavior
The proper fields for GitLab are:
- GITLAB_AUTH
- GITLAB_ENDPOINT
- JIRA_BOARD_GITLAB_PROJECTS

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/140070878-5db90f75-4250-41e4-be3d-c21f164e8555.png)

**Comment by e2corporation** [comment]
Linked to #608
