### ISSUE TITLE
Config-UI: All Plugin Tables have power buttons

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#609]
## Describe the bug
There is a Power button icon in the tables. Let's remove that.

## To Reproduce
1. Go to http://localhost:4000/integrations/jira

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/140071395-7f848149-a3de-4034-9147-d2374d9e73cf.png)

**Comment by joncodo** [comment]
@e2corporation can explain these power buttons in a new proposal ticket. Then we can get it cleared by @Startrekzky and @hezyin for approval to work on. This ticket is simply to remove them for this release

**Comment by Startrekzky** [comment]
Let's get it removed as it's not in the prototype.
