### ISSUE TITLE
Config-UI: Delete single connection endpoint

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#619]
## Description
We need a way to delete connections for Plugins. 

## Describe the solution you'd like
- [ ] We need a button in the "Connections" tables for each plugin, on connection items. (Frontend)
- [ ] We need a backend route to delete the connection information. (Backend)

## Has the Feature been Requested Before?
No.

## Additional context
PLEASE NOTE: Only Jira currently supports multi-sources in the DB. So the Jira plugin can delete source from the database. GitLab and Jenkins will need to simply assign their credentials in the .env file to empty.

**Comment by klesh** [comment]
Make sure pop up a Confirmation dialog
