### ISSUE TITLE
RegisterRouter method: Plugin Routes send 201 HTTP response by default 

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#623]
## Description
In router.go, the RegisterRouter method contains this logic:

![image](https://user-images.githubusercontent.com/27032263/140158164-6fc3662b-1c04-4e28-9555-ee7880931aa6.png)

However, certainly not all API resources should return 201. This is only for "Created" methods like POST.

## Describe the solution you'd like
We should implement some logic to decide what type of response to return based on the route type.

## Has the Feature been Requested Before?
No.

**Comment by klesh** [comment]
Should be `StatusOK`

**Comment by klesh** [comment]
Closes by #705
