### ISSUE TITLE
Capital vs lowercase UI variables

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#628]
`{connection.endpoint || connection.Endpoint}`

So the backend golang routes return Capital letters since lowercase letters mean private properties in GO.

```
return &JenkinsSource{
Endpoint: configJson.JENKINS_ENDPOINT,
Username: configJson.JENKINS_USERNAME,
Password: configJson.JENKINS_PASSWORD,
// The UI relies on a source ID here but we will hardcode it until the sources work is done for Jenkins
ID:   1,
Name: "Jenkins",
}, nil
```

**Comment by joncodo** [comment]
Moving to the backlog for now since there are so many other things to do

**Comment by klesh** [comment]
Will be address by the 'New Blueprint User Flow'
