### ISSUE TITLE
Update wordings on Jira configuration page to question-based sentences

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#637]
## Description
To help users easily understand 
1. why to configure
2. what to configure
3. how to configure
during the plugin configuration, especially Jira configuration page

## Describe the solution you'd like
Change the description/tips to question-based sentences.

For instance, now the description for "issue type mapping" is 
 > "Your issue types will be converted to 3 standard types for metrics calculation, such as requirement count.

For better understanding, we can modify it to something like:
> What issue types would you consider as a `requirement`? 
> What issue types would you consider as a `bug`? 
> What issue types would you consider as a `incident`?

**Comment by klesh** [comment]
Will be addressed #1862
