### ISSUE TITLE
Move domain layer entities to Framework level

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#638]
## Description
Now we had `domain layer` as an optional plugin, the Devlake Framework itself acts like a Plugin Manager and Task Manager, and let plugin do basically all the work. This approach provides maximum freedom for plugin development, but also adds burden to plugin developer, and not possible to enforce some standard behaviors onto plugin.

Domain Layer Entities is the **contract** between **data sources** and **grafana charts**, With Domain Layer Entities being compulsory, framework can gain control over the system.

## Describe the solution you'd like
1. Step 1
  - Move all domain layer entities to devlake framework
  - Make sure all plugin compile and execute properly
2. Step 2
  - Combine domain-layer-conversion plugin into data-source plugin, i.e. `jiradomin` -> `jira`
  - Update `Execute` method, add `convertXXX` tasks.
3. Step 3: 
  - Document
  - config-ui json

**Comment by hezyin** [comment]
@klesh 

I understand the rationale of having the framework internalize the domain layer entities and step 1 of the solution, but steps 2 and 3 are a bit abstract for me. Below are some questions:

1. Can you elaborate more on "Plugin exposes all its tasks to the framework, and remove Execute method"? Right now, a task refers to a single invocation of a plugin's `Execute` method. But it seems like you're referring to something else with the word "task" here. Can you illustrate the new plugin interface you're proposing with the Jira plugin as an example?
2. If plugins aren't allowed to write directly to the domain layer table, what does a plugin produce, and how does the framework take it from there? What would be the benefit of doing things this way compared to allowing plugins to write directly to the domain layer table?
3. How does this proposal help resolve the data isolation problem?

**Comment by klesh** [comment]
Step 2 and 3 were base on the "Framework Do More" approach, the idea is to let Framework do more work and gain more control.
> @klesh
> 
> I understand the rationale of having the framework internalize the domain layer entities and step 1 of the solution, but steps 2 and 3 are a bit abstract for me. Below are some questions:
> 
> 1. Can you elaborate more on "Plugin exposes all its tasks to the framework, and remove Execute method"? Right now, a task refers to a single invocation of a plugin's `Execute` method. But it seems like you're referring to something else with the word "task" here. Can you illustrate the new plugin interface you're proposing with the Jira plugin as an example?
As I went through all our plugins, the structure of `Execute` are quite similar, which could be abstracted away from plugin and let framework manage the process, Framework knows how many tasks to run, progress implementation would be more concise.
> 2. If plugins aren't allowed to write directly to the domain layer table, what does a plugin produce, and how does the framework take it from there? What would be the benefit of doing things this way compared to allowing plugins to write directly to the domain layer table?
This is a proposal from @mindlesscloud ,  Plugin output a set of domain entities, and framework is responsible for verification and storage. It's like if a plugin implement a `IssueConverter`, then framework would call this interface, and receive a set of standard `Issue` , then check it and save it, this way, we can control the locking, data constraint stuff like that on Framework level, Plugin implementation would be simpler, if we went for "Framework Do More" approach, this is one way to go .
> 3. How does this proposal help resolve the data isolation problem?
I don't know how should we solve the data isolation problem, because I dont think we have already fully define the isolation problem either. But moving domain entities to framework should be done before we addressing the data isolation problem.

**Comment by klesh** [comment]
> Step 2 and 3 were base on the "Framework Do More" approach, the idea is to let Framework do more work and gain more control.
> 
> > @klesh
> > I understand the rationale of having the framework internalize the domain layer entities and step 1 of the solution, but steps 2 and 3 are a bit abstract for me. Below are some questions:
> > 1. Can you elaborate more on "Plugin exposes all its tasks to the framework, and remove Execute method"? Right now, a task refers to a single invocation of a plugin's `Execute` method. But it seems like you're referring to something else with the word "task" here. Can you illustrate the new plugin interface you're proposing with the Jira plugin as an example?
> > 2. If plugins aren't allowed to write directly to the domain layer table, what does a plugin produce, and how does the framework take it from there? What would be the benefit of doing things this way compared to allowing plugins to write directly to the domain layer table?
> > 3. How does this proposal help resolve the data isolation problem?

1. As I went through all our plugins, the structure of `Execute` are quite similar, which could be abstracted away from plugin and let framework manage the process, Framework knows how many tasks to run, progress implementation would be more concise.
2. This is a proposal from @mindlesscloud ,  Plugin output a set of domain entities, and framework is responsible for verification and storage. It's like if a plugin implement a `IssueConverter`, then framework would call this interface, and receive a set of standard `Issue` , then check it and save it, this way, we can control the locking, data constraint stuff like that on Framework level, Plugin implementation would be simpler, if we went for "Framework Do More" approach, this is one way to go .
 3. I don't know how should we solve the data isolation problem, and I dont think we have already fully define the isolation problem either. But moving domain entities to framework should be done before we addressing the data isolation problem, so this is the very first step...
