### ISSUE TITLE
Config-UI: Change Jira dropdowns to text fields

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#640]
## Description
Jira configuration on the frontend is too complex for this iteration. 

## Describe the solution you'd like
We should simplify it by reverting dropdown menus (Epics, Granularity, Boards) to editable text fields. This way it will make sense when the user starts from scratch. 

- [ ] Change dropdowns to text fields (frontend)
- [ ] Change routes to return simpler data (backend)

## Has the Feature been Requested Before?
No

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/140378049-333f2205-20c0-44f3-a1fe-7f4005d74345.png)

## Additional context
https://github.com/merico-dev/lake/issues/594

**Comment by e2corporation** [comment]
This is related to #606, both will be addressed on same PR.
