### ISSUE TITLE
Config-UI: When triggering collection, we need to show failures

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#642]
## Description
When I trigger collection...

![Screen Shot 2021-11-05 at 9 25 36 AM](https://user-images.githubusercontent.com/3011407/140509957-bca98237-fb2c-4aa2-bffd-a806f19f06c1.png)

And it fails...

<img width="1767" alt="Screen Shot 2021-11-05 at 9 26 33 AM" src="https://user-images.githubusercontent.com/3011407/140509998-846287fc-2d54-4c67-b927-a25882cfafd8.png">

The UI should notify the user of the failure and attempt to help them fix it.

## Describe the solution you'd like
I want to see a toast message saying that it failed and I want to show the user the error message from the backend.

**Comment by Startrekzky** [comment]
It's already fixed.
