### ISSUE TITLE
The config-ui shows a modal that tells a user to restart the application

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#643]
![Screen Shot 2021-11-05 at 9 29 26 AM](https://user-images.githubusercontent.com/3011407/140510367-789de995-3148-400e-a863-08317f4e8e83.png)

This modal should either appear everywhere or nowhere I think.

What is the desired UI design of this @e2corporation @Startrekzky

**Comment by e2corporation** [comment]
This modal exists from the V1 version of config-ui. I think that dialog styling is fine just needs appropriate dialog title and messaging.

**Comment by Startrekzky** [comment]
I'm with @e2corporation

**Comment by e2corporation** [comment]
<img width="1173" alt="Screen Shot 2021-11-11 at 5 27 58 PM" src="https://user-images.githubusercontent.com/1742233/141378534-43556c97-2981-451d-85fb-d7fc58d5f4a1.png">

**Comment by e2corporation** [comment]
PR #698(Webpack Prod Build) will need to go first before applying this change.
