### ISSUE TITLE
In config-ui, if the user has no .env file, the application fails.

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#646]
## Description
If no .env file exists, it should create one for the user automatically.

This should happen on the backend.

**Comment by joncodo** [comment]
You also can't have a blank .env file or you get this error:

```
2021/11/05 09:47:07 /Users/jonathanodonnell/go/src/github.com/merico-dev/lake/models/init.go:31
[error] failed to initialize database, got error Error 1045: Access denied for user ''@'192.168.16.1' (using password: NO)
ERROR: >>> Mysql failed to connect
panic: Error 1045: Access denied for user ''@'192.168.16.1' (using password: NO)
```

**Comment by joncodo** [comment]
It looks like the .env.example is fine to start with as long as you know the host of (mysql vs localhost) for docker and local running.

**Comment by hezyin** [comment]
@joncodo As confirmed by @klesh, this issue affects neither of our user workflow and teamcode workflow. So this can be closed.
