### ISSUE TITLE
Config-UI: Help Icons for each field

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#649]
## Description
Each field should have a help icon that opens a modal with instructions on how to find the data that you need to populate the fields.

IE: if they need their jira board ID, show them how and where to look for it.

**Comment by e2corporation** [comment]
This was taken out of scope for iter3

**Comment by joncodo** [comment]
I agree. That is why there is no iter3 label on it ;)

**Comment by klesh** [comment]
Not needed anymore
