### ISSUE TITLE
Config-UI: Gitlab: When saving settings of jira board ids it fails

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#652]
## Description
![Screen Shot 2021-11-05 at 9 55 04 AM](https://user-images.githubusercontent.com/3011407/140513541-0864b2ae-17ea-4d0b-bd41-4afc1aae0bca.png)
<img width="1086" alt="Screen Shot 2021-11-05 at 9 55 19 AM" src="https://user-images.githubusercontent.com/3011407/140513552-e6e3ae6e-ae59-45d4-8d6c-41b1fc164fd7.png">

The UI shows it failing but there are no relevant console or network errors when clicking on "Save Settings" at the bottom.

JIRA_BOARD_GITLAB_PROJECTS= also was not set in my .env file

**Comment by e2corporation** [comment]
Kevin and I discussed some changes related to this field yesterday, BE should be receiving the data. Will have to verify again. Isn't `JIRA_BOARD_GITLAB_PROJECTS` BE expects in the request payload?

**Comment by kevin-kline** [comment]
> Kevin and I discussed some changes related to this field yesterday, BE should be receiving the data. Will have to verify again. Isn't `JIRA_BOARD_GITLAB_PROJECTS` BE expects in the request payload?

This is fixed: https://github.com/merico-dev/lake/pull/645
