### ISSUE TITLE
Config-UI: Jira: Add connection does not work

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#654]
## Describe the bug
![Screen Shot 2021-11-05 at 10 04 12 AM](https://user-images.githubusercontent.com/3011407/140514687-2df1034a-8fb3-403f-9c4b-ae9484589d7f.png)

There are no parameters sent down to the backend so nothing gets saved.

**Comment by e2corporation** [comment]
@joncodo This would technically be fixed with my Last PR merged #655. Will verify
