### ISSUE TITLE
Config-UI: Plugin Settings should be handled dynamically?

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#656]
## Question

Right now, the frontend deals with differences between plugins with 'if' conditions or case statements. 

I.E. if (```name == "gitlab") { // do something specific to gitlab }```

As we add more plugins to the system, this can balloon out of control. Should start thinking about some generic settings that the frontend can interpret about plugins so it can dynamically render them accordingly? This is an architecture question.

**Comment by e2corporation** [comment]
@kevin-kline This isn't truly accurate, we have `switch` statements in most places, however certain IF conditions are necessary for this iteration. There is a also main integrations array (integrationsData) defined at the top level which contains our list of available providers so there are already dynamic elements at play. Differences between fields that are not standard would have their own react components. In the case of setting we have settings/jira.jsx settings/gitlab.jsx etc.

In the future as more providers are added we'll adjust the UI accordingly, including any unnecessary IF logic.

**Comment by klesh** [comment]
@e2corporation If I understand this correctly, we can close this? free feel to do so.
