### ISSUE TITLE
Config-UI: Remove "Dashboard" from AppCrumbs component

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#657]
## Describe the bug
Dashboard no longer exists, yet it shows to the user in AppCrumbs. We need to remove it completely.

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/140528756-fc8c7925-cb84-4696-b90b-51a6cea821ca.png)

**Comment by e2corporation** [comment]
I think it's fine for this iteration It routes to the correct destination, Integrations.

**Comment by e2corporation** [comment]
Otherwise it would have to be commented out in the AppCrumbs object configuration across multiple files.

**Comment by e2corporation** [comment]
The breadcrumbs also "collapse" at the first node after drilling down past 3 levels deep.

**Comment by joncodo** [comment]
This links to the default page.
<img width="601" alt="Screen Shot 2021-11-17 at 8 50 11 AM" src="https://user-images.githubusercontent.com/3011407/142203808-02d7897d-67a0-4eea-a008-0444dc2f26f4.png">

Right now, the integrations link and the dashboard link are the same but I think that is ok. Lets leave it and close this.
