### ISSUE TITLE
test connection interface

### ISSUE THREAD

**Issue by mindlesscloud** [merico-dev/lake#667]
## Description
On setting up a new data source, using the test connection button user can verify the configuration.
From the perspective of backend, we define a new interface:

```go
type ConnectionTester interface{
    Connect(ctx context.Context, arg *Arg) (bool, error)
}
```

To check whether `myPlugin` implements `ConnectionTester` at runtime:

```go
_, ok := myPlugin.(ConnectionTester)
```
We could create several atomic interfaces, by composition of them, we got more flexibility.

**Comment by joncodo** [comment]
@mindlesscloud are you working on this? If not, I can do it

**Comment by kevin-kline** [comment]
> @mindlesscloud are you working on this? If not, I can do it

I am.
