### ISSUE TITLE
Jira issue type mapping - use type_name and type_id

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#669]
## Description
We should combine the benefits of the 2 ways to map Jira tool-layer issue type to Domain layer issue type.

id-mapping Benefit: 
- Pros: No need to consider language environment, change of transaction type name.      
- Cons: heavy burden of one-time configuration, duplicate names can occur

name-mapping: 
- Pros: Reduces the task burden for users when there are duplicate transaction types.
- Cons: It is affected by the environment and needs to keep an eye on the setting items for problems and changes (account language environment changes); it is more difficult for the user to locate the problem after it occurs

## Has the Feature been Requested Before?
Please link any other

**Comment by narrowizard** [comment]
Using type_name.
