### ISSUE TITLE
Jira issue type mapping - the default mapping logic should be visible to users

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#670]
## Description
When users are doing Jira issue type mapping, users can map/convert 'Story', 'Task' to the standard issue_type 'Requirement' in the domain layer.
However, if users already have an issue type called 'Requirement' in the tool layer, and they forgot to map this issue type to 'Requirement' in the conifg-UI, the type of these issues will still be 'Requirement' in the domain layer.
Thus, the user can only see 'Story', 'Task' are mapped to 'Requriement', but the actual number of Requirement-type issues in the domain layer is composed of the issues whose tool-layer types are 'Story', 'Task' and 'Requirement'.

## Has the Feature been Requested Before?
Please link any other

**Comment by klesh** [comment]
Use `StatusKey` for mapping now, not a problem anymore
