### ISSUE TITLE
Config-UI: Jira subtitle (connection name) doesn't refresh when saved.

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#680]
## Describe the bug
If you save a new connection name, the connection name doesn't update in the subtitle (or breadcrumb) until you manually refresh.

## To Reproduce
1. Go to http://localhost:4000/connections/configure/jira/1
2. Edit "Connection Name" field
3. Click "Save Connection"
4. See error as described.

## Expected behavior
All fields are refreshed.

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/140806761-34b55aff-7353-4ced-a84b-cd7868840fdf.png)

**Comment by e2corporation** [comment]
Nice find, we need to retrigger a call to `fetchConnection` routine once the save successfully completes so that the `activeConnection` object is refreshed.
