### ISSUE TITLE
Jenkins should send back progress <- 1 when completed.

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#682]
## Describe the bug
When the Jenkins plugin completes all it jobs, it should update the task progress to 1. If it doesn't, the UI won't know when it's done.

## To Reproduce
1. Go to Config-UI triggers page
2. Click on 'Trigger Request' with a JSON object that has a ```{"plugin": "jenkins"}``` object.
3. See that it won't complete.
4. Data in DB shows the status as TASK_COMPLETED and progress as 0.

## Expected behavior
It should complete.

## Screenshots

![image](https://user-images.githubusercontent.com/27032263/140812564-4ab64fcd-73ba-4164-b923-293e82c05913.png)

**Comment by joncodo** [comment]
This is working
