### ISSUE TITLE
Delivery velocity dashboard lacks data

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#689]
## Describe the bug

There're two charts in the delivery velocity dashboard that don't have data.

## To Reproduce
1. Collect data under dev mode
2. Visit the delivery velocity dashboard
3. See there's no data for the following charts
<img width="2463" alt="Screen Shot 2021-11-09 at 12 07 58 AM" src="https://user-images.githubusercontent.com/2908155/140886152-1368c0aa-0776-46df-b356-a7e05f0fb11e.png">

<img width="2459" alt="Screen Shot 2021-11-09 at 12 07 52 AM" src="https://user-images.githubusercontent.com/2908155/140886158-de9d8c06-4c29-4ce3-a073-710be00652b5.png">

**Comment by kevin-kline** [comment]
Please note, it's also important to have the proper type mappings for the source in the DB @hezyin . That completes the fix.

![image](https://user-images.githubusercontent.com/27032263/140940661-667d47f3-fc80-4055-badd-7e86d0963edf.png)

![image](https://user-images.githubusercontent.com/27032263/140940711-a4c9ef05-170f-4e91-95e1-4d94906c1d15.png)

**Comment by joncodo** [comment]
Something like this

```


jira_source_post_full() {
    curl -v -XPOST "$LAKE_ENDPOINT/plugins/jira/sources" --data '
    {
        "name": "test-jira-source",
        "endpoint": "'"$JIRA_ENDPOINT"'",
        "basicAuthEncoded": "'"$JIRA_BASIC_AUTH_ENCODED"'",
        "epicKeyField": "'"$JIRA_ENDPOINT"'",
        "storyPointField": "'"$JIRA_ISSUE_STORYPOINT_FIELD"'",
        "storyPointCoefficient": '$JIRA_ISSUE_STORYPOINT_COEFFICIENT',
        "typeMappings": {
            "Story": {
                "standardType": "Requirement",
                "statusMappings": {
                    "已完成": {
                        "standardStatus": "Resolved"
                    },
                    "已解决": {
                        "standardStatus": "Resolved"
                    }
                }
            },
```
