### ISSUE TITLE
github and gitlab domain layer needs to support type based on labels

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#690]
## Description
"according to the value of issue_labels and issue_creator:
if (issue_lables contain 'bug' or 'Bug') and issue_creator is from Triforce team then 'Bug'
elseif (issue_lables contain 'bug' or 'Bug') and issue_creator is not from Triforce team then 'Incident'
elseif (issue_lables contains 'feat' or 'feature' or 'Feature' or 'Proposal' or 'proposal') then 'Requirement'
elseif (issue_lables contains 'doc' or 'Doc') then 'Documentation'
else 'Other'"

For this, we need to parse labels for each issue and set the issue type.

**Comment by joncodo** [comment]
we also need to support priority

Parse from the value of issue_labels:
if issue_lables like '%highest%' then 'highest'
elseif if issue_lables like '%high%' then 'high'

**Comment by Startrekzky** [comment]
We also need to support `status`

**Comment by joncodo** [comment]
We also need lead time

**Comment by joncodo** [comment]
> and issue_creator is not from Triforce team then 'Incident'

Lets not collect teams now @Startrekzky

**Comment by Startrekzky** [comment]
> > and issue_creator is not from Triforce team then 'Incident'
> 
> Lets not collect teams now @Startrekzky

Sure. We make it as simple as we can.
