### ISSUE TITLE
We need the domain layer to be able to be joined in mysql

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#693]
## Description
For the domain layer to be useful, we will need to join commits to project etc.
![Screen Shot 2021-11-09 at 10 03 55 AM](https://user-images.githubusercontent.com/3011407/140938221-2a6b5ec4-15c7-485a-b9e7-32299fa8704b.png)

**Comment by joncodo** [comment]
These should not be foreign keys but instead be just ids

**Comment by klesh** [comment]
Add a `repo_origin_key` to `commits` , the `repo_id` should not exist.
