### ISSUE TITLE
Is it possible to inject a custom Dashboard URL?

### ISSUE THREAD

**Issue by ZhenhangTung** [merico-dev/lake#708]
## Question
Is it possible to inject a custom Dashboard URL?

## Screenshots
![image](https://user-images.githubusercontent.com/8170159/141214657-948659e0-4bbf-4e0c-a3d3-50e4eb2dcc42.png)

## Additional context
The URL pattern of TeamCode's TIN application is `xxx-4000.xxx.teamcode.com` instead of `xxx.xxx.teamcode.com:4000`, so the user cannot be redirected to Grafana by using `location.hostname:4000` in JS.

**Comment by klesh** [comment]
Working on it
