### ISSUE TITLE
We need worklog entity in issue managemenet domain layer schema

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#710]
## Description
We need worklog records for issues to calculate some indicators. With following columns:
- issue_id
- author_id: who created the worklog
- comment
- start_time
- time_spent: eg: 4h
- time_spent_seconds: eg: 14400
- update_author_id: who updated the worklog
- update_time

## Question
I am not sure what `update_author_id` and `update_time` means, it's from jira api and all items I can find is with same value of `author_id` and `update_author_id`.  
Also, column name is not matter, you can change it as your mind. @Startrekzky

**Comment by mindlesscloud** [comment]
Do we really need the `comment` column? It is a 3D array by the [documents of Jira API](https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/#api-agile-1-0-board-boardid-issue-get)

**Comment by narrowizard** [comment]
Closed by #852
