### ISSUE TITLE
`config-ui` layout seems off when built into docker image

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#712]
## Describe the bug
![image](https://user-images.githubusercontent.com/61080/141298887-3f3c065c-b7b2-4cb6-bef0-bd1252053ffc.png)

## To Reproduce
1. build config-ui docker image
2. launch config-ui by `docker-compose`
3. open in browser

## Expected behavior
![image](https://user-images.githubusercontent.com/61080/141298969-c76abb84-350c-48c7-bb49-887a8f65fad4.png)

**Comment by e2corporation** [comment]
Config-UI's Build Process is being updated & tested, this will be resolved with #660
