### ISSUE TITLE
Config UI - JIRA / Story Point Coefficient NaN Condition

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#717]
## Describe the bug
The  **Story Point Coefficient** settings field for the **JIRA** Provider would prefer numeric values, and needs to default to 0 otherwise. The onChange handler logic for this field needs to be updated to prevent a `NaN` scenario. This is not a critical issue, but does impact usability for the **Story Point Coefficient**  field.

## To Reproduce
1. Edit an existing JIRA Connection Source
2. Click on **Settings** action link
3. Scroll down to **Story Point Coefficient** field
4. Type a letter such as "a"
5. Notice on Keyup "NaN" appears in field

## Expected behavior
Only numeric values are allowed for this field and it should default to 0. The useState property associated with this field property should also initialize to 0 when defined, and the logic in the onChange handler needs to be reduced.

## Screenshots

<img width="1045" alt="Screen Shot 2021-11-11 at 3 55 56 PM" src="https://user-images.githubusercontent.com/1742233/141368351-a0f1ef40-3afb-4e6c-92c2-4e004e547fac.png">

**Comment by e2corporation** [comment]
@joncodo This one needs assignment for this iteration `iter4` or the next after release.

**Comment by Startrekzky** [comment]
I'll redesign 'coefficient' logic.

**Comment by joncodo** [comment]
## Assumptions

1. We should default this to 1 since if it is 0 and is used by the code, all values will be zero since the code does something like this: `storyPoints = storyPointsFromJira * storyPointCoefficient`
2. I thought that @Startrekzky wanted to get rid of this field since no customer is asking for it at this time. 

I think this feature is too niche and will not be used. It will only confuse the end user. I suggest we remove it from the codebase unless EE really needs it.

**Comment by Startrekzky** [comment]
> ## Assumptions
> 1. We should default this to 1 since if it is 0 and is used by the code, all values will be zero since the code does something like this: `storyPoints = storyPointsFromJira * storyPointCoefficient`
> 2. I thought that @Startrekzky wanted to get rid of this field since no customer is asking for it at this time.
> 
> I think this feature is too niche and will not be used. It will only confuse the end user. I suggest we remove it from the codebase unless EE really needs it.

My suggestion is to get rid of this key/field as it has been removed from the domain layer according to this document https://merico.feishu.cn/docs/doccn6ZyxRzUgKMFXzWTwzcWH7f
