### ISSUE TITLE
Config UI - Integrations / Connections Management Table

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#718]
## Describe the bug
It would be nice to have **client-side table pagination** on the list of connection sources available for a provider. Reference Blueprint CSS docs to see if there are native components that are best-suited as a basis for this task. Assuming a user has more than 10-15 Instance connections, this would be necessary for better management.

https://blueprintjs.com/docs

- [ ] Leverage the Blueprint JS **Button Group** Core Module to create a simple pagination widget for the Table.
    -  https://blueprintjs.com/docs/#core/components/button-group

**Comment by klesh** [comment]
It's unlikely user would have this many connections, especially for same kind of platform.
I suggest we do this later.

**Comment by Startrekzky** [comment]
It's unlikely a user would have this many connections, we can do it later.
