### ISSUE TITLE
Add a field 'title' to 'issues' table

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#723]
## Description
To display bug details properly

## Describe the solution you'd like

- [x] Add title to 'issues' table
- [ ] Add a column 'title' in the table below, this table is in dashboar 'BugDetailedInfo'
![image](https://user-images.githubusercontent.com/14050754/141409206-1b31b713-cca8-4d52-933e-aa11e74602f7.png)

**Comment by joncodo** [comment]
![Screen Shot 2021-11-12 at 9 30 39 AM](https://user-images.githubusercontent.com/3011407/141474990-948149c9-5f84-4498-817d-279ad4cba9d9.png)
