### ISSUE TITLE
Check Github's issue status conversion logic

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#724]
## Question
Please check issue statuses in domain layer. I’m not sure if github_issue_status has been transformed as: 'open' -> 'Todo', 'closed' -> 'Resolved'.
This may affect the demo dashboard SQL.

**Comment by joncodo** [comment]
I'm not sure what this means. Do you I think we no longer need issue status?

**Comment by Startrekzky** [comment]
We have to standardize issue statuses in domain layer.
