### ISSUE TITLE
No Restart needed after saving configuration

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#728]
## Description
Before this iteration, all configuration were wrote into .env file and load by `docker-compose` during container creation. Now that we had all our plugin configuration go through devlake api, even though some settings are still being stored into `.env` file, but restart is not required anymore at least for plugin configuration.

Other settings like `DB_URI/HOST/PORT` are still needed  to be loaded during container creation. But these settings are not suppose to be changed by `config-ui` at the first place. `HOST/PORT` are non-business-related, changing them most likely will break `config-ui` make it unable to connect to devlake anymore. and the `DB_URI` would break `devlake` itself, the only way to restore the system is to modify `.env` file by hand, which is more of a devops operation. So, we can safely assume that devops guys should be the one care about these basic settings. and they will operate out of `config-ui` scope. and our real users would care only the plugin configuration or business related settings. Thus, these non-business-related settings **SHOULD BE REMOVED** from `config-ui`

## Describe the solution you'd like
1. Remove `DB_URI/HOST/PORT` from `config-ui`
2. Make sure all plugins read the latest settings posted via api
3. Remove all restart confirmation dialog from `config-ui`

## Has the Feature been Requested Before?
No

@e2corporation @joncodo @kevin-kline  Post your thoughts, and we might do it on next iter

**Comment by e2corporation** [comment]
This ticket may no longer be needed after commit ID `bef1117a: feat: remove apiconfiguration side nav for now`. The restart dialog would be repurposed for a later time. Please confirm @klesh @joncodo
