### ISSUE TITLE
Nginx proxy layer for grafana

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#731]
## Description

@klesh please update this ticket

**Comment by klesh** [comment]
grafana doesn't need a proxy, redirection is a more appropriate.
Should be covered by https://github.com/merico-dev/lake/pull/730
I tested it and it worked on docker-compose mode. 

maybe we could setup a `webpack-mock-server` to do the redirection for dev mode.
@e2corporation Would you like to work on that or I can set it up. Let me know.
