### ISSUE TITLE
Github issues don't have type

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#736]
## Describe the bug
Github issues' type field is empty. Is there something wrong with the tag parsing logic?

![L8onEXpwnV](https://user-images.githubusercontent.com/14050754/141476222-2750dc19-e3d7-4bda-8ce5-97c250f628ed.png)

![ExH3E86HS0](https://user-images.githubusercontent.com/14050754/141476404-b6f63559-14de-4233-9ace-69678045454e.png)

**Comment by kevin-kline** [comment]
Plan of attack:
1. Verify data on my machine
2. Unit test parsing logic
3. Inquire about differences in our setup with @Startrekzky (if my end is working)

**Comment by joncodo** [comment]
Linked to #690

**Comment by kevin-kline** [comment]
@Startrekzky 
I verified the data on my machine. Here's an example of one that you posted:

![image](https://user-images.githubusercontent.com/27032263/141481879-c16bd42b-5515-496b-97c8-d474a7bee7b2.png)

It's essential to let the issue collector run fully to get the label associations. This means the "CollectChildrenOnIssues" method needs to run and collect each issue individually. When that is done, it appears this works on my machine.

![image](https://user-images.githubusercontent.com/27032263/141482311-fde4e571-2689-426b-b926-2246eed2396e.png)
