### ISSUE TITLE
Nginx is not working for me locally

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#745]
Even with a local .env file, I am still seeing this problem

DEVLAKE_ENDPOINT=localhost:8080
GRAFANA_ENDPOINT=http://localhost:3002
![Screen Shot 2021-11-12 at 3 59 51 PM](https://user-images.githubusercontent.com/3011407/141527472-8c6f6660-b12a-49a8-bdfb-d810f6a95160.png)

**Comment by klesh** [comment]
Unable to reproduce. nginx is part of `config-ui` image, and should be verified using User Setup Process. I suggest you follow these step to verify:

1. docker pull mericodev/devlake
2. docker pull mericodev/lake
3. git checkout config-ui-githubproxy       # this branch fixed other docker-compose issues, didn't modify `nginx.conf`
4. backup your `.env` and cp `.env.exmple` to `.env`
5. docker-compose up -d
6. access `http://localhost:4000`, all api should be proxied to `devlake` correctly.

**Comment by joncodo** [comment]
What is this? docker pull mericodev/devlake
![Screen Shot 2021-11-14 at 12 37 52 PM](https://user-images.githubusercontent.com/3011407/141689856-44326ea7-1cf1-4fd6-a25b-d91df4ea913f.png)

I only see these

**Comment by klesh** [comment]
@joncodo mericode/lake it is then

**Comment by joncodo** [comment]
This is now working for me. Once I merged your latest pr:

```
    volumes:
      - ./.env:/app/.env
```

https://github.com/merico-dev/lake/pull/748/files
