### ISSUE TITLE
Refactor: use `npm` package instead of including 3rd party resources in our codebase directly

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#749]
## Description
Now we put all cdn fonts/css files into our repo directly, it solved the problem we are facing, and ok for now.
But it's also not a very good practice, because these are not really our product.

## Describe the solution you'd like
Use these resources by `npm` packages:
- https://www.npmjs.com/package/typeface-montserrat
- https://www.npmjs.com/package/jetbrains-mono

## Has the Feature been Requested Before?
No

**Comment by e2corporation** [comment]
@klesh These are open-source typefaces available for both personal and commercial use.

**Comment by e2corporation** [comment]
@klesh If there is a possibility of using them as npm packages we can look into that, however they would need to get bundled and used correctly with the imports and the build process adjusted. No harm in localizing them however.

**Comment by klesh** [comment]
> @klesh If there is a possibility of using them as npm packages we can look into that, however they would need to get bundled and used correctly with the imports and the build process adjusted. No harm in localizing them however.

@e2corporation There is a plan to analyze devlake repo on AE in the future, and AE has this opensource code copying checking feature. Chances are those cdn resources would be recognized as cheating behavious toward DevEq...

**Comment by joncodo** [comment]
@klesh can you tell me the business value of this ticket? What problem does this solve? Looking for more clarity on priority.

**Comment by joncodo** [comment]
What refactor problem does this solve?

**Comment by joncodo** [comment]
I agree with you. I get now what you meant.

**Comment by e2corporation** [comment]
Move to `next` sprint
