### ISSUE TITLE
Corrections to User Setup in Readme

### ISSUE THREAD

**Issue by ggcannard** [merico-dev/lake#750]
## Documentation Scope
The main README

## Describe the Change
Update the User Setup steps. Currently, a couple steps are not correct:
* It suggests to bring up config-ui on its own, rather than the entire docker-compose. This causes config-ui to crash.
* The button `Go to Grafana` no longer has this name. It has been changed to `View Dashboards`

**Comment by joncodo** [comment]
Fixed and merged
