### ISSUE TITLE
We need to update the github readme to tell users how to get their tokens

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#751]
- Get personal access tokens
- Screenshots etc

**Comment by joncodo** [comment]
The main readme page needs a link in our plugins table:
![Screen Shot 2021-11-14 at 1 47 58 PM](https://user-images.githubusercontent.com/3011407/141692321-d7d9a7af-9c6f-415b-91ff-b1701fc5d0ee.png)

**Comment by hezyin** [comment]
This is now tracked in a new ticket: https://github.com/merico-dev/lake/issues/777
