### ISSUE TITLE
Change styling in config-UI's trigger collection page.

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#767]
## Description
1. Links to [how to use the trigger](https://github.com/merico-dev/lake/wiki/How-to-use-the-triggers-page) wiki in config-UI's trigger collection page is not clear.

2. The description above is not clear enough. 

## Proposed solution
1. Links to `how to use the trigger` should be highlighted
![image](https://user-images.githubusercontent.com/14050754/141794687-108d4823-d6f7-425d-b10b-eb88643f75d3.png)

2. The description above should be updated to :
   Create a http request to trigger data collect tasks, please replace your gitlab projectId and jira boardId in the request body. This can take up to 20 minutes for large projects. (Gitlab 10k+ commits or Jira 5k+ issues)

   There are two types of plugins in our application, corresponding to the 2 lists in the following json.
   The regular plugins collect and enrich data (the 1st list) while the domain layer plugins (the 2nd list) prepare the data for the graphs in Grafana dashboards. You **SHOULD ONLY** have to edit the regular plugins. Editing domain layer plugins is for advanced usage only. Detailed configuration guide: [How to use the triggers page](https://github.com/merico-dev/lake/wiki/How-to-use-the-triggers-page)

**Comment by e2corporation** [comment]
Recommended font styling for the "Full documentation" link:

```
                  <p className='description' style={{ fontSize: '13px' }}>
                    <span style={{ fontWeight: 'bold' }}>Full documentation here:</span>&nbsp;
                    <a href='https://github.com/merico-dev/lake/wiki/How-to-use-the-triggers-page' target='_blank' rel='noreferrer'>
                      How to use the Triggers Page
                    </a>
                  </p>
```

**Comment by e2corporation** [comment]
'Jira' should also be written as 'JIRA'
