### ISSUE TITLE
prebuilt dashboards for grafana won't get updated on existing deployment

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#770]
## Describe the bug
Seems like grafana would copy our prebuilt dashboards into its storage on initialization only, so, whenever we update our dashboards, they don't get push into user's existing deployment.
This is problematic for long term users, we have to figure out a solution to solve this.

## To Reproduce
1. setup a deployment by docker-compose
2. update any dashboard
3. rebuild grafana docker image
4. restart docker-compose by `docker-compose up -d`
5. dashboards stay unchanged on grafana

## Expected behavior
User should see the updated dashboards

**Comment by Startrekzky** [comment]
to be further investigated

**Comment by klesh** [comment]
1. Start up `docker-compose`
```sh
[klesh@klesh-laptop] ~/P/m/lake (main|✔ )> docker-compose up -d                                                                                         4.373slake_mysql_1 is up-to-date
Creating lake_grafana_1 ... done
Creating lake_devlake_1 ... done
Creating lake_config-ui_1 ... done
```
2. Pick one dashboard from `grafana`
![image](https://user-images.githubusercontent.com/61080/143840348-662cd086-608e-4cab-b8c4-9944f454491a.png)
3. Make change to this dashboard:
    a. change dashboard title
    b. change date format for the chart from `%M %Y to `%Y %M`
```
M grafana/dashboards/DemoHowFastDoWeRespondToCustomerRequirements.json
@@ -108,7 +108,7 @@
           "group": [],
           "metricColumn": "none",
           "rawQuery": true,
-          "rawSql": "with _requirements as(\n  select \n    DATE_ADD(date(resolution_date), INTERVAL -DAY(date(resolution_date))+1 DAY) as time,\n    avg(lead_time_minutes)/1440 as lead_time_days\n  from issues i\n  where \n    type = 'Requirement'\n    and $__timeFilter(resolution_date)\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  lead_time_days as 'Average Requirement Lead Time (day)'\nfrom _requirements\norder by time asc",
+          "rawSql": "with _requirements as(\n  select \n    DATE_ADD(date(resolution_date), INTERVAL -DAY(date(resolution_date))+1 DAY) as time,\n    avg(lead_time_minutes)/1440 as lead_time_days\n  from issues i\n  where \n    type = 'Requirement'\n    and $__timeFilter(resolution_date)\n  group by time\n)\n\nselect\n  date_format(time,'%Y %M') as month,\n  lead_time_days as 'Average Requirement Lead Time (day)'\nfrom _requirements\norder by time asc",
           "refId": "A",
           "select": [
             [
@@ -195,7 +195,7 @@
   },
   "timepicker": {},
   "timezone": "",
-  "title": "Demo-How fast do we respond to customer requirements?",
+  "title": "Demo-FOFO",
```
4. build `grafana` image with latest tag
```
cd grafana
docker build -t mericodev/grafana:latest .
```
5. update `docker-compose` to use latest image
```
sed -i 's|mericodev/grafana:0.4.0|mericodev/grafana:latest|' docker-compose.yml 
docker-compose up -d
```
6. observe dashboard
![image](https://user-images.githubusercontent.com/61080/143845613-0cb5987d-9fa6-480c-8cc3-b3731ef99328.png)
7. modify dashboard on grafana
![image](https://user-images.githubusercontent.com/61080/143845808-3cba157c-7639-4dd4-b839-83b14a51840f.png)
8. modify dashboard on repo: **mimicing devlake updation**
    a. change DATE FORMAT to `%Y %m` (month in numberic)
    b. change title to "Demo-FOOBAR"
9. rebuild `grafana` image and restart `grafana` service
```
cd grafana
docker build -t mericodev/grafana:latest .
docker-compose up -d
```
![image](https://user-images.githubusercontent.com/61080/143846463-9eafd1b6-f571-4389-8e68-1da8f231597e.png)
**Dashboard got updated to latest devlake ones**

**Comment by klesh** [comment]
Conclusion:
Dashboards are always update to date as devlake ones. Works as we want they to be.
