### ISSUE TITLE
"How To Debug" document

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#773]
## Documentation Scope
A New User encountered issues setting up Dev Lake, and was unable to debug the issues effectively. 

## Describe the Change
We should consider how we can help a New User debug issues when they arise. They may need some examples and screenshots of where to see some logs.

**Comment by hezyin** [comment]
@kevin-kline This is a good idea but is a bit too general. Let's instead create more concrete sub tickets to implement this idea.
