### ISSUE TITLE
Github API Plugin Source: Proxy URL missing in API JSON Response

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#783]
## Describe the bug
GitHub setting page where BE is not returning the saved GitHub Proxy URL value in api response, this was a newly added field to GitHub provider settings.

- [ ] BE needs to update endpoint `/api/plugins/github/sources/1`
   - PROXY field is missing from response
- [ ] Config UI - GitHub Settings JSX API field needs verification (see below)
 
## To Reproduce
1. Go to Data Integrations > GitHub > Settings
2. Enter a Proxy URL Value and Save
3. Notice URL is sent in the Request payload as expected if headers are inspected.
4. Reload the page
5. Notice Proxy URL field is **blank** because the fetch endpoint for the plugin source does not include the proxy field.

## Expected behavior
Include the `GITHUB_PROXY` field in the API Response for the Gitlab Plugin Source.
`http://localhost:4000/api/plugins/github/sources/1`

```
{
  "Endpoint": "https://api.github.com/",
  "Auth": "***",
  "Name": "Github",
  "ID": 1,
  // GITHUB_PROXY MISSING HERE (config UI set to read "connection.proxy")
 // "proxy": [PROXY_URL_HERE]
}
```

**Config UI (GITHUB Settings JSX)**
   // This line needs to update to set the appropriate key from API response.

```
# settings/github.jsx
.....
  useEffect(() => {
    // ***** Change this Line to Match API Response ****
    setGithubProxy(connection.proxy)
  }, [connection])

```

## Screenshots
(Before Save Configuration)
<img width="1100" alt="Screen Shot 2021-11-15 at 1 39 08 PM" src="https://user-images.githubusercontent.com/1742233/141836968-ee6b0ac1-1689-4605-b6de-fafdf1e1bc8f.png">
(After Save Configuration & Reload)
<img width="1101" alt="Screen Shot 2021-11-15 at 1 39 21 PM" src="https://user-images.githubusercontent.com/1742233/141836965-b626370e-a7d5-437d-87ac-8502485b7a9e.png">

## Additional context
When adding new settings fields for a Data Provider, please test both Add and Modify states to ensure data consistency.

**Comment by klesh** [comment]
![image](https://user-images.githubusercontent.com/61080/141877550-e9018f38-0dec-4806-8c24-048be54a94d6.png)

I'm having hard time to reproduce your problem, how did you start up the BE? by docker or by `make dev`?

If it was docker, try repulll the backend image and retstart the container.

@e2corporation

**Comment by klesh** [comment]
unable to reproduce, close for now, feel free to reopen @e2corporation
