### ISSUE TITLE
"Getting Started" Wizard

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#787]
## Description
When a New User starts Dev Lake, it is too confusing. They do not know how to set it up, because it's very complicated.

## Describe the solution you'd like
When a New User starts Dev Lake, they need a wizard to take them through the setup flow so that they understand how Dev Lake is set up. They should be taken from Zero understanding to Beginner level understanding. Some ideas:
- "Why" section
- Example Repo to collect data from and see data

## Has the Feature been Requested Before?
No.

## Describe alternatives you've considered
More documentation is not good enough. They should be guided step by step.

**Comment by klesh** [comment]
Will be addressed by #1862
