### ISSUE TITLE
"Docs" Folder

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#788]
## Documentation Scope
Docs are scattered throughout the application. One new user reports this is difficult to navigate.

## Describe the Change
We could have a "Docs" folder to make it easier to find docs.

**Comment by klesh** [comment]
It makes sense to place docs of plugin inside the  plugin's own folder.
Maybe we could use some tool or write some scripts to pull all those docs together and generate a github pages website for document

**Comment by klesh** [comment]
All documentation will be addressed by official website in the future, not a problem anymore
