### ISSUE TITLE
Progress Details with higher granularity

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#789]
## Description
Currently, our progress updates from tasks is very low resolution and doesn't provide very much information.

## Describe the solution you'd like
We should improve progress updates by giving users more specific messages about what their plugin is doing, and some numerical idea about how far along it is in the process.

Each plugin handles their own progress, so this task requires improvement for each plugin:

- [ ] Jira #479 
- [ ] GitLab #813 
- [ ] GitHub #814 
- [ ] Jenkins #815 

## Has the Feature been Requested Before?
No.

**Comment by joncodo** [comment]
Links to this: https://github.com/merico-dev/lake/issues/479

**Comment by kevin-kline** [comment]
@joncodo Hey, can you weigh in on the priority of which plugins need this feature?

**Comment by kevin-kline** [comment]
This issue has been re-defined due to complications here: https://github.com/merico-dev/lake/issues/822
