### ISSUE TITLE
YouTube Series

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#790]
## Description
User Feedback suggests that some people will not try a new technology unless they are able to see a YouTube walkthrough to help them understand and use the technology.

## Describe the solution you'd like
We should make a series of YouTube videos that explain the "Why" of Dev Lake, and some tutorials on how to set it up from scratch to complete functionality.

## Has the Feature been Requested Before?
Maybe?

**Comment by joncodo** [comment]
Closing for now
