### ISSUE TITLE
Usability: Tracking Ticket

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#791]
## Description
This is a tracking ticket for the following issues related to Usability. These ideas were gathered through New User feedback. All are open to discussion!

- Test Connection button: https://github.com/merico-dev/lake/issues/595
- How to Debug doc: #773 
- Populate "Triggers" JSON dynamically #774 
- Cancelling tasks: #775 
- Absolute Links: #786 
- "Getting Started" Wizard: #787 
- "Docs" folder: #788 
- Better progress details: #789 
- YouTube Series: #790

**Comment by joncodo** [comment]
I think this ticket is so important to our success.
