### ISSUE TITLE
Investigate how we can use scarf to better understand user geographics

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#793]
## Description

https://about.scarf.sh/scarf-gateway

We're mostly concerned with scarf-gateway to know which companies are pulling our docker images.

Success criteria: 
deliver a document that includes
- [ ] what info/stats can we get from Scarf, seeing if we can get the info of the companies that are pulling our docker images.
- [ ] how to implement Scarf

## History 

- jinglei found scarf and liked that it tells them which company uses our software
- The motivation is to track the companies

## JONS NOTES

https://scarf.sh/gateway/joncodo/docker/mericodev%2Fconfig-ui

### What we can get from scarf

1. We can get regions or countries. We can get user operating system. I have not been able to get companies yet for Merico employees but we might be able to get larger companies since it looks up based on IP.
2. To implement scarf, it is very easy and fast. All we have to do is register our docker image in the scarf gateway. This means we have to have users do `docker pull joncodo.docker.scarf.sh/mericodev/config-ui`

### Concerns

The only problem I have with this is the security aspect. I think users will not know the scarf domain and will be concerned as to what they are pulling. I also think that it puts our user's security in the hands of scarf. If something goes wrong there, all our users could download viruses or fail to get our image. 

I recommend we do not do this since the value of the company list is not enough for the security risk and the risk of losing user adoption based on pulling from an non verified source.

**Comment by Startrekzky** [comment]
Research first

**Comment by joncodo** [comment]
<img width="838" alt="Screen Shot 2021-12-07 at 10 56 46 AM" src="https://user-images.githubusercontent.com/3011407/145052399-9827b680-6d6c-4e72-971b-429a3a6bcd72.png">

**Comment by joncodo** [comment]
<img width="733" alt="Screen Shot 2021-12-07 at 11 01 12 AM" src="https://user-images.githubusercontent.com/3011407/145053229-0c276152-ffb0-4bfc-8033-2a1bea10dcae.png">

**Comment by joncodo** [comment]
<img width="325" alt="Screen Shot 2021-12-07 at 11 01 49 AM" src="https://user-images.githubusercontent.com/3011407/145053355-8643f4f9-511f-4eb5-b3f0-d22ca28742d3.png">

**Comment by joncodo** [comment]
<img width="1377" alt="Screen Shot 2021-12-07 at 11 02 33 AM" src="https://user-images.githubusercontent.com/3011407/145053471-22acb6d0-f94c-4737-a83b-7725cbb91e67.png">

**Comment by joncodo** [comment]
https://img.shields.io/badge/Scarf:%20Downloads-4/month-green?style=for-the-badge&color=7ACCE8&labelColor=00304A

**Comment by joncodo** [comment]
<img width="1110" alt="Screen Shot 2021-12-07 at 11 11 07 AM" src="https://user-images.githubusercontent.com/3011407/145054894-9d3547e4-41e6-49f3-ba92-c18f41569593.png">

**Comment by joncodo** [comment]
Latency from all over China
<img width="916" alt="Screen Shot 2021-12-07 at 11 19 45 AM" src="https://user-images.githubusercontent.com/3011407/145056369-50d5d4dc-ddc5-4dd2-8063-089e5f097854.png">

**Comment by joncodo** [comment]
https://github.com/scarf-sh/scarf/issues/28

**Comment by joncodo** [comment]
<img width="561" alt="Screen Shot 2021-12-07 at 11 24 15 AM" src="https://user-images.githubusercontent.com/3011407/145057137-9baf3e77-5598-42b2-b4c0-fce46741af80.png">

**Comment by joncodo** [comment]
My hosted image: https://scarf.sh/gateway/joncodo/docker/mericodev%2Fconfig-ui

You can pull with:  docker pull joncodo.docker.scarf.sh/mericodev/config-ui

**Comment by aviaviavi** [comment]
👋   Avi from Scarf here - It's great to see these latency benchmarks, thank you for posting them. We are continually expanding our global data center footprint so your containers will be available quickly, around the world. It looks like we need to improve in central China, which is very doable for us by deploying to new regions. I can keep you posted on that progress. Does this current latency block you from continuing to adopt Scarf for Merico?

If there are any other questions I can answer as you get started, I'm happy to help in any way I can.

**Comment by joncodo** [comment]
It does not block us to use scarf at this time. I will continue to keep you updated as we move forward. @MaximDub can you put me in touch with @aviaviavi via email in the future for more private chats?

**Comment by aviaviavi** [comment]
Just want to drop my response to this here: https://github.com/scarf-sh/scarf/issues/29#issuecomment-989006948. We should be able to adequately address these concerns, happy to chat about it further
