### ISSUE TITLE
`config-ui` reporting 503 before devlake ready

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#799]
## Description
`devlake` takes longer to boot up, and `config-ui` get ready almost instantly. User would get 503 errors before `devlake` ready when trying to set system up on `config-ui`.
It would be a plus if we can solve this issue before release.

## Describe the solution you'd like
1. Tweak `docker-compose` to start `config-ui` only when `devlake` is ready(in sense of truly ready for requests), not sure if doable
2. Display a WATING DEVLAKE BOOT UP screen before actually showing `config-ui` screen, and keep probing the devlake port, for maximum like 1min or so. Display  a failure message when timeouted.

## Has the Feature been Requested Before?
No

**Comment by hezyin** [comment]
@e2corporation Please prioritize designing the trigger and pipeline pages before this ticket as many other tickets depend on that two pages.
