### ISSUE TITLE
macOS - DevLake `ERROR`: >>> Mysql failed to connect

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#800]
## Lake / Docker / Mac OS + MySQL
Users / Developers in a Mac OS Environment are unable to start **Lake** with `docker-compose up` due to a bad MySQL TCP Connection string. To resolve this issue for Mac OS and potentially other environments, please see the steps below.

**SOLUTION STEPS** 
- [ ] **Update MySQL Docker Configuration** in `docker-compose.yml` SET `container_name`
  - Define a **CONTAINER NAME** For the MySQL Instance eg. `container_name: lakeMYSQL`
- [ ] **Update Dev Lake's DB_URL Connection String** to use _Container Name_ and NOT _localhost_ 
  - `DB_URL=merico:merico@tcp(lakeMYSQL:3306)/lake?charset=utf8mb4&parseTime=True`

<img width="774" alt="Screen Shot 2021-11-16 at 10 47 11 AM" src="https://user-images.githubusercontent.com/1742233/142018169-f3724e34-8cb4-44e0-bfea-3b52ba1135a3.png">

## To Reproduce
1. Go to **DevLake** project folder (`lake`) running `main` branch
2. Run `docker-compose up` to start services
3. Notice the Go Init Model fails to connect `/app/models/init.go:31`
4. DevLake Issues **Panic Error** and exits with Code 2

## Expected behavior
DevLake should startup successfully and connect to the MySQL Service instance when running `docker-compose up` instead of throwing panic errors.

## Screenshots

**BEFORE** 
<img width="787" alt="Screen Shot 2021-11-16 at 10 20 49 AM" src="https://user-images.githubusercontent.com/1742233/142017359-2c057ea2-38f9-456b-b84b-38624ee7cc3c.png">

**AFTER PROPOSED SOLUTION**
<img width="787" alt="Screen Shot 2021-11-16 at 10 32 47 AM" src="https://user-images.githubusercontent.com/1742233/142017388-9e425ba5-1a64-4e64-90bb-3e9ff0c57f98.png">

## Additional context
Please see a similar issue below on StackOverflow for addtional context with regard to **Go** and **Docker**.
https://stackoverflow.com/questions/52504318/unable-to-connect-to-mysql-server-with-go-and-docker-dial-tcp-127-0-0-13306

**Comment by e2corporation** [comment]
```
macOS Catalina 10.15.7 (19H2)
Docker version 20.10.8, build 3967b7d
go version go1.16.5 darwin/amd64
```

**Comment by e2corporation** [comment]
This may be specific to my env, will close if it is an isolated incident or due to bad docker cache.

**Comment by kevin-kline** [comment]
> This may be specific to my env, will close if it is an isolated incident or due to bad docker cache.

To add to this discussion, I verified the "User Setup" flow on my machine (as described in our main README). I'm on an M1 Mac, and I do not run into this error. Maybe we can close this one on that basis.

**Comment by klesh** [comment]
@e2corporation Would you like to try pinging `mysql` on your host machine?
