### ISSUE TITLE
Upgrade for Existing users/DB migrations for existing data

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#806]
## Description
Now we dont actually support upgrade devlake to newer version at this point, things like data schema change would cause devlake not working properly, and grafana dashboards may not updated after first initialization(to be verified), we need to support upgrade to newer version for deployed instance. 

1. Establish a mechanism to ensure user can migrate database for deployed instance during upgrade operation
2. Make sure user can get latest dashboards on deployed instance when user chose to upgrade

## Describe the solution you'd like

Solutions are to be consider, we need to investigate the situation futher more. like:
1. How is `gorm`s `AutoMigrate` behave, what is the limitation
2. Does `grafana` copys prebuilt dashboards on `initialization` and never again? 

## Has the Feature been Requested Before?
No

## Additional context
@runjinz was unable to upgrade his deployed instance while keeping all his data. had to delete tables and re-sync everything.

**Comment by joncodo** [comment]
?

**Comment by klesh** [comment]
@joncodo  issue detail is filled.

**Comment by joncodo** [comment]
You have to use Migration from Gorm. https://gorm.io/docs/migration.html

**Comment by klesh** [comment]
We should try this feature next time we have to do some breaking migration, set up an example of how to do so.

**Comment by joncodo** [comment]
@mindlesscloud I am going to take this ticket. Hopefully that is ok with you

**Comment by joncodo** [comment]
# PLAN OF ATTACK


We need tests to make sure we can insert every model type as of now
We need to migrate from scratch
All migrations should be done with SQL
All test should still pass after refactor
Tests will help to document the data model to our users

**Comment by joncodo** [comment]
To investigate: https://sqitch.org/

**Comment by joncodo** [comment]
Currently running into this problem: https://github.com/golang-migrate/migrate/issues/282

**Comment by joncodo** [comment]
PR ready

**Comment by joncodo** [comment]
## Questions to solve

1. How do we force the tests to use the test DB? - Use a flag for TEST in the init method
2. How do users auto run the migration scripts on each run of the service?
3. Have we tested this new DB from a new user perspective from docker-compose?
4. How do we run these tests in CI? - Prevent the models tests in CI. Only run them locally for now
5. How do we remove the auto migrate lines and make the migrations run against lake for CI and docker-compose and local dev?
6. How do plugins run migrations?

**Comment by joncodo** [comment]
Closing in favour of https://github.com/merico-dev/lake/issues/979
