### ISSUE TITLE
config-UI test connection hook up

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#807]
## Description
What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

## Has the Feature been Requested Before?
[Please link any other](https://github.com/merico-dev/lake/issues/667)

**Comment by hezyin** [comment]
This is waiting for #667, cc @joncodo

**Comment by kevin-kline** [comment]
closed by #841
