### ISSUE TITLE
Config UI - Production Build NGINX Layer not serving FONT and other assets

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#823]
## Config UI / Docker / NGINX / FONTS Not served

When running the "built" **Production Mode** of **Config UI**, the distributed bundle is served by **NGINX** however the `/font/` directory is not mapped and/or publicly accessible so the appropriate font styling is not applied resulting in browser defaults of "sans-serif" and "serif" being used. Requests to the `ttf` and `woff` font files fail resulting in warnings by the browser.

- [ ] Verify that **Dockerfile** copies entire `dist/` folder including subdirectories.
   - COPY `dist/*` (note the asterisk) may exclude subdirectories.
- [ ] Update **NGINX** Configuration move ROOT Declaration to server scope
  - Fix `root` location declaration
  - Configuring MIME Types may be required
- [ ] Test Production mode to ensure fonts are properly served and not index.html
- [ ] **OPTIONAL** Add 404 Page directive to NGINX

_Note the font appearance in the Sidebar and main application in the screenshots below._

**DEVELOPMENT** MODE (Correct Font Loading)
<img width="1161" alt="Screen Shot 2021-11-18 at 10 19 47 AM" src="https://user-images.githubusercontent.com/1742233/142443898-8d027d1e-9c86-482c-988e-92668cc9522c.png">

**PROD** MODE w/ **Docker** (Missing Fonts)
<img width="1161" alt="Screen Shot 2021-11-18 at 10 21 37 AM" src="https://user-images.githubusercontent.com/1742233/142443940-241e9954-70db-4b63-9959-873117d0d326.png">

**Comment by klesh** [comment]
@e2corporation can we close this?

**Comment by e2corporation** [comment]
@klesh No this is a valid issue that needs to be resolved so fonts and assets are properly served by nginx.
