### ISSUE TITLE
Create an entity named `pipeline` to represent a tasks trigger request 

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#824]
## Description
Now POST request to `/tasks` will create multiple tasks, we need an entity to represent the triggeration to help user for task management.

Currently, `POST /tasks` accepts multiple tasks like following:
```json
[
  [
    {
      "plugin": "gitlab",
      "options": {
        "projectId": 8967944
      }
    },
    {
      "plugin": "jenkins",
      "options": {}
    }
  ],
  [
    { "plugin": "gitlab-domain", "options": {} },
    { "plugin": "jenkinsdomain", "options": {} }
  ]
]
```
and then return multiple task ids to client.

This is hard for client side to keep track of execution, one would have to check every single task status to determine wether they were all finish or fail...

## Describe the solution you'd like
Create an new endpoint `/pipelines` to replace `/tasks` which accept the same tasks array along with other information, return a single `pipeline_id` for client side to keep track of the execution.

`POST /pipelines`
```json
{
    "name": "EE sync - 20211119",
    "tasks": [ ... ]
}
```
response:
```json
{
    "id": 1,
    "name": "EE sync - 20211119",
    "createdAt": "2021-11-19T11:14:00+08:00",
    "finishedAt": null,
    "status": "TASK_CREATED",
    "message": null,
    "totalTasks": 4,
    "finishedTasks": 3,
    "spentSeconds": 0,
    "tasks": [...]
}
```

And then client side can keep track of progress by 
`GET /pipelines/1`
```json
{
    "id": 1,
    "name": "EE sync - 20211119",
    "createdAt": "2021-11-19T11:14:00+08:00",
    "finishedAt": null,
    "status": "TASK_RUNNING",
    "message": null,
    "totalTasks": 5,
    "finishedTasks": 3,
    "spentSeconds": 10,
    "tasks": [...]
}
```

Client side can query all pipeline by 
`GET /pipelines?status=TASK_RUNNING&pending=1&page=1&=pagesize=10`
```json
{
    "pipeline": [
        {
            "id": 1,
            "name": "EE sync - 20211119",
            "createdAt": "2021-11-19T11:14:00+08:00",
            "beganAt": null,
            "finishedAt": null,
            "status": "TASK_RUNNING",
            "message": null,
            "totalTasks": 5,
            "finishedTasks": 3,
            "spentSeconds": 10,
            "tasks": [...]
        }
    ],
    "count": 1
}
```
- `status`: filtering on status
- `pending`: filtering by `finishedAt is null` 

Client side can cancel a single pipeline
`DELETE /pipelines/1`

Query task details including progress:
`GET /pipelines/1/tasks`
which return tasks belongs to a specific pipeline

Notification moved to `pipeline` level, and redefined as `PipelineStatusChanged` which would be trigger when pipeline finished, either `COMPLETED` or `FAILED`.
```golang
	err = notificationService.PipelineStatusChanged(PipelineNotification{
		PipelineID: pipeline.ID,
		CreatedAt:  pipeline.CreatedAt,
		UpdatedAt:  pipeline.UpdatedAt,
		BeganAt:    pipeline.BeganAt,
		FinishedAt: pipeline.FinishedAt,
		Status:     pipeline.Status,
	})
```
@narrowizard 

## Has the Feature been Requested Before?
No

## Additional context
EE need sth like above to reduce their tasks management complexity

**Comment by liangjingyang** [comment]
> GET /task/pending rename to GET /tasks?pending=1

What about `GET /tasks?status=TASK_PENDING`

**Comment by klesh** [comment]
@liangjingyang  this is redesigned because we dont really have a status named `TASK_PENDING`,  statuses like `CREATED` and `RUNNING` are all considered `pending`

**Comment by liangjingyang** [comment]
Got it. `pending=1` will be converted to something like `status in [CREATED, RUNNING]`, right? I just meant we could convert `status=PENDING` to `status in [CREATED, RUNNING]` in the same way.

Or consider to support array in query parameters?

**Comment by klesh** [comment]
> Got it. `pending=1` will be converted to something like `status in [CREATED, RUNNING]`, right? I just meant we could convert `status=PENDING` to `status in [CREATED, RUNNING]` in the same way.
> 
> Or consider to support array in query parameters?

@liangjingyang 
As I said above, we don't actually have a status called `PENDING`, it's odd to accept such a parameter for status, and I plan to fulfill `pending=1` by filtering `ended_at is null` (to be added to record time spent on task) which has no direct connection to `status`, which make more sense IMO.

We could add multiple statuses for status filtering, but it should not be used to address the same problem here: the `pending=1` is mainly for `config-ui` to know if there were unfinished tasks.  In the future, we may add more detailed status like `TASK_SCHEDULED` which is also a `PENDING` task, in this case, `config-ui` would have to add it to its list for **unfinished** tasks as well. By `pending=1` approach, `config-ui` or other clients wouldn't need to do anything at all.

**Comment by hezyin** [comment]
@klesh 

1. Gitlab pipelines API should be a good reference: https://docs.gitlab.com/ee/api/pipelines.html Maybe we want to add "Get all pipelines" and "Cancel a pipeline" to our APIs.
2. How do we display progress in this new "A pipeline consists of a 2D array of tasks" model? One proposal is like the following:

a) At the task level, each task can share their progress like "Step 3/9 Collecting issues (1500)"
b) At the pipeline level, each pipeline's progress is represented by the status of its tasks (how many are finished and still running)

**Comment by hezyin** [comment]
@klesh When we reviewed @e2corporation's latest UI designs today, @joncodo brought up a good point that it could be cumbersome for users to go through the trigger page every time they need to trigger data collection. Instead, we could ask users to create the pipeline once and reuse it whenever they need to collect data.

Under this design, we're splitting the original `Pipeline` concept into two parts:

1. A new `Pipeline` component that only stores the task topology and collection options
2. A `PipelineRun` component that represents a specific run of a `Pipeline`, stores the start time, end time, status, and other info related to a run

This is similar to how airflow models `DAG` and `DAGRun`. Following this data model, below is the corresponding visual mockups:

1. Pipelines page
![IMG_9503](https://user-images.githubusercontent.com/2908155/143329651-00b668eb-696a-47fe-9d7e-c9e385ac8eb7.jpg)

2. Create a new pipeline page (adapted from the trigger page)
![IMG_9500](https://user-images.githubusercontent.com/2908155/143329697-7d9c757d-50bb-4216-a791-c3414cedc956.jpg)

3. Individual pipeline run page
![IMG_9504](https://user-images.githubusercontent.com/2908155/143329693-3ea6c50c-4093-4072-8f43-8926c20acfa9.jpg)

The design above used airflow and GitLab pipeline as reference. Please have a discussion about whether it's worth it to go this route with @Startrekzky 

cc @mindlesscloud @joncodo @kevin-kline

**Comment by klesh** [comment]
## For long term, the idea is solid. I suggest that we change the names/terms though

1. `pipeline` to sth like `pipeline template` or `blueprint` or `cronjob`, sth like `gitlab-ci.yml` which keep changing overtime
2. `pipeline run` to `pipeline`  stand for a historical execution record which is immutable just like gitlab's

## How should we attack

This cron thing we need more time to deliver, as well as config-ui design. I suggest that we do the immutable `pipeline` first, and add the `template` feature on top of it.

1. Implement the pipeline with previous design, itself can function properly
2. Implment a `pipeline` rerun function which create a new `pipeline` by copying specified one, this is easy to do and much like how gitlab pipeline behave. This can make do before this `template` feature ready.
3. Implement this `template/blueprint` or `cronjob` feature so it can trigger `pipeline` automatically or manually.

Can we move the futher discussion to another ticket? 

@hezyin @Startrekzky @mindlesscloud @joncodo @kevin-kline
