### ISSUE TITLE
Create an plugin example repo 

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#825]
## Description
To help developer start their own plugin development quickly.

## Describe the solution you'd like
1. Create an example repo on merico-dev org
2. Make sure exmaple code can compile successfully
3. Make sure `devlake` can load and execute plugin successfully
4. Write documentation for development

## Has the Feature been Requested Before?
No

## Additional context
EE need to publish some closed source plugin

**Comment by joncodo** [comment]
# Questions

1. Is this meant to be in a separate repo? Maybe the code compiles to a go pkg and we import it?
2. Can I hook this up to the pokemon api as a sample?
3. What is the EE plugin trying to do? If I knew that, I could help them get it started

**Comment by klesh** [comment]
> # Questions
> 1. Is this meant to be in a separate repo? Maybe the code compiles to a go pkg and we import it?
> 2. Can I hook this up to the pokemon api as a sample?
> 3. What is the EE plugin trying to do? If I knew that, I could help them get it started

1. Yes, separate repo. No, code should compiled to a `.so` file, because it may be `closed-source` plugin, and we load it dynamically, check the `plugins/plugins.go` we load the binary artifact, not by pkg in source code form.
2. Not sure what pokemon api is? 
3. They want to develop and distribute some `closed-source` plugin, in order to implement some EE functionalities, you could talk to @narrowizard if you needed more context.

**Comment by joncodo** [comment]
# PLAN OF ATTACK
## Can it work locally as a developer?
- [ ] create a repo https://github.com/merico-dev/ee-lake-plugin
- [ ] Init that repo with a very basic plugin
- [ ] Compile that plugin into a .so file
- [ ] copy that file into lake manually and make a /pipelines request that works and pulls data from plugin
## How does an end user work with it?
- [ ] Tell lake which 3rd party plugins they want
- [ ] When they run docker compose, all the files get to the right places

**Comment by joncodo** [comment]
# Alternative Proposal

I think the time has come to break apart our single repo idea. We should make lake the main core application and separate the config-ui and the plugins.

If we want EE to make a private plugin, or anyone to make their own plugin, we don't want to manage the git workflow or plugin itself. The maintainers of those plugins should do so.

If the core is then stored in the cloud, the plugins can install the core and implement the required methods. This will allow us to expose a module for:

- DB migrations
- API routes 
- Access to other Lake data models 
- Access to Utils

I think actually has to happen in order complete this task since there are methods we need in the new repo that only contains a plugin.

IE: 

- [ ] Creating new models
```
func (plugin Jira) Init() {
	err := lakeModels.Db.AutoMigrate(
		&models.JiraProject{},
```

- [ ] Creating new tool layer dashboards

- [ ] Exposing the resource handler

```
func (plugin Jira) ApiResources() map[string]map[string]core.ApiResourceHandler {
	return map[string]map[string]core.ApiResourceHandler{
		"echo": {
			"POST": func(input *core.ApiResourceInput) (*core.ApiResourceOutput, error) {
				return &core.ApiResourceOutput{Body: input.Body}, nil
			},
		},
```

- [ ] Checking for required plugin functions

```
func (plugin Jira) Init() {
```

- [ ] Unmarshalling responses
```
	jiraApiBoard := &JiraApiBoard{}
	err = core.UnmarshalResponse(res, jiraApiBoard)
```

- [ ] All requests are made with the api
```
type JiraApiClient struct {
	core.ApiClient
}
```

- [ ] Worker schedulers and other utils can be shared
```
type WorkerScheduler struct {
	waitGroup    *sync.WaitGroup
	pool         *ants.Pool
	ticker       *time.Ticker
	workerErrors *[]error
	ctx          context.Context
}
```

**Comment by joncodo** [comment]
Spoke with Klesh again and here are the findings:

1. Set up a repo that compiles but pulling down the core packages from the cloud
2. Install the third party repo as a go module in lake
3. Put the .so file in the plugins/bin directory
4. In docker compose, mount the 3rd party plugins
5. In the code for lake, make it load the regular plugins and the 3rd party plugins

NOTE: The third party plugins can run standalone with a function like this:

```

// standalone mode for debugging
func main() {
	args := os.Args[1:]
	if len(args) < 2 {
		panic(fmt.Errorf("Usage: jira <source_id> <board_id>"))
	}
	sourceId, err := strconv.ParseUint(args[0], 10, 64)
	if err != nil {
		panic(fmt.Errorf("error paring source_id: %w", err))
	}
	boardId, err := strconv.ParseUint(args[1], 10, 64)
	if err != nil {
		panic(fmt.Errorf("error paring board_id: %w", err))
	}

	PluginEntry.Init()
	progress := make(chan float32)
	go func() {
		err := PluginEntry.Execute(
			map[string]interface{}{
				"sourceId": sourceId,
				"boardId":  boardId,
				//"tasks":    []string{"enrichIssues"},
			},
			progress,
			context.Background(),
		)
		if err != nil {
			panic(err)
		}
	}()
	for p := range progress {
		fmt.Println(p)
	}
}

```

**Comment by joncodo** [comment]
@klesh who is the leader of team that needs this plugin? Is it @narrowizard ?

**Comment by narrowizard** [comment]
Thank you for your implement @joncodo , I will check the demo repo tomorrow. Sorry for not responsing for some days.

**Comment by narrowizard** [comment]
I have tried to load the private plugin, and it works well.

**Comment by joncodo** [comment]
Ok great! I will make it work in docker-compose now so you can load it up for your bosses easily @narrowizard

**Comment by joncodo** [comment]
For now, I will close this until we are actually using the external plugin. This will give us a real example and we can then hook it up to docker compose when the time comes. I think this will help us to mature this plugin process.

Closing for now
