### ISSUE TITLE
Config UI: Type mappings Should not require you to press enter to save

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#831]
<img width="1094" alt="Screen Shot 2021-11-19 at 11 15 39 AM" src="https://user-images.githubusercontent.com/3011407/142646195-e4095599-f7d4-4b6c-9f17-f0816a329abb.png">

**Comment by joncodo** [comment]
This happened after I saved it:
<img width="1171" alt="Screen Shot 2021-11-19 at 11 16 54 AM" src="https://user-images.githubusercontent.com/3011407/142646338-bf7ef427-2b41-45b3-a12f-77c64ab37b92.png">

Looks like the type mappings are not being sent to the backend

**Comment by kevin-kline** [comment]
They are being sent. You have to press enter to register each individual mapping before saving settings.

![image](https://user-images.githubusercontent.com/27032263/142651589-cbf18e3e-35e6-4a78-a06f-ce8e5ef3e569.png)

![image](https://user-images.githubusercontent.com/27032263/142651651-678dcef9-6d32-40b3-b894-a660822a9a7e.png)

**Comment by joncodo** [comment]
You should not have to press enter. That is not intuitive. @e2corporation can we change this?

**Comment by klesh** [comment]
I think this is already been resolved in the past, feel free to re-open if I was wrong
