### ISSUE TITLE
Would Devlake provide k8s deployment option?

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/lake#844]
## Description

DevLake is needed to support deployment with Kubernetes

**Comment by daniel-hutao** [comment]
Deployment/Service/ConfigMap/... -> helm chart -> Operator

**Comment by hezyin** [comment]
@daniel-hutao Thanks for making this feature request. Just to get clarified, are you asking for k8s deployment option for Dev Lake?

**Comment by daniel-hutao** [comment]
Compared with the _Docker_ and _docker-compose_ deployment methods, I think the **Kubernetes** deployment method is used more. So I hope **Dev Lake** can provide deployment capabilities similar to _kubectl apply -f xxx.yaml_ or _helm install devlake_

**Comment by hezyin** [comment]
Thanks for the clarification, I have changed the issue title accordingly. It won't be our short term priority, but we're happy to accept PRs:)

**Comment by daniel-hutao** [comment]
/assign @daniel-hutao 

I'd like to contribute a pr to enable DevLake to support `helm chart` deployment

**Comment by Startrekzky** [comment]
Done
