### ISSUE TITLE
Consider `CLA`?

### ISSUE THREAD

**Issue by yihong0618** [merico-dev/lake#847]
As a commercial open source project can this repo consider should contributors be considered to sign a [CLA](https://cla.developers.google.com/clas) ？

e.g.
https://github.com/cla-assistant/cla-assistant

**Comment by klesh** [comment]
@hezyin Please take a look

**Comment by hezyin** [comment]
@yihong0618 Thanks for bringing up the CLA issue. This is under our radar but probably will not get implemented in the short term to reduce the friction to contribute to Dev Lake.

**Comment by klesh** [comment]
Hi @yihong0618 , due to the fact that this project have already been donated to Apache,  `CLA` is a kind of  a must.
So, yes, we are not only consider, but also accepted!
Thanks for your proposal, closing it now.

**Comment by yihong0618** [comment]
cool
