### ISSUE TITLE
Can not config GitHub plugin using docker-compose

### ISSUE THREAD

**Issue by yihong0618** [merico-dev/lake#853]
docker-compose 

can not config GitHub plugin
![image](https://user-images.githubusercontent.com/15976103/143179030-06ef62ba-f820-4432-920b-fda45cdf76c7.png)

xhr shows error "open .env: is a directory"

env `win10 wsl1`

**Comment by yihong0618** [comment]
the `.env` file in the container mount as a `dir` .
Caused the bug, I am not sure its a common problem or not.

Maybe I can take a `PR` to fix this 
@klesh

**Comment by klesh** [comment]
@yihong0618 
No, not a common problem that I know of, this is the first time to my knowledge.
Did you `cp .env.example .env` before running `docker-compose up` ?

**Comment by yihong0618** [comment]
Yes, I did, and I searched it found maybe the compose file problem.
https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume

I comments the `volumns lines` everyting goes well

**Comment by Startrekzky** [comment]
Since this issue has been inactive for quite a while, I'll close it. Feel free to reopen it if the problem hasn't been addressed.
