### ISSUE TITLE
How can we get source id for Jira configuration in our private jira service.

### ISSUE THREAD

**Issue by Seins** [merico-dev/lake#854]
## Question
How can we get source id for Jira configuration in our private jira service.

**Comment by klesh** [comment]
You can connect to multiple jira data sources by adding connection on "JIRA Integration" page.
And the `sourceId` can be observed on the listing page:
![image](https://user-images.githubusercontent.com/61080/143205319-1a906688-2845-4654-b27e-0d576c92a065.png)
