### ISSUE TITLE
Add Multi-Source Functionality to All Plugins

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#859]
## Description
Right now, we are only storing configuration in an .env file for all but Jira. This limits our other sources to 1. If we want to enable multiple sources for other plugins with different auth tokens, we need to save sources in the DB, and eliminate .env variables.

- [ ] GitLab
- [ ] GitHub
- [ ] Jenkins
- [ ] AE

## Describe the solution you'd like
Change everywhere we read/write to/from .env in relation to GitLab to read/write to/from DB.

## Has the Feature been Requested Before?
No.

**Comment by kevin-kline** [comment]
2 directions 

1. Jira style multi-source functionality
2. "Framework" handles multi-source.

We haven't decided yet, so this is on hold.

**Comment by klesh** [comment]
This is huge, shoud be tackled one by one and in differents time. close this for now.
