### ISSUE TITLE
cannot get gitlab line of code

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake#866]
## Describe the bug
I want query gitlab MR line of code, but they are empty.

## To Reproduce
There is no column in https://gitlab.com/api/v4/projects/XXXX/merge_requests/XXXXX/commits?per_page=100

## Screenshots

![image](https://user-images.githubusercontent.com/3294100/143419018-b488b3ca-1913-4028-baa5-4423958385ea.png)
![image](https://user-images.githubusercontent.com/3294100/143419972-28fa96c9-76ee-4e4a-b818-7437d9e58210.png)

**Comment by klesh** [comment]
@joncodo  Can you take a look at this? Seems like gitlab api doesnt return `additions` and `deletions`

**Comment by kevin-kline** [comment]
> @joncodo Can you take a look at this? Seems like gitlab api doesnt return `additions` and `deletions`

This is true for MR commits. We don't get Additions/Deletions from the API when collecting _merge request commits_ . We only get Additions/Deletions from _commits_. Use _commits_ to calculate additions / deletions. 

What do we need to calculate here? Additions / Deletions on a MR basis?

**Comment by likyh** [comment]
> > @joncodo Can you take a look at this? Seems like gitlab api doesnt return `additions` and `deletions`
> 
> This is true for MR commits. We don't get Additions/Deletions from the API when collecting _merge request commits_ . For reference: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits
> 
> We only get Additions/Deletions from _commits_. We use _commits_ to calculate additions / deletions.
> 
> What do we need to calculate here? Additions / Deletions on a MR basis?

So will we delete the corresponding columns in the data table? Or cal it?

**Comment by klesh** [comment]
> > > @joncodo Can you take a look at this? Seems like gitlab api doesnt return `additions` and `deletions`
> > 
> > 
> > This is true for MR commits. We don't get Additions/Deletions from the API when collecting _merge request commits_ . For reference: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits
> > We only get Additions/Deletions from _commits_. We use _commits_ to calculate additions / deletions.
> > What do we need to calculate here? Additions / Deletions on a MR basis?
> 
> So will we delete the corresponding columns in the data table? Or cal it?

Which way do u prefer.

**Comment by likyh** [comment]
> > > > @joncodo Can you take a look at this? Seems like gitlab api doesnt return `additions` and `deletions`
> > > 
> > > 
> > > This is true for MR commits. We don't get Additions/Deletions from the API when collecting _merge request commits_ . For reference: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits
> > > We only get Additions/Deletions from _commits_. We use _commits_ to calculate additions / deletions.
> > > What do we need to calculate here? Additions / Deletions on a MR basis?
> > 
> > 
> > So will we delete the corresponding columns in the data table? Or cal it?
> 
> Which way do u prefer. @likyh

All is ok. Now I use them by other way.

**Comment by klesh** [comment]
I think we should delete those column for now. @kevin-kline
