### ISSUE TITLE
Jira trigger fails

### ISSUE THREAD

**Issue by aanyoka** [merico-dev/lake#868]
## Describe the bug
On http://localhost:4000/triggers changing the board id on the Jira properties in the data trigger JSON results in an error:

"_TASK_FAILED invalid character 'B' looking for beginning of value_"

## To Reproduce
Steps to reproduce the behaviour:
1. Go to http://localhost:4000/triggers
2. Change the board Id to the appropriate board id on you Jira project.
3. Click "Trigger Collection"

## Expected behaviour
The trigger to complete (not throw the error)

## Screenshots
![image](https://user-images.githubusercontent.com/95045145/143481471-c32ed189-3c59-4b2e-ba54-a41ca662db97.png)
![image](https://user-images.githubusercontent.com/95045145/143481488-720a745b-8908-4b2d-ac27-20aff804b834.png)

**Comment by klesh** [comment]
@aanyoka Is this JIRA Server or JIRA Cloud?

**Comment by aanyoka** [comment]
@klesh This is Jira Cloud

**Comment by klesh** [comment]
@aanyoka Did you follow this guide to configure the jira api token?
A invalid token would cause this error.

**Comment by aanyoka** [comment]
Hi @klesh, so we did follow the guide:
(we censored any sensitive information)
![image](https://user-images.githubusercontent.com/95045145/144082768-a05eae3c-c56d-4d82-8604-72ec4addea70.png)
![image](https://user-images.githubusercontent.com/95045145/144082971-cd7c4ec6-3201-4f1b-8b61-7cc9aa8ac62f.png)

The status says that it is online, I'm not sure if you can see anything immediately wrong with the way we have set it up. We have used a Jira API token like the guide mentioned.

**Comment by klesh** [comment]
@aanyoka Sorry for replying so late, did you generate the token with following button, and enter your email and api token?
![image](https://user-images.githubusercontent.com/61080/145130757-d1a85c9c-014b-4370-b38a-8e69821c0bae.png)
I would need log from devlake for investigation, would you like to reproduce the error and run following command and post the jira error message part here?
```
docker-compose logs devlake
```
Sorry for your inconvenience
