### ISSUE TITLE
Removed lines of code

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#89]

**Comment by joncodo** [comment]
<img width="301" alt="Screen Shot 2021-07-30 at 1 36 38 PM" src="https://user-images.githubusercontent.com/3011407/127684288-422c5d9e-11ba-426b-a391-3bfb35f2ca2f.png">

```
SELECT
  count(id) as "Commits",
  sum(additions) as "Additions",
  sum(deletions) as "Deletions",
  sum(additions - deletions) as "LOC"
FROM gitlab_commits
WHERE
  $__timeFilter(gitlab_commits.committed_date) AND gitlab_commits.project_id = $ProjectId
ORDER BY 1
```

https://github.com/merico-dev/lake/blob/main/src/plugins/gitlab-pond/src/collector/commits.js

The difference with this one is that it takes into account github stats as well. `<url>?with_stats=true`. 

@UltimateBeaver to review and close

**Comment by klesh** [comment]
sum(additions - deletions)  could produce negative outcome which is problematic when calculating 'Bugs count per 1k LOC'
