### ISSUE TITLE
Domain layer entity `commits` should not have `RepoId` column

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#890]
## Describe the bug
Because all domain layer entities were converted from tool layer entity, using AutoIncremental PK is not ideal.
All domain layer entities should not have column like `XxxxId` as foreig key to another domain layer entity

## To Reproduce
![image](https://user-images.githubusercontent.com/61080/144045174-00d33014-6a17-4946-916a-9e9c6672de9e.png)

## Expected behavior
Should be `RepoOriginKey` with type `varchar`, and the value should be generated by `OriginKeyGenerator`

**Comment by joncodo** [comment]
Based on this comment by @hezyin I think we should either have both domainOriginKey and id?
<img width="1228" alt="Screen Shot 2021-12-03 at 1 54 12 PM" src="https://user-images.githubusercontent.com/3011407/144649936-4cf36d7c-cc60-4d5c-8745-816d4fd6fd7a.png">

**Comment by joncodo** [comment]
When working with the code in general, its not that easy to work with these compound keys. However, they are useful as primary keys since they are guaranteed to be unique. But when you want to join to other tables, how do you extract the ids you want?
