### ISSUE TITLE
Grafana: We should remove all dashboards except the ones that answer our three questions

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#891]
Approved @Startrekzky ?

Its confusing to the user and hard to maintain. We will not delete them but instead move them to an _archive folder that grafana will not see

<img width="477" alt="Screen Shot 2021-11-30 at 9 12 56 AM" src="https://user-images.githubusercontent.com/3011407/144053760-c72b6292-2fd8-47d7-9a43-ad1f9857f7fe.png">

**Comment by Startrekzky** [comment]
I think we should at least keep demo dashboards and data-source-specific dashboards for now. 
In the next step, we should change the sources of the data-source-specific dashboards to the domain layer.
What do you think? @hezyin @joncodo @klesh

**Comment by klesh** [comment]
@Startrekzky I dont understand the part of "change the sources of the data-source-specific dashboards to the domain layer"

**Comment by joncodo** [comment]
Archive folder solution for now. Do not delete this work.
