### ISSUE TITLE
Add release and tag to tool layer from GitLab

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake#894]
## Description
I want to query jenkins build's commit and gitlab MR relations in dev lake.
But now triforce not collect it.
My target is building MR and RELEASE relations.

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/3294100/144063195-1a186b0e-323b-445e-8beb-d5265a262d68.png)

## Has the Feature been Requested Before?
I don't konw 😹

## Describe alternatives you've considered
Don't know either. Maybe add some collectors ?

**Comment by likyh** [comment]
So when will it finish? @Startrekzky

**Comment by Startrekzky** [comment]
> So when will it finish? @Startrekzky

Hopefully by Dec 16

**Comment by joncodo** [comment]
So before I can work on this I need some questions answered @likyh 

1. What is the flow of data that you currently have? Is it something like this?

- A developer makes a MR in gitlab
- Jenkins pipeline is triggered on the commit that was pushed before the code is merged
- Jenkins pulls the commit and runs the pipeline
- Jenkins reports back success or failure to the gitlab MR

2. How do you know which MRs are linked to which release? Is it something like this?

- You make a release in gitlab like v2
- You look at all the commits in v1 and compare it to v2
- Then you figure out which MRs were linked to the commits between v1 and v2? (How is this step done?)

3. The data model you want is:

- The domain layer of commits has all commits
- There is a new model in the domain layer called `release`
- Each commit is linked to a `release`
- There is a domain layer model called `merge_request`
- Each `commit` is linked to a `merge_request`

4. How should be able to populate this data with gitlab only. How does Jenkins builds fit into this model?

**Comment by likyh** [comment]
Not exactly.

1. What is the flow of data that you currently have? Is it something like this?
* A developer start a build in jenkins
* Jenkins pulls the commit from gitlab (and jenkins will save them) and runs the pipeline (create a release)
* Jenkins add a git tag and push to gitlab

I wanted to get release-commit relations from jenkins build and its' git commit changes, But now I think maybe I can get release-commit relations from gitlab only.

**Comment by joncodo** [comment]
I think we should do this from github only. And we can track releases in the gitlab plugin. I think Jenkins is a very custom way to do this and we should not capture this from Jenkins.

What if we just have a table in gitlab plugin for releases and we link commits to release or MR to release in some way?

**Comment by joncodo** [comment]
is 

> 3\. The data model you want is:

Is this the data model you want to see?

**Comment by likyh** [comment]
> > 3. The data model you want is:
> 
> Is this the data model you want to see?

I think the top 3 is OK for me. Or we can only have new model called `tag`.  Either is acceptable.

**Comment by joncodo** [comment]
I think this also means we need to migrate from scratch and remove the auto migrate line

**Comment by joncodo** [comment]
# PLAN OF ATTACK

DB Migrations
1. We need tests to make sure we can insert every model type as of now
2. We need to migrate from scratch
3. All migrations should be done with SQL
4. All test should still pass after refactor
5. Tests will help to document the data model to our users

**Comment by Startrekzky** [comment]
Hi @joncodo, in order to reduce the workload of the issue, I discussed with @likyh, he agreed that we can first collect `release` and `tag` information in GitLab collector, to make sure that data exists in the GitLab tool layer and he can query it sooner.
We can work on the Github collector and GitLab/Github converters in the future.

**Comment by klesh** [comment]
@likyh please update progress

**Comment by likyh** [comment]
> @likyh please update progress

@joncodo

**Comment by joncodo** [comment]
I have not worked on this yet
