### ISSUE TITLE
Make configure: not loading for hezheng

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#899]
<img width="1303" alt="Screen Shot 2021-11-30 at 3 25 58 PM" src="https://user-images.githubusercontent.com/3011407/144114291-ad282a48-1c8c-48ff-89a6-d028802e495f.png">

This is because of this line: 

```
upstream devlake {
    server ${DEVLAKE_ENDPOINT} fail_timeout=5s max_fails=5;
}
server {
  listen 80;
  server_name localhost;
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  location /api/ {
    rewrite /api/(.*) /$1  break;
    proxy_pass http://devlake;
  }

  location /grafana {
    rewrite /grafana(.*)$ ${GRAFANA_ENDPOINT}$1;
  }
}

```

I think GRAFANA_ENDPOINT and DEVLAKE_ENDPOINT are not being set when running `make configure` in isolation

**Comment by klesh** [comment]
cause: DEVLAKE_ENDPOINT and GRAFANA_ENDPOINT is missing from `.env` file
solution: to add a script which check `.env` against `.env.example` maybe

**Comment by klesh** [comment]
please follow the README, not a bug
