### ISSUE TITLE
Config-UI: Allow User to configure Tasks on each Plugin in a Pipeline

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#924]
## Description
Each plugin has the option to execute an array of tasks rather than the default which runs all tasks. This allows the user to select which tasks they wish to execute. For example, if executing GitLab, they may include:

"tasks": ["collectIssues", "enrichIssues", "collectMrs"]

## Describe the solution you'd like
It would be a nice layer of customization to allow the user to configure the tasks for each plugin to execute on a pipeline.

## Has the Feature been Requested Before?
No.

**Comment by klesh** [comment]
Resolved.
