### ISSUE TITLE
Grafana Charts: Dynamic Generation

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#929]
## Description
Users can access Grafana charts whether or not they have the data to support them. This can lead to a confusing user experience when charts are broken or say "No Data".

## Describe the solution you'd like
Ideally, I'd like to see us implement dynamic generation of charts based on data the user definitely has in their DB. Thus we only provision charts that will be filled with data.

## Has the Feature been Requested Before?
We have talked about it.

**Comment by klesh** [comment]
Not a viable solution.
Not cost effective, too much involve not much gain.
Close for now, feel free to re-open
