### ISSUE TITLE
[Jira] Issue status mapping should not based on issue type

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#934]
## Description
Now our jira issue status mapping is based on issue type, what means each jira issue type has serials of issue status mappings. In most situation and semanticly, we only need a global status mapping for all issue types.

**Comment by leglars** [comment]
Just a reminder, the new global status is a set of standard statuses across the whole domain. We try to use a mapping to normalize the differences between all sources, such as Jira, TAPD, Github, Gitlab etc.

**Comment by klesh** [comment]
AFAIK, technically, different types can have same status name representing totally different semantics( in sense of Pending/InProgress/Done).
But I'm not sure if the semantic was binded to `status` entity, and assuming the term "global" means mapping status without  nesting them within types, if both were true,  `status id` mapping make sense, so, I'm assuming you were talking about the `status id` mapping?
Description was too vague, please add more context and detail.

**Comment by narrowizard** [comment]
We will use default statusCategory mapping. And add custom mapping settings by status name (within each issue type) in the future.  
Closed.
