### ISSUE TITLE
Gather User Application Usage Information

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#936]
## Description
We should decide on some questions we'd like answered from a marketing and business perspective. @MaximDub @nitinvasanth 

Some example questions:
- Who is trying out the product?
- What company do they work for?
- What is their customer profile?

## Describe the solution you'd like

Some examples:

- Try different technologies designed for this purpose (Scarf, etc.)
- Prompt Users to register with their email address 
- Prompt Users for feedback questionnaire
- Use GitHub Insights and DockerHub download count

## Has the Feature been Requested Before?
https://github.com/merico-dev/lake/issues/793 

## Further Questions

- What is the business trying to achieve with this information?

made with @joncodo

**Comment by klesh** [comment]
Maybe we can start with Anonymous feedback first.
