### ISSUE TITLE
We should remove OriginKey and replace it with GUID and compound unique keys

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#937]
Comparison doc of both solutions

https://merico.feishu.cn/docs/doccnL2Sz9X9nrCXycoIFaJOgEb#

## Related tickets:

#890 

## What was OriginKey meant to do

1. Guarantee a unique key for the table
2. Provide information for where the data came from in terms of a plugin

## What is wrong with OriginKey

1. We need a lot of code to support it
2. Its hard to understand for users
3. If you want to query a part of it with SQL and Grafana, you can't extract parts of the key out.

## Alternative solution proposal

1. Each table has a GUID that a guaranteed unique string. This allows us to reference it from other tables and allows it to be a primary key
2. Each table needs to maintain a UNIQUE constraint or compound UNIQUE constraint that prevents duplicate records from being inserted.
3. When a table like `commit` references `repo`, the `commit` table will have a column called `repoId` which will reference the repo GUID
4. We remove all code in the file `models/domainlayer/okgen/originkey_generator.go`
5. Each table has a separate column called `plugin_source` which tells you where the data came from.

**Comment by klesh** [comment]
closed by #945
