### ISSUE TITLE
feat: auth token field should be password type

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#941]
## Config UI / Integrations / Configure Connection/ `AuthToken` Field

For the **Configure Connection** module, the **Auth Token** is sensitive and could benefit from being a password type field with a toggle button to control visibility of entered value.

- [ ] Auth Token should be `password` type (for all Providers)
- [ ] Field value should have the ability to switch between _visible_ and _hidden_

<img width="1030" alt="Screen Shot 2021-12-07 at 6 09 14 PM" src="https://user-images.githubusercontent.com/1742233/145120724-f4253be8-f21e-400a-bc87-d79f31f3ad49.png">

**Comment by klesh** [comment]
Will be addressed by #1862
