### ISSUE TITLE
Should report an error if we set wrong auth info to jira source.

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#942]
## Description
When we setting a jira source, we want to know if the endpoint as well as the auth info is correct.

## Describe the solution you'd like
I suggest that lake should return specific error info when something is wrong. For example:
- Tell if the endpoint is resolvable.
- Tell if the endpoint is connectable.
- Tell if the endpoint is a valid jira api server.
- Tell if the auth info is right.

## Has the Feature been Requested Before?
No

**Comment by joncodo** [comment]
So we have something for this now in the routes called: TestConnection.

`GET /github/test`

```
func (plugin Github) ApiResources() map[string]map[string]core.ApiResourceHandler {
	return map[string]map[string]core.ApiResourceHandler{
		"test": {
			"GET": api.TestConnection,
		},
```

Here is the implementation

```
/*
GET /plugins/github/test
*/
func TestConnection(input *core.ApiResourceInput) (*core.ApiResourceOutput, error) {
	ValidationResult := core.ValidateParams(input, []string{"endpoint", "auth"})
	if !ValidationResult.Success {
		return &core.ApiResourceOutput{Body: ValidationResult}, nil
	}
	endpoint := input.Query.Get("endpoint")
	auth := input.Query.Get("auth")
	tokens := strings.Split(auth, ",")
	githubApiClient := tasks.CreateApiClient(endpoint, tokens)

	// PLEASE NOTE: This works because GitHub API Client rotates tokens on each request
	for i := 0; i < len(tokens); i++ {
		res, err := githubApiClient.Get("user/public_emails", nil, nil)
		if err != nil || res.StatusCode != 200 {
			logger.Error("Error: ", err)
			return &core.ApiResourceOutput{Body: core.TestResult{
				Success: false,
				Message: core.InvalidConnectionError + fmt.Sprintf("Check token: %v or endpoint %v", tokens[i], endpoint),
			}}, nil
		}
		githubApiResponse := &ApiUserPublicEmailResponse{}
		err = core.UnmarshalResponse(res, githubApiResponse)
		if err != nil {
			logger.Error("Error: ", err)
			return &core.ApiResourceOutput{Body: core.TestResult{Success: false, Message: core.UnmarshallingError}}, nil
		}
	}
	return &core.ApiResourceOutput{Body: core.TestResult{Success: true, Message: ""}}, nil
}
```

**Comment by joncodo** [comment]
Actually, jira already has this too: `plugins/jira/api/jira_connections.go`

**Comment by kevin-kline** [comment]
all plugins have test connection. I need to update docs.

**Comment by narrowizard** [comment]
Thank u for your replies.  
Just a further question, will it be better to test connection when setting jira auth info automatically? I just don't know why we can set a wrong auth info to jira plugin(without auto check).

**Comment by klesh** [comment]
@narrowizard 
Adding a new source is a plain simple operation which can be performed even without internet connection.
TestConnection on the other hand depends only internet connection.
Even if we combined these two operations, the token was verified and stored into database, they still can be expired afterward, so, what is the point of doing this?
Seperate these two operations provide more flexibility for clients IMO.

**Comment by narrowizard** [comment]
Now we check jira auth info using the test api. Close this issue now.  
But the error info returned by jira test api is not concrete enough. I will try to create a PR for that.
