### ISSUE TITLE
Too many commits seem to be pulled in for gitlab pond collector

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#95]
```
async collectByProjectId (db, projectId, forceAll) {
    const commitsCollection = await findOrCreateCollection(db, collectionName)
    for await (const commit of fetcher.fetchPaged(`projects/${projectId}/repository/commits?all=true&with_stats=true`)) {
      commit.projectId = projectId
      console.log('JON >>> saving commit to mongo')
      await commitsCollection.findOneAndUpdate(
        { id: commit.id },
        { $set: commit },
        { upsert: true }
      )
    }
  }
```

I sent a post with: 

```
{
    "jira": {
        "boardId": 8
    },
    "gitlab": {
        "projectId": 8967944
    }
}
```

This is for vdev.co

<img width="339" alt="Screen Shot 2021-07-30 at 2 37 29 PM" src="https://user-images.githubusercontent.com/3011407/127691074-d7905560-0c36-46f3-8662-216ffee9d904.png">

I expected to see only 15k commits in my mongo db but I saw many more. I stopped the process when it hit 350 pages long

<img width="1260" alt="Screen Shot 2021-07-30 at 2 38 13 PM" src="https://user-images.githubusercontent.com/3011407/127691156-64acab52-1d23-4861-837b-d6aa27caa28e.png">

## EXPECTED: 

- I should get the exact number of commits in the repo stored in mongo

## Questions

- Is this maybe all commits from all branch even if they are not merged?

**Comment by joncodo** [comment]
So it seems that when you set `?all=true` in the request, it pulls down duplicate commits.

This is a duplicate commit for the repo ce-backend: 20103385

<img width="980" alt="Screen Shot 2021-07-30 at 3 13 43 PM" src="https://user-images.githubusercontent.com/3011407/127695018-491a3591-35c2-4a72-bd59-38aebfc71341.png">

I am removing the all=true

**Comment by joncodo** [comment]
@klesh I am closing this but you should read it

**Comment by klesh** [comment]
> ```
> async collectByProjectId (db, projectId, forceAll) {
>     const commitsCollection = await findOrCreateCollection(db, collectionName)
>     for await (const commit of fetcher.fetchPaged(`projects/${projectId}/repository/commits?all=true&with_stats=true`)) {
>       commit.projectId = projectId
>       console.log('JON >>> saving commit to mongo')
>       await commitsCollection.findOneAndUpdate(
>         { id: commit.id },
>         { $set: commit },
>         { upsert: true }
>       )
>     }
>   }
> ```
> 
> I sent a post with:
> 
> ```
> {
>     "jira": {
>         "boardId": 8
>     },
>     "gitlab": {
>         "projectId": 8967944
>     }
> }
> ```
> 
> This is for vdev.co
> 
> <img alt="Screen Shot 2021-07-30 at 2 37 29 PM" width="339" src="https://user-images.githubusercontent.com/3011407/127691074-d7905560-0c36-46f3-8662-216ffee9d904.png">
> 
> I expected to see only 15k commits in my mongo db but I saw many more. I stopped the process when it hit 350 pages long
> 
> <img alt="Screen Shot 2021-07-30 at 2 38 13 PM" width="1260" src="https://user-images.githubusercontent.com/3011407/127691156-64acab52-1d23-4861-837b-d6aa27caa28e.png">
> 
> ## EXPECTED:
> * I should get the exact number of commits in the repo stored in mongo
> 
> ## Questions
> * Is this maybe all commits from all branch even if they are not merged?

They screenshot you took was showing the number of commits of `master` branch, according to [Commits API| Gitlab](https://docs.gitlab.com/ee/api/commits.html), we have to pass `ref_name=master` if we were to get exact number from the screenshot .

Per the documentation, I think it's expected to return all commits from all branches when we don't specify `ref_name`.

And for `all` parameter, I guest it will also return commits that don't belong to any branch.

I think we should collect `all` commits in the end, but for MVP, I think it's ok to collect only `master` with `all=false`. Would you like to keep this issue open until we have time to solve?

BTW: the 'duplicated commits' look like a cherry-pick pair, I don't have access to ce repo, so I'm just guessing.

@UltimateBeaver What do you think?
