### ISSUE TITLE
Extract the relation between commits and branch and tag from git repository and store in domain layer

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#952]
## User story
1. As a PMO, I want to see the overall commits and corresponding Eloc that have been committed from specific releases.
2. As a PMO, I want to see the percentage of different types (bug-fixing/feature/docs) of commits.
3. As a QA manager, I want to see each developer's contribution to bug-fixing commits in each release.
4. As a PMO, I want to see how many commits are there in one branch.

## Belongs to issue
#949

**Comment by liangjingyang** [comment]
Relates to #1011

**Comment by klesh** [comment]
Closed by #1109
