### ISSUE TITLE
`feat` Config UI - Pipelines Feature Implementation

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#962]
# Config-UI / Pipelines / Implementation

The **Pipelines** UI Feature is composed of the following primary sub-tasks that are dependent on each other and will be tracked as separate tickets.

Initial development estimates outlined below, will need re-estimation once development is underway.

**Development Tasks**
- Run/Create Pipeline #963
- All Pipeline Runs (Manage Pipelines)  #964
- Pipeline Activity (Run Details) #965
- Post Development Tasks #1049 

See #835 for Concept/UX Details

## Run/Create Pipeline [~3d] (#963) 🏁 Merged PR  975 https://github.com/merico-dev/lake/pull/975
- [x] Apply reference design layout(s)
- [x] Setup Routing & Navigation
- [x] Build Create Pipeline Form
- [x] Apply form constraints & validations
- [x] Error Handling & No-data states
- [x] Functionality Testing w/ User Stories

## All Pipeline Runs (Manage Pipelines) [~4d] (#964) 🏁 Merged PR #1037 
- [x] Apply reference design layout(s)
- [x] Setup Routing & Navigation
- [x] Build Data Table for Pipeline Runs
- [x] Apply Filtering Logic
- [x] Connect Pipeline Actions
  - [x] View Pipeline
  - [x] CANCEL Pipeline
  - [x] Restart/Retry Pipeline
- [x] Add Pagination Support
- [x] Error Handling & No-data states
- [x] Functionality Testing w/ User Stories

**Backlog**
- [ ] Apply Time Selector and Daterange Logic #1043 

## Pipeline Activity (Run Details) [~3d] (#965) 🏁 Merged PR  997 https://github.com/merico-dev/lake/pull/997
- [x] Apply reference design layout(s)
- [x] Setup Routing
- [x] Display Run Activity & Status
- [x] Setup Status Polling
- [x] Connect Pipeline Actions
- [x] Error Handling & No-data states
- [x] Functionality Testing w/ User Stories

## Post-Development Tasks [~2d] (#1049)
- [ ] Deprecate Triggers Page
- [ ] Cleanups & Linting
- [ ] Developer QA
- [ ] Overall Integration Testing
- [ ] Testing + Bugfixes

**Comment by klesh** [comment]
code freezed for v0.6.0, moving this issue to v0.7.0
