### ISSUE TITLE
Grafana charts have incorrect table/field names in SQL

### ISSUE THREAD

**Issue by ggcannard** [merico-dev/lake#970]
## Describe the bug
Some demo Grafana charts are not working, apparently due to database model changes. For example, the SQL statement for DemoDetailedBugInfo.json refers to _summary_, _assignee_origin_key_, and _created_date_ fields, from table _issues_, all of which do not exist. They appear to have been remapped to new names.

## To Reproduce
Open Grafana charts:
* Demo-Average Requirement Lead Time By Assignee
* Demo-Detailed Bug Info

## Expected behavior
No errors when loading charts.

## Screenshots
![image](https://user-images.githubusercontent.com/53152985/146235107-a3864249-0b4e-4a70-b1e7-050f5c81b3be.png)

**Comment by klesh** [comment]
Thanks for your report, were you using the `main` branch? if that was the case, this is expected. Please use the release tag until we finish all development and release a new version
