### ISSUE TITLE
pipelines: `JIRA` data provider/plugin connection test failed

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#982]
## Describe the bug
It appears that the **JIRA Data Provider** is providing a `Failed` Connection Test even though the Authentication credentials used are properly generated per DevLake `README` instructions. This maybe specific to development environment or local database state.

<img width="419" alt="Screen Shot 2021-12-17 at 9 46 04 PM" src="https://user-images.githubusercontent.com/1742233/146627475-284d6659-858a-4370-ad09-7bec36dd6c4f.png">

**Comment by klesh** [comment]
Please verify if the token worked with tools like `postman` first.

**Comment by e2corporation** [comment]
@klesh Will conduct a Postman test to verify.
