### ISSUE TITLE
pipelines: when a pipeline is cancelled it's status should be set to `task_cancelled` or `task_failed`

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#996]
## Pipelines API / Cancel Pipeline

Cancelled tasks are left with a status of `TASK_RUNNING` which is not ideal or accurate. The status of a pipeline that was cancelled should be set to `TASK_FAILED` or `TASK_CANCELLED`

**Comment by e2corporation** [comment]
Relates to #965

**Comment by klesh** [comment]
Relates to #920

**Comment by klesh** [comment]
Will be handled in v0.7.0
